'use strict';

/* ---------- Events Data ---------- */
/* category: 'sound' | 'image' | 'street'  isPrimary: true = 主要活動 / false = 其他活動 */
const EVENTS = [

  {
    num:'02', icon:'🎼',
    img:'images/展演活動_NSO《來自臺灣》2026室內樂美國巡演.png?v=2',
    date:'2026-05-19',
    time:'7:30 p.m.',
    title:'NSO《來自臺灣》2026室內樂美國巡演',
    title_en:'From Formosa: Taiwan Philharmonic Chamber Ensemble 2026 US Tour',
    subtitle:'交響樂 × 排灣族古謠 · Feel the Roots.',
    subtitle_en:'Symphony Orchestra × Paiwan Ancient Ballads · Feel the Roots.',
    location:'Merkin Concert Hall, Kaufman Music Center, New York',
    location_full:'Merkin Concert Hall, Kaufman Music Center, 129 W 67th St, New York, NY',
    desc:'2026年逢美國建國250週年與「美國臺灣傳統週」，NSO國家交響樂團肩負文化外交使命，由小提琴家鄧皓敦、陳怡茹、中提琴家陳猶白及大提琴家連亦先，攜手鋼琴家嚴俊傑與排灣古謠演唱團體「TBT 泰武古謠傳唱」赴美演出。以「島嶼之音」為核心，呈現蕭泰然經典、客家新創及陳可嘉首演新作。',
    desc_en:"Celebrating \"America250\" and Taiwanese American Heritage Week, Taiwan Philharmonic proudly presents \"From Formosa,\" a premier cultural diplomacy tour showcasing Taiwan's rich musical tapestry. Led by Concertmaster Hao-Tun Teng and an elite chamber ensemble, the performance features acclaimed pianist Chun-Chieh Yen and the soulful voices of the Taiwu Ballads Troupe (TBT). The program bridges tradition and modernity, spanning Tyzen Hsiao's iconic Aboriginal Suite, contemporary Hakka compositions, and the world premiere of a new work by composer Ke-Chia Chen.",
    long_desc: '2026年正值美國建國250週年，適逢五月「美國臺灣傳統週」，NSO國家交響樂團肩負文化外交使命，由小提琴家鄧皓敦、陳怡茹、中提琴家陳猶白及大提琴家連亦先，攜手鋼琴家嚴俊傑與排灣族古謠演唱團體「TBT 泰武古謠傳唱」，赴美演出。音樂會以「島嶼之音」為核心，精選蕭泰然的經典《原住民組曲》、當代客家新創作品，並於巡演首場世界首演臺灣作曲家陳可嘉新作。\n\n從純粹的古謠吟唱到當代鋼琴五重奏，展現臺灣音樂從傳統走向國際的精湛實力。在臺美交流的重要時刻，NSO 期許以最頂尖的室內樂陣容與旋律，讓臺灣的藝術人才在國際舞台閃耀，透過音符築起兩國深厚的情誼橋樑，向世界遞出最動人的臺灣文化名片。',
    long_desc_en: "Celebrating \"America250\" and Taiwanese American Heritage Week, Taiwan Philharmonic proudly presents \"From Formosa,\" a premier cultural diplomacy tour showcasing Taiwan's rich musical tapestry. Led by Concertmaster Hao-Tun Teng and an elite chamber ensemble, the performance features acclaimed pianist Chun-Chieh Yen and the soulful voices of the Taiwu Ballads Troupe (TBT). The program bridges tradition and modernity, spanning Tyzen Hsiao's iconic Aboriginal Suite, contemporary Hakka compositions, and the highly anticipated world premiere of a new work by composer Ke-Chia Chen.\n\nFrom the raw beauty of indigenous Paiwan chants to contemporary piano quintets, this concert offers a captivating journey through Taiwan's diverse heritage. At this landmark moment in Taiwan–U.S. cultural exchange, Taiwan Philharmonic brings its finest chamber musicians to shine on the international stage, building a bridge of friendship through music — and presenting the world with the most moving portrait of Taiwanese culture.",
    program: [
      { zh: 'TBT 泰武古謠傳唱組曲', en: 'Taiwanese Indigenous Polyphonic Songs' },
      { zh: '臺灣傳統原住民歌謠組曲（由陳廷銓改編給絃樂四重奏與TBT）', en: 'Taiwanese Indigenous Music for String Quartet & Chorus (arr. Ting-Chuan Chen)' },
      { zh: '陳可嘉：新創臺灣傳統原住民樂曲，給鋼琴五重奏', en: 'Ke-Chia Chen: Commissioned Work for Piano Quintet', premiere: true },
      { zh: '蕭泰然：《原住民組曲》，給鋼琴五重奏', en: "Tyzen Hsiao: The Highlander's Suite for Piano Quintet" },
      { zh: '客家絃樂四重奏新創作品（以樂會客2.0計畫）', en: 'Hakka Music for String Quartets', premiere: true },
      { zh: '柯普蘭：絃樂四重奏二首', en: 'Aaron Copland: Two Pieces for String Quartet' }
    ],
    ensemble: {
      name: '國家交響樂團 Taiwan Philharmonic',
      name_en: 'Taiwan Philharmonic (NSO)',
      bio: '國家交響樂團（NSO）的前身「聯合實驗管絃樂團」成立於1986年，以打造頂尖交響樂團為目標；2014年4月改隸國家表演藝術中心，以「臺灣愛樂」立足國際。經過三十多年耕耘，NSO參與交響樂、室內樂、歌劇、舞蹈、跨界製作，已成為亞洲地區最具指標性的樂團。2022年起由德國指揮家準・馬寇爾擔任音樂總監，以樂團獨特的聲音擔任臺灣的文化大使。',
      bio_en: 'Taiwan Philharmonic (NSO) was established in 1986. Over three decades, it has grown into one of Asia\'s most iconic orchestras, presenting symphonic, chamber, opera, dance, and cross-disciplinary productions. The orchestra has toured internationally, performing at David Geffen Hall (NYC), Kennedy Center (D.C.), Elbphilharmonie (Hamburg), Théâtre des Champs-Élysées (Paris), and Suntory Hall (Tokyo). In 2022, German conductor Jun Märkl became Music Director.',
      website: 'https://npac-nso.org/en',
      facebook: 'https://www.facebook.com/nso.taiwan/',
      instagram: 'https://www.instagram.com/taiwanphilharmonic/'
    },
    performers: [
      {
        instrument: '小提琴', instrument_en: 'Violin',
        name: '鄧皓敦', name_en: 'Hao-Tun Teng',
        bio: '畢業於國立藝術學院。十七歲獲第七屆臺北市交協奏曲比賽優勝。曾任長榮交響樂團首席及助理指揮。現職為國家交響樂團副首席，自2022/23樂季起為代理樂團首席。',
        bio_en: 'Hao-Tun Teng is the Associate Concertmaster of the National Symphony Orchestra and has served as Acting Concertmaster since the 2022/23 season.'
      },
      {
        instrument: '小提琴', instrument_en: 'Violin',
        name: '陳怡茹', name_en: 'Yi-Ju Chen',
        bio: '國立臺灣師範大學學士，東吳音樂系演奏碩士。曾受教育部邀請於國家音樂廳擔任獨奏，並積極投入室內樂領域。現為國家交響樂團第二部小提琴首席。',
        bio_en: 'Yi-Ju Chen is currently the Second Violin Principal of the National Symphony Orchestra. She has performed with the Lincoln Center Chamber Music Society and attended the Huang Junwen Chamber Music Festival.'
      },
      {
        instrument: '中提琴', instrument_en: 'Viola',
        name: '陳猶白', name_en: 'Jubel Chen',
        bio: '印地安納大學及密西根大學畢業。曾加入 New World Symphony，2005年返臺成為國家交響樂團成員。',
        bio_en: 'Jubel Chen graduated from Indiana University and the University of Michigan. He has been a member of the National Symphony Orchestra since 2005.'
      },
      {
        instrument: '大提琴', instrument_en: 'Cello',
        name: '連亦先', name_en: 'Yi-Shien Lien',
        bio: '馬里蘭大學音樂系大提琴演奏博士。曾於林肯中心與甘迺迪中心演出，並世界首演譚盾《臥虎藏龍》協奏曲。',
        bio_en: 'Yi-Shien Lien holds a DMA in Cello from the University of Maryland. She has performed at Lincoln Center and the Kennedy Center, and gave the world premiere of Tan Dun\'s Crouching Tiger, Hidden Dragon concerto.'
      },
      {
        instrument: '鋼琴', instrument_en: 'Piano',
        name: '嚴俊傑', name_en: 'Chun-Chieh Yen',
        bio: '當代最具辨識度的鋼琴家之一。13歲獲第三屆國際柴可夫斯基青少年音樂大賽大獎。演出足跡遍及紐約林肯中心、聖彼得堡愛樂大廳及巴黎柯爾托廳。2008年榮獲第19屆金曲獎「最佳古典演奏獎」。現任國立臺灣師範大學教授。',
        bio_en: 'Chun-Chieh Yen won 3rd Prize at the 3rd International Tchaikovsky Competition for Young Musicians at age 13. He has performed with the Russian National Orchestra and Taiwan Philharmonic at Lincoln Center, St. Petersburg Philharmonic Hall, and Salle Cortot, Paris. Golden Melody Award winner. Professor at National Taiwan Normal University.',
        facebook: 'https://www.facebook.com/PianistChunChiehYEN/',
        instagram: 'https://www.instagram.com/ycchoping/'
      },
      {
        instrument: '古謠傳唱', instrument_en: 'Ballads Troupe',
        name: 'TBT 泰武古謠傳唱', name_en: 'Taiwu Ballads Troupe (TBT)',
        bio: '由查馬克．法拉屋樂於屏東泰武創立，致力傳承排灣族古調，整理出近百首傳統歌謠。曾登上WOMADelaide、WOMAD New Zealand等國際音樂節舞台。2026年4月推出睽違14年全新專輯《Kivaljuq－歌，正在綻放》。',
        bio_en: 'Taiwu Ballads Troupe (TBT) was founded by Camake Valaule in Taiwu, Pingtung. Dedicated to preserving Paiwan polyphonic songs, TBT has collected nearly 100 ancient melodies and performed at WOMADelaide, WOMAD New Zealand, and on tour in the US, Europe, and Japan. In April 2026, TBT releases Kivaljuq – Songs in Full Bloom, their first album in 14 years.',
        facebook: 'https://www.facebook.com/TaiwuAncientBalladsTroupe',
        website: 'https://www.windmusiclabel.com/taiwuballadstroupe'
      }
    ],
    category:'sound', isPrimary:true, externalUrl:''
  },
  {
    num:'06', icon:'💃',
    img:'images/展演活動_翃舞.png',
    date:'2026-07-17', endDate:'2026-07-18',
    time:'7:30 p.m. (EST)',
    title:'翃舞製作《羽人》',
    title_en:'HUNG DANCE — BIRDY',
    subtitle:'當代舞蹈 · 自由從限制開始',
    subtitle_en:'Contemporary Dance · Eight performers, one vision.',
    location:'NYU Skirball Center, 紐約',
    location_full:'NYU Skirball Center, New York',
    desc:'「所有的自由飛翔，都是從限制開始的？」《羽人》以強烈而細膩的身體語言，描繪人在束縛之中仍渴望自由。作品大膽解構傳統戲曲元素：象徵權力的「翎子」化為意識的延伸，失去槍頭的「藤桿」則架起浮動的牢籠，揉合太極與當代舞蹈語彙，探索生命的韌性。2023年於法國亞維儂藝術節創下20場完售佳績。',
    desc_en:'"Is all flight born from limitation?" BIRDY, a striking work by LAI Hung-chung, explores the tension between freedom and constraint through a refined physical language. Drawing from traditional Peking opera, the Ling Zi (pheasant feathers) shift from symbols of power into extensions of consciousness. Rattan poles form fluid, cage-like structures. Blending Tai Chi with contemporary dance. Presented at the 2023 Festival Off Avignon with 20 sold-out performances.',
    long_desc: '「從動靜之中窺見萬物、萬變共存之道。」\n\n《羽人》以屢獲國際大獎的雙人版為雛形，發展成八人的全版作品。我們的一生中，都在不斷突破限制、找尋飛翔的方向。當遭遇困境時，是逃避、掙扎、逃離、抑或擺脫限制而驟然湧出能量？\n\n舞者頭上的翎子，在空間交錯、堆疊甚至纏繞，貌似人體脊椎的延伸，產生的動能及擺幅，如同人類面對內心狀態時的焦慮不安、堅定期盼。藤桿堅固且富有彈性的特性，在舞台上製造出如浮動的迷宮，舞者們突破框架而飛翔，如同在處處受限的生活夾縫中，創造出生命的空間與距離。在《羽人》中，舞蹈風格以具有太極元素的翃舞技巧為基礎，融合水袖甩動、手勢等傳統戲曲動作，創造出臺灣獨特舞蹈語彙。',
    long_desc_en: 'BIRDY, a captivating dance work by LAI Hung-chung, evolves from an award-winning duet into a full-length piece for eight dancers. It explores the interplay between freedom and limitation through a layered dialogue between personal experience and broader societal contexts.\n\nTraditional Peking opera elements are reimagined as central visual and conceptual devices. The Ling Zi (pheasant feathers) become extensions of consciousness. Rattan poles, derived from spears stripped of their tips, form shifting, cage-like structures across the stage. Grounded in Hung Dance\'s movement language, the choreography integrates Tai Chi–inspired principles with contemporary dance and traditional operatic gestures. Through this interplay, BIRDY invites audiences to reflect on how we coexist with limitation, how transformation emerges through tension, and how balance can be found within constant change.',
    youtubeId: 'qe-x8AYYEYU',
    ensemble: {
      name: '翃舞製作',
      name_en: 'HUNG DANCE',
      bio: '翃舞製作，來自臺灣的當代舞團。2017年由編舞家賴翃中成立，以「翃」字作為團名，翱翔之意。舞團以年度製作、國際共製及國際巡演為發展主軸，同時策劃「漂鳥舞蹈平台」，致力支持新銳編舞家創作發展。翃舞製作憑藉多部作品於國際舞壇嶄露頭角，包括《羽人》與《推拉》等作，在多項國際競賽中獲得肯定。足跡遍及五大洲，累積逾三百場演出。',
      bio_en: 'HUNG DANCE is a Taiwanese contemporary dance company founded in 2017 by Artistic Director and choreographer LAI Hung-chung. Inspired by the word "Hung (翃)", the company\'s name reflects its aspiration to soar. Focusing on annual productions, international collaboration, and tours, HUNG DANCE also organizes the Stray Birds Dance Platform to foster choreographers\' creativity. With over 300 performances, HUNG DANCE has toured extensively across five continents.',
      photo: 'images/hung dance/hung-dance-director.jpg',
      logo: 'images/hung dance/HUNG DANCE.png',
      website: 'https://www.hungdance.com/',
      facebook: 'https://www.facebook.com/HungDanceTaiwan',
      instagram: 'https://www.instagram.com/hungdancetaiwan'
    },
    gallery: [
      'images/hung dance/2_Hung Dance_羽人BIRDY_credit 劉人豪LIU,Ren-haur.JPEG',
      'images/hung dance/20_Hung Dance_羽人BIRDY_credit 劉人豪LIU,Ren-haur.JPEG',
      'images/hung dance/29_Hung Dance_羽人BIRDY_credit 劉人豪LIU,Ren-haur.JPEG',
      'images/hung dance/48_Hung Dance_羽人BIRDY_credit 劉人豪LIU,Ren-haur.JPEG',
      'images/hung dance/52_Hung Dance_羽人BIRDY_credit 劉人豪LIU,Ren-haur.JPEG',
      'images/hung dance/64_Hung Dance_羽人BIRDY_credit 劉人豪LIU,Ren-haur.JPEG',
      'images/hung dance/68_Hung Dance_羽人BIRDY_credit 劉人豪LIU,Ren-haur.JPEG',
      'images/hung dance/77_Hung Dance_羽人BIRDY_credit 劉人豪LIU,Ren-haur.JPEG',
      'images/hung dance/79_Hung Dance_羽人BIRDY_credit 劉人豪LIU,Ren-haur.JPEG',
      'images/hung dance/80_Hung Dance_羽人BIRDY_credit 劉人豪LIU,Ren-haur.JPEG',
      'images/hung dance/87_Hung Dance_羽人BIRDY_credit 劉人豪LIU,Ren-haur.JPEG',
      'images/hung dance/88_Hung Dance_羽人BIRDY_credit 劉人豪LIU,Ren-haur.JPEG',
      'images/hung dance/96_Hung Dance_羽人BIRDY_credit 劉人豪LIU,Ren-haur.JPEG',
      'images/hung dance/97_Hung Dance_羽人BIRDY_credit 劉人豪LIU,Ren-haur.JPEG',
      'images/hung dance/122_Hung Dance_羽人BIRDY_credit 劉人豪LIU,Ren-haur.JPEG',
      'images/hung dance/127_Hung Dance_羽人BIRDY_credit 劉人豪LIU,Ren-haur.JPEG',
      'images/hung dance/羽人BIRDY_credit 劉人豪LIU,Ren-haur.JPEG'
    ],
    category:'sound', isPrimary:true, externalUrl:''
  },
  {
    num:'07', icon:'🎵',
    img:'images/展演活動_taiwanese wave.png',
    date:'2026-08-16',
    time:'5:00 p.m. - 9:30 p.m. (EST)',
    title:'2026 紐約夏日舞台音樂節 臺灣之夜',
    title_en:'Taiwanese Waves 2026 @ SummerStage',
    subtitle:'9m88 · YELLOW · ØZI · Chance Emerson · Mong Tong',
    subtitle_en:'9m88 · YELLOW · ØZI · Chance Emerson · Mong Tong',
    location:'Rumsey Playfield, Central Park',
    location_full:'Rumsey Playfield, Central Park, New York City (SummerStage)',
    desc:'自 2016 年起舉辦的 Taiwanese Waves，是亞洲首個獲官方邀請登上紐約 Central Park SummerStage 的音樂計畫，也是每年夏天紐約客必訪的戶外演唱會之一。以三至四組風格與語言各異的音樂人同台演出為核心，持續把橫跨台語、原住民族語、華語等多元聲音帶上國際舞台，至今場場滿座，吸引來自紐約與外州的樂迷共襄盛舉。',
    desc_en:'Launched in 2016, Taiwanese Waves is the first music program from Asia to receive an official invitation to perform at New York\'s Central Park SummerStage, and has since become one of the city\'s must‑see free outdoor concerts each summer. Curated around three to four artists or groups each year, the program showcases Taiwan\'s rich musical diversity across languages and genres, drawing packed audiences from New York and beyond.',
    long_desc: '自 2016 年起舉辦的 Taiwanese Waves，是亞洲首個獲得官方邀請登上紐約 Central Park SummerStage 的音樂計畫，也是夏季紐約客必訪的戶外音樂活動之一。2016 年首度以「臺灣之夜 Taiwanese Waves」登場，即創下 SummerStage 單日觀眾人次新高，之後每一屆皆締造滿場紀錄，吸引許多外州樂迷專程前來中央公園參與。\n\n2016－2019 年，Taiwanese Waves 連續四屆舉辦，之後因 COVID-19 疫情，2020－2022 年全球多數現場演出被迫取消，計畫也暫停三年。2023 年以「Taiwanese Waves Returns」之名回歸實體舞台，2025 年更是第六度登上 SummerStage，不僅延續介紹台語與原住民族語創作的傳統，更首度加入舞蹈元素，讓節目形式更加多元。\n\n從首屆起，Taiwanese Waves 便以三至四組風格與語言各異的創作人共同演出的設計，展現台灣音樂的多元樣貌。歷屆曾登場的音樂人包括：2016 年的安溥、旺福、落日飛車；2017 年的滅火器、黃玠與黃小禎、桑布伊；2018 年的大象體操、生祥樂隊、蛋堡；2019 年由阿爆、Tizzy Bac、萬芳等四組女性代表壓軸全場；2023 年則有金曲最佳國語女歌手魏如萱（娃娃）、新世代樂團恐龍的皮與 DJ MR. SKIN 的「國語作業簿」派對。2025 年以「原民語 x 台語 x 國語」為策展概念，邀請鄭宜農、阿爆與那屋瓦少女隊，以及布拉瑞揚舞團同台演出。\n\n邁入第十年的 Taiwanese Waves，第七屆將焦點放在已有海外演出經驗、並具國際拓展潛力的音樂人，以 R&B 與靈魂樂為主軸，邀請來自台灣的新生代創作歌手 YELLOW 黃宣、9m88、ØZI——三位皆為金曲獎入圍常客，並多次與國際音樂人合作演出。同時也大力推廣深受海外樂迷喜愛的迷幻搖滾樂團 Mong Tong 夢東，以及新生代臺裔美籍創作者 Chance Emerson，邀請紐約觀眾在夏夜裡隨著音樂輕鬆搖擺，一起慶祝 Taiwanese Waves 的第一個十年。',
    long_desc_en: 'Launched in 2016, Taiwanese Waves is the first music program from Asia to receive an official invitation to perform at New York\'s Central Park SummerStage, and has since become one of the must‑see outdoor concerts for New Yorkers every summer. From its debut "Taiwanese Waves: Taiwan Night" in 2016, the event broke SummerStage\'s single‑day attendance record and has sold out every subsequent edition, drawing audiences from across New York and out of state.\n\nTaiwanese Waves was held annually from 2016 to 2019, but was forced to pause between 2020 and 2022 due to the COVID‑19 pandemic and the global shutdown of live performances. In 2023, it returned to the SummerStage under the banner "Taiwanese Waves Returns," and in 2025 the program appeared on the SummerStage for the sixth time. That year\'s edition not only continued to highlight music in Taiwanese and Indigenous languages, but also introduced dance for the first time, expanding the artistic scope of the show.\n\nFrom the very beginning, Taiwanese Waves has been curated around three to four artists or groups each year, deliberately showcasing different genres, languages, and creative voices from Taiwan. Past lineups have featured: Anpu, Wonfu, and Sunset Rollercoaster in 2016; Fire EX., Huang Jie & Huang Hsiao‑chun, and Sangpuy in 2017; Elephant Gym, Sheng‑xiang & Band, and Soft Lipa in 2018; and a powerful all‑female lineup in 2019 with ABAO, Tizzy Bac, and Wanfang. In 2023, the stage welcomed Golden Melody Award winner Waa Wei, rising band Dinosaur\'s Skin, and DJ MR. SKIN with his "Mandarin Workbook" party concept. In 2025, the curatorial theme "Indigenous Languages x Taiwanese x Mandarin" brought together Enno Cheng, ABAO with the Na Nuwas Girls, and Bulareyaung Dance Company.\n\nCelebrating its tenth year, the seventh edition of Taiwanese Waves shifts the focus toward artists with prior international touring experience and strong potential for global crossover. Centered on R&B and soul‑influenced sounds, the 2026 lineup presents three next‑generation Taiwanese singer‑songwriters—YELLOW Huang Hsuan, 9m88, and ØZI—who are all frequent nominees at the Golden Melody Awards and have extensive international collaboration experience. The program also highlights psychedelic rock band Mong Tong, beloved by overseas listeners, alongside Taiwanese‑American singer‑songwriter Chance Emerson. Together, they invite New York audiences to sway, dance, and celebrate the first decade of Taiwanese Waves under the summer night sky.',
    performersLabel: '演出陣容',
    performersLabel_en: 'Lineup',
    speakersLabel: '策展人',
    speakersLabel_en: 'Curator',
    speakers: [
      {
        name: '嚴敏 Mia',
        name_en: 'Mia Yen',
        role: '策展人',
        role_en: 'Curator',
        bio: '嚴敏 Mia 是長年深耕紐約與台北之間的音樂策展人與經紀人，為將台灣原創音樂帶上國際舞台的重要推手，被樂壇暱稱為「紐約媽媽」。2008 年赴紐約後，她從 Live House 實習、場館企劃到演出協調，多方投入現場音樂產業，累積豐富國際實務經驗；2016 年創辦「Taiwanese Waves」並首度促成台灣音樂人登上紐約 Central Park SummerStage，開啟台灣獨立音樂在紐約夏日音樂祭的里程碑。此外，她亦以經紀人身分長期與 9m88 等音樂人合作，透過巡演規劃、跨國媒合與品牌合作，持續搭建東西方音樂與文化交流的橋樑。',
        bio_en: 'Mia Yen is a New York– and Taipei‑based music curator and artist manager, widely regarded as a key advocate for bringing Taiwanese original music onto the international stage and affectionately known in the scene as "New York Mom." After moving to New York in 2008, she immersed herself in the live‑music ecosystem—from interning and programming at local venues to coordinating shows—gaining extensive hands‑on experience in the independent circuit. In 2016, she founded "Taiwanese Waves" and successfully brought Taiwanese artists to New York\'s Central Park SummerStage for the first time, marking a major milestone for Taiwan\'s indie music at one of the city\'s flagship summer festivals. Mia also manages artists such as 9m88, overseeing touring, international collaborations, and brand partnerships, and continues to build bridges between Asian and Western music communities through her curatorial and behind‑the‑scenes work.'
      }
    ],
    performers: [
      {
        instrument: 'R&B / Neo-Soul / Jazz',
        instrument_en: 'R&B / Neo-Soul / Jazz',
        name: '9m88',
        name_en: '9m88',
        bio: '出道至今，9m88 已發行三張正式專輯與兩張爵士 EP，並推出多首個人與合作單曲，音樂風格橫跨 R&B、Neo‑Soul、Jazz、Hip‑Hop 與 Pop，是少數同時活躍於戲劇、Podcast 主持、時尚與視覺藝術領域的獨立創作歌手。2019 年首張創作專輯《平庸之上 Beyond Mediocrity》入圍金曲獎最佳新人，並獲得金音獎最佳新人獎肯定；2023 年第三張專輯《Sent》更入圍金曲獎最佳華語女歌手獎，持續以獨立之姿在華語樂壇發光。她亦參與電影《女孩》、《大濛》、《雙囍》的演出，其中《女孩》入圍威尼斯影展競賽單元，《大濛》則獲金馬獎最佳劇情片，展現跨界表演能量。',
        bio_en: 'Since her debut, 9m88 has released three full‑length albums and two jazz EPs, along with numerous solo and collaborative singles that span R&B, neo‑soul, jazz, hip‑hop, and pop. A prolific independent artist, she is also active in film, podcast hosting, fashion, and visual art. Her 2019 debut album "Beyond Mediocrity" earned a Golden Melody Award nomination for Best New Artist and won the Golden Indie Music Awards\' Best New Artist, while her 2023 album "Sent" received a Golden Melody nomination for Best Mandarin Female Singer. On screen, she has starred in films such as "Girls," "Day Off," and "Double Happiness Limited," with "Girls" selected for competition at the Venice Film Festival and "Day Off" winning Best Narrative Feature at the Golden Horse Awards.',
        instagram: 'https://www.instagram.com/9m88'
      },
      {
        instrument: 'R&B / Pop',
        instrument_en: 'R&B / Pop',
        name: 'YELLOW 黃宣',
        name_en: 'YELLOW Huang Hsuan',
        bio: 'YELLOW 黃宣是歌手、音樂製作人、主持人與演員，14 歲便開始創作並在歌唱比賽中奪冠。2019 年以單曲作品獲得第 30 屆金曲獎最佳單曲製作人獎，2020 年推出專輯《浮世擊》，入圍金曲獎最佳華語男歌手與最佳編曲人等獎項，並替多位華語歌手擔任製作與編曲。他也跨足影視與主持領域，參與電影《他馬克老闆》、《愛情城事》與影集《正港分局》等演出，並曾主持金曲獎星光大道，以音樂與綜藝感兼具的形象受到矚目。',
        bio_en: 'YELLOW Huang Hsuan is a singer, producer, host, and actor who began writing music at 14 and soon won his first vocal competition. He released his debut EP in 2019 and went on to win the Golden Melody Award for Best Single Producer at the 30th Golden Melody Awards; his 2020 album "Floating World" earned nominations for Best Mandarin Male Singer and Best Arrangement while he continued to produce for various Mandarin pop artists. Beyond music, he has appeared in films such as "Boss Mark" and "Love in Taipei," the TV series "Zhen‑Gang Police Station," and has hosted red‑carpet events including the Golden Melody Awards, showcasing his versatility on stage and on screen.',
        instagram: 'https://www.instagram.com/y3loooooo'
      },
      {
        instrument: 'R&B / Hip-Hop',
        instrument_en: 'R&B / Hip-Hop',
        name: 'ØZI',
        name_en: 'ØZI',
        bio: 'ØZI 是台灣 R&B 創作男歌手、音樂製作人與 MV 導演，2018 年發行首張專輯《ØZI: The Album》，以此獲得第 30 屆金曲獎最佳新人獎，正式奠定其在華語 R&B 領域的重要位置。之後陸續推出第二張專輯《PEDESTAL》（2021）與第三張專輯《ADICA》（2023），並舉辦同名大型演唱會，持續拓展聲音與舞台企圖。最新專輯《SWIRL》邀集 Jay Park、Awich、JP The Wavy 等多位國際音樂人合作，展現其跨國製作與多元風格的企圖與實力。',
        bio_en: 'ØZI is a Taiwanese R&B singer‑songwriter, producer, and music video director. His 2018 debut "ØZI: The Album" won Best New Artist at the 30th Golden Melody Awards, cementing his status as a leading voice in Mandarin R&B. He followed up with his second album "PEDESTAL" in 2021 and third album "ADICA" in 2023, both accompanied by large‑scale live shows that pushed his performance and production to new heights. His latest project "SWIRL" features collaborations with international artists including Jay Park, Awich, and JP The Wavy, underscoring his ambition and reach on the global stage.',
        instagram: 'https://www.instagram.com/ozifp'
      },
      {
        instrument: 'Folk Rock',
        instrument_en: 'Folk Rock',
        name: 'Chance Emerson',
        name_en: 'Chance Emerson',
        bio: 'Chance Emerson 是一位台美混血的民謠搖滾創作歌手，目前定居美國，作品融合獨立民謠與搖滾元素，帶有細膩敘事與真摯情感。他曾為 Sting、Sam Barber、Shakey Graves 等音樂人擔任演唱會開場嘉賓，並登上 Lollapalooza、Austin City Limits、Newport Folk Festival 等美國知名音樂節舞台。最新專輯《Ginkgo》在各大串流平台累積超過三百萬次播放，持續以現場演出與創作拓展其北美與國際樂迷群。',
        bio_en: 'Chance Emerson is a Taiwanese‑American folk‑rock singer‑songwriter based in the United States, known for blending indie folk and rock with intimate, narrative‑driven songwriting. He has opened for artists such as Sting, Sam Barber, and Shakey Graves, and has performed at major U.S. festivals including Lollapalooza, Austin City Limits, and Newport Folk Festival. His latest album "Ginkgo" has surpassed three million streams across platforms, further expanding his growing audience in North America and beyond.',
        instagram: 'https://www.instagram.com/chance.s.emerson'
      },
      {
        instrument: '迷幻搖滾',
        instrument_en: 'Psychedelic Rock',
        name: 'Mong Tong 夢東',
        name_en: 'Mong Tong',
        bio: '夢東（Mong Tong）是來自台北的迷幻搖滾雙人組，由兄弟洪御與郡其組成，音樂深受台灣神祕主義、美學符號與民間信仰圖騰影響。兩人將靈異錄音、東方旋律與迷幻 Groove 融入音樂，形塑兼具復古與未來感的聲響風景；「夢東」一詞有多重含義，他們選擇以「夢之東方」做為貼近其音樂世界的註解。夢東曾舉辦美國巡迴、參與 SXSW 音樂節，並登上美國知名電台節目 KEXP 演出，以充滿視覺與聽覺層次的現場表演廣獲國際樂迷關注。',
        bio_en: 'Mong Tong is a psychedelic rock duo from Taipei formed by brothers Hom Yu and Jiun Chi, whose music draws heavily on Taiwanese mysticism, vintage superstition iconography, and East Asian sonic motifs. The two craft a sound that weaves field recordings, Eastern melodies, and hypnotic grooves into a surreal, cinematic universe—reflected in the name "Mong Tong," which they interpret as "Dreaming of the East." The duo has toured the United States, performed at SXSW, and appeared on the renowned live‑session platform KEXP, earning international attention for their immersive, multi‑layered performances.',
        instagram: 'https://www.instagram.com/mongtongband'
      }
    ],
    category:'sound', isPrimary:true, externalUrl:''
  },

  /* ── 身體與聲音 · 其他活動 ── */
  {
    num:'13', icon:'🎹',
    img:'images/展演活動_從內在聆聽到聲音：聽見台灣——嚴俊傑鋼琴講座暨示範演出.png',
    date:'2026-05-20',
    title:'從內在聆聽到聲音：聽見台灣——嚴俊傑鋼琴講座暨示範演出',
    title_en:'From Inner Hearing to Sound: Listening to Taiwan — An Artist Talk with Pianist Chun‑Chieh Yen',
    subtitle:'嚴俊傑 × 駐紐約臺北文化中心 · Feel the Keys.',
    subtitle_en:'Chun‑Chieh Yen × Taipei Cultural Center in New York · Feel the Keys.',
    location:'駐紐約臺北經濟文化辦事處一樓文化藝廊',
    location_full:'1 E 42nd Street, New York, NY 10017, USA',
    desc:'From Inner Hearing to Sound 邀請鋼琴家嚴俊傑，在紐約駐處文化藝廊分享他對「台灣聲音」的思考，並以現場鋼琴示範，帶領觀眾從內在聆聽到實際發聲，感受作品背後的情感與想像。活動由駐紐約臺北經濟文化辦事處、駐紐約臺北文化中心與 New Asia CMS 合作推出，為 NSO 國家交響樂團室內樂美國巡演在紐約的重要延伸節目之一。',
    desc_en:'"From Inner Hearing to Sound: Listening to Taiwan" features pianist Chun‑Chieh Yen in an intimate artist talk and mini‑recital at TECO‑NY\'s cultural gallery. Through conversation and live performance, Yen invites audiences to explore what "the sound of Taiwan" can mean today, as part of a special program co‑presented with the Taipei Economic and Cultural Office in New York, the Taipei Cultural Center, and New Asia CMS alongside the NSO chamber tour.',
    long_desc: 'From Inner Hearing to Sound 由新亞洲室內樂協會（New Asia CMS）與駐紐約臺北經濟文化辦事處、駐紐約臺北文化中心共同合作舉辦，邀請活躍於國際舞台的鋼琴家嚴俊傑，於紐約分享他對音樂詮釋與「台灣聲音」的觀察。\n\n嚴俊傑將從自身學習與演出經驗談起，回到樂譜與身體之間的關係，討論「內在聆聽」如何轉化為指尖落鍵的瞬間，並現場演奏多段鋼琴作品，讓觀眾在近距離的互動中，感受音樂在不同文化語境裡所承載的記憶與情感。\n\n本活動亦是 NSO 國家交響樂團室內樂「美洲巡演」在紐約的重要延伸節目之一，透過講座與示範演出，補充正式音樂會之外的思考脈絡，從個人創作與教育實踐出發，回應「台灣的聲音是什麼樣子？」這個提問。現場並安排 Q&A 與茶點時間，提供紐約在地聽眾與藝術家近距離交流的機會。',
    long_desc_en: '"From Inner Hearing to Sound: Listening to Taiwan — An Artist Talk with Pianist Chun‑Chieh Yen" is a special event co‑presented by New Asia CMS, the Taipei Economic and Cultural Office in New York (TECO‑NY), and the Taipei Cultural Center, held at TECO‑NY\'s cultural gallery. In this program, internationally active pianist Chun‑Chieh Yen reflects on his artistic journey and on what it means to speak of a distinct "sound of Taiwan," moving from score to body and from imagination to sound.\n\nCombining conversation with live performance, Yen will demonstrate how inner listening shapes his approach to touch, phrasing, and color at the keyboard, inviting audiences to experience how music can carry memory, identity, and cultural resonance. Presented in conjunction with the National Symphony Orchestra (NSO) of Taiwan\'s chamber tour in the United States, the event offers New York audiences a more intimate context for engaging with Taiwanese music and musicians, with time for Q&A and informal interaction over light refreshments.',
    performers: [
      {
        instrument: '鋼琴', instrument_en: 'Piano',
        name: '嚴俊傑', name_en: 'Chun‑Chieh Yen',
        bio: '嚴俊傑是活躍於國際舞台的台灣鋼琴家與教育者，曾師事柴可夫斯基大賽金牌得主 Vladimir Krainev，長年於歐洲深造與演出，現任國立臺灣師範大學音樂系專任教授。他以細膩的音色與深具故事感的詮釋著稱，演出足跡遍及歐洲、北美與亞洲多國，同時積極開設大師班與講座，關注如何透過教學與舞台實踐為年輕音樂家打造與世界接軌的平台。\n\n嚴俊傑創辦並擔任「國際大師鋼琴藝術節」藝術總監，匯聚海內外名師與樂壇新秀，透過密集大師課與音樂會，建構屬於亞洲的鋼琴教育與交流節點。近年亦多次與 NSO 國家交響樂團合作巡演，並在各類節目、Podcast 與媒體專訪中分享他對音樂、教育與跨文化交流的思考。',
        bio_en: 'Chun‑Chieh Yen is a Taiwanese pianist and educator whose career spans Europe, North America, and Asia. A former student of Vladimir Krainev, gold medalist of the International Tchaikovsky Competition, Yen is known for his refined sound, narrative approach to interpretation, and commitment to fostering the next generation of musicians. He currently serves as a professor at National Taiwan Normal University and frequently appears in concerts, masterclasses, and lecture‑recitals worldwide.\n\nYen is the founder and artistic director of the International Master Piano Festival, which brings together renowned artists and young talents for intensive masterclasses and performances, creating a key platform for piano education and exchange in Asia. In recent years, he has collaborated extensively with Taiwan\'s National Symphony Orchestra (NSO) on international tours and has shared his insights on music, teaching, and cross‑cultural dialogue through media interviews, podcasts, and public talks.',
        facebook: 'https://www.facebook.com/PianistChunChiehYEN/',
        instagram: 'https://www.instagram.com/ycchoping/'
      }
    ],
    category:'sound', isPrimary:true, externalUrl:''
  },

  /* ── 身體與聲音 · 主要活動（續） ── */
  {
    num:'01', icon:'🎭',
    img:'images/展演活動_臺美藝文大師系列講座.png',
    date:'2026-05-01',
    time:'6:30 p.m.–8:00 p.m. (EST)',
    title:'跨越邊界與肢體：林懷民與美國舞蹈節總監 Jodee Nimerichter 對談',
    title_en:'Across Borders, Across Bodies: Lin Hwai-min and Jodee Nimerichter in Conversation',
    subtitle:'林懷民 × Jodee Nimerichter · Feel the Wisdom.',
    subtitle_en:'Lin Hwai-min × Jodee Nimerichter · Feel the Wisdom.',
    location:'Asia Society, New York',
    location_full:'Asia Society, 725 Park Avenue, New York, NY 10021',
    desc:'「Across Borders, Across Bodies」邀請雲門舞集創辦人林懷民與美國舞蹈節（ADF）藝術總監 Jodee Nimerichter 對談，從跨國合作、舞蹈節策展到身體美學，回顧數十年來臺灣與美國在當代表演藝術上的交流歷程。活動由 Asia Society 與駐紐約臺北文化中心共同主辦，作為「TAIWAN POP｜紐文 35」系列首場節目，開啟一整年關於臺灣文化的國際對話。',
    desc_en:'"Across Borders, Across Bodies" brings together Lin Hwai-min, founder of Taiwan\'s Cloud Gate Dance Theatre, and Jodee Nimerichter, artistic director of the American Dance Festival (ADF), for a conversation on cross-border collaboration, festival curation, and the evolving aesthetics of the dancing body. Co-presented by Asia Society and the Taipei Cultural Center in New York, the event inaugurates the "TAIWAN POP | TCCNY 35" anniversary series, opening a year-long dialogue on Taiwanese culture on the international stage.',
    long_desc: '「Across Borders, Across Bodies: Lin Hwai-min and Jodee Nimerichter in Conversation」由 Asia Society 與駐紐約臺北文化中心共同主辦，特別邀請雲門舞集創辦人林懷民與美國舞蹈節（American Dance Festival, ADF）藝術總監 Jodee Nimerichter 進行一場深度對談，慶祝臺美之間長達數十年的舞蹈交流。\n\n自 1970 年代雲門舞集創立以來，林懷民以獨特的身體語彙，將太極、武術、書法與東亞哲思融入當代舞蹈，作品多次受邀於美國巡演，為國際觀眾開啟認識臺灣舞蹈的重要窗口；ADF 則長年邀請雲門及多位臺灣編舞家參與駐村與演出，讓雙方建立起深厚的專業與情感連結。\n\n在本場對談中，兩人將從個人記憶與機構經驗出發，分享過往合作幕後的故事，討論如何在不同文化背景與資源條件下推動創作、策展與巡演，也將談及身為藝術家與藝術節總監，在面對全球局勢與觀眾變化時，如何重新想像舞蹈在當代所能承載的意義。\n\n作為「TAIWAN POP｜紐文 35」系列的開幕節目，本活動不僅是對歷史的回顧，更是對下一階段臺美藝文交流的提問與前瞻。',
    long_desc_en: 'Co-presented by Asia Society and the Taipei Cultural Center in New York, "Across Borders, Across Bodies: Lin Hwai-min and Jodee Nimerichter in Conversation" celebrates decades of dance exchange between Taiwan and the United States. Lin Hwai-min, founder of Cloud Gate Dance Theatre of Taiwan, has reshaped contemporary dance by integrating tai chi, martial arts, calligraphy, and Asian philosophies into a distinctive movement language, while Cloud Gate\'s landmark tours across the U.S. have introduced international audiences to Taiwan\'s rich performing-arts landscape. Jodee Nimerichter, as artistic director of the American Dance Festival (ADF), has built enduring relationships with Cloud Gate and numerous Taiwanese choreographers through residencies, commissions, and presentations, weaving Taiwan into ADF\'s broader global network.\n\nIn this conversation, Lin and Nimerichter will revisit key moments in their collaborations, share behind-the-scenes stories from rehearsals, tours, and festival programming, and reflect on how artists and institutions navigate cultural, logistical, and political borders. They will also address the shifting role of the dancing body in contemporary society — how it can carry memory and history, embody place and identity, and create shared spaces of imagination for audiences around the world.\n\nAs the opening event of the "TAIWAN POP | TCCNY 35" anniversary series, the evening looks back at the past while charting possible futures for Taiwan–U.S. artistic exchange.',
    speakers: [
      {
        name: '林懷民', name_en: 'Lin Hwai-min',
        role: '雲門舞集創辦人', role_en: 'Founder, Cloud Gate Dance Theatre',
        bio: '林懷民是雲門舞集創辦人與前任藝術總監，被譽為引領亞洲當代舞蹈的重要先驅之一。自 1973 年創立雲門以來，他將太極、書法、美學與東亞哲思融入肢體語彙，創作《薪傳》、《九歌》、《水月》、《行草》與《松煙》等經典作品，帶領雲門巡演超過三十餘國，成為國際認識臺灣舞蹈的代表。退休後，他持續以寫作、講座與策畫等形式參與文化現場，關注藝術與社會的長期對話。',
        bio_en: 'Lin Hwai-min is the founder and former artistic director of Cloud Gate Dance Theatre of Taiwan and is widely regarded as a pioneering figure in contemporary dance in Asia. Since establishing Cloud Gate in 1973, he has created a distinctive movement language informed by tai chi, calligraphy, Asian aesthetics, and philosophy, in works such as "Legacy," "Nine Songs," "Moon Water," "Cursive," and "Pine Smoke," touring to more than thirty countries worldwide. After stepping down from Cloud Gate, Lin has continued to write, lecture, and engage in cultural initiatives, reflecting on the role of art in society.',
        website: 'https://www.cloudgate.org.tw/',
        facebook: 'https://www.facebook.com/cloudgate',
        instagram: 'https://www.instagram.com/cloudgate_official'
      },
      {
        name: 'Jodee Nimerichter', name_en: 'Jodee Nimerichter',
        role: '美國舞蹈節藝術總監', role_en: 'Artistic Director, American Dance Festival',
        bio: 'Jodee Nimerichter 為美國舞蹈節（American Dance Festival, ADF）藝術總監，長期致力於當代舞蹈的製作、國際合作與巡演推動。她在 ADF 主導多項新作委託與跨國交流計畫，與世界各地編舞家與舞團合作，亦多次與雲門舞集及臺灣編舞家合作演出與駐村，成為連結美國舞蹈界與亞洲的重要策展推手。',
        bio_en: 'Jodee Nimerichter is the artistic director of the American Dance Festival (ADF), where she oversees commissioning, presenting, and touring initiatives that support contemporary dance around the world. Under her leadership, ADF has developed numerous international collaborations and residencies, working with choreographers and companies from across Asia, Europe, and the Americas, including long-standing partnerships with Cloud Gate Dance Theatre and other Taiwanese artists.',
        website: 'https://www.americandancefestival.org',
        facebook: 'https://www.facebook.com/AmericanDanceFestival',
        instagram: 'https://www.instagram.com/americandancefestival'
      }
    ],
    category:'sound', isPrimary:true, externalUrl:'https://asiasociety.org/new-york/events/across-borders-across-bodies-lin-hwai-min-and-jodee-nimerichter-conversation'
  },
  {
    num:'04', icon:'🎬',
    img:'images/展演活動_世界之間：跨越疆界的臺灣電影.png',
    date:'2026-09-01', endDate:'2026-09-30',
    title:'世界之間：跨越疆界的臺灣電影',
    title_en:'Between Worlds: Taiwanese Cinema Across Borders',
    subtitle:'電影影展 · Feel the Frame.',
    subtitle_en:'Film Festival at Metrograph · Feel the Frame.',
    location:'Metrograph, 7 Ludlow St, New York',
    desc:'Metrograph 電影院自 2018 年起與駐紐約臺北文化中心深度合作，歷屆台灣影展場場爆滿。2026 年以「邊界、遷徙、歸屬」為主軸，策劃放映 10 部長片及 1 場短片選集，分三大策展方向：新浪潮起點、離散與遷徙、跨界合作，並邀請影人出席開幕。',
    desc_en:"Metrograph has partnered with the Taipei Cultural Center in New York since 2018, with every Taiwanese film program selling out. In 2026, Between Worlds presents 10 features and a short film program across three strands — New Wave Foundations, Diaspora Stories, and Cross-Border Collaborations — organized around the themes of borders, migration, and belonging.",
    long_desc: 'Metrograph 電影院創立於 2016 年，位於曼哈頓下東城，是紐約最具辨識度的藝術電影院之一，深受東亞電影愛好者支持。駐紐約臺北文化中心自 2018 年起與 Metrograph 建立合作關係，歷屆台灣主題影展場場爆滿。\n\n2026 年雙方再度合作，推出「世界之間：跨越疆界的臺灣電影」影展，以「邊界」、「遷徙」、「歸屬」為主軸，透過經典與當代作品並陳，描繪臺灣電影如何在跨文化語境中建構新的敘事語言。預計放映 10 部長片及 1 場短片選集，分三大策展方向：\n\n- 新浪潮起點：蔡明亮《青少年哪吒》、侯孝賢《尼羅河女兒》、楊德昌《一一》\n- 離散與遷徙：關錦鵬《三個女人的故事》、李安《喜宴》、黃熙《女兒的女兒》\n- 跨界合作：鄒時擎《左撇子女孩》、曾佩裕《藍色太陽宮》、舒淇《女孩》等。\n\n影展將邀請影人出席開幕，部分影片亦於 Metrograph At Home 線上平台同步放映。',
    long_desc_en: "Metrograph, founded in 2016 in Manhattan's Lower East Side, is one of New York's most distinguished independent cinemas and a gathering place for East Asian film enthusiasts. The Taipei Cultural Center in New York has partnered with Metrograph since 2018, presenting sold-out Taiwanese film programs.\n\nIn 2026, the two institutions reunite for Between Worlds: Taiwanese Cinema Across Borders — a program organized around the themes of borders, migration, and belonging, presenting classic and contemporary Taiwanese films alongside one another to trace how Taiwanese cinema has built new narrative languages across cultures.\nThe program includes 10 features and a short film program, across three curatorial strands:\n\n- New Wave Foundations: Tsai Ming-liang's Rebels of the Neon God, Hou Hsiao-hsien's Daughter of the Nile, Edward Yang's Yi Yi\n- Diaspora Stories: Stanley Kwan's Full Moon in New York, Ang Lee's The Wedding Banquet, Singing Chen's Daughter's Daughter\n- Cross-Border Collaborations: Works including Tsou Shih-ching's Left Handed Girl, Angie Chen's Blue Sun Palace, and Shu Qi's Girl.\nFilmmakers will be invited to attend the opening program; selected titles will also stream on Metrograph At Home.",
    category:'image', isPrimary:true, externalUrl:''
  },

  /* ── 影像與敘事 · 其他活動 ── */

  /* ── 街頭與生活 · 主要活動 ── */
  {
    num:'03', icon:'🎨',
    img:'images/展演活動_布希維克街頭藝術節 臺灣藝術家參展.png',
    date:'2026-05-28', endDate:'2026-05-30',
    time:'主活動 10:00–18:00',
    title:'2026 紐約布希維克街頭藝術計畫',
    title_en:'Taiwanese Artists @ 2026 Bushwick Collective Block Party',
    subtitle:'五位臺灣壁畫藝術家 · Feel the Wall.',
    subtitle_en:'Five Taiwanese Mural Artists · Feel the Wall.',
    location:'Bushwick, Brooklyn, New York',
    location_full:'Bushwick, Brooklyn, New York — Scott Ave & Troutman St / St. Nicholas Ave area',
    desc:'The Bushwick Collective Block Party 是紐約布魯克林 Bushwick 區一年一度的大型街頭藝術與音樂節慶，結合即席壁畫創作、嘻哈舞台、DJ、餐車與在地市集，將整個社區變成開放式戶外美術館。',
    desc_en:'The Bushwick Collective Block Party is an annual street art and music festival in Bushwick, Brooklyn, transforming the neighborhood into an open-air gallery with live mural painting, hip-hop performances, DJs, food trucks, and local vendors.',
    long_desc: '「The Bushwick Collective Block Party」是紐約布魯克林 Bushwick 區每年夏天最具代表性的街頭藝術慶典之一，由街頭藝術策展計畫 The Bushwick Collective 自 2012 年起發起並持續舉辦。活動結合大規模壁畫創作、現場嘻哈音樂演出、街頭塗鴉示範、美食餐車與在地市集，已從一場社區聚會，發展成匯聚國際藝術家、在地居民與全球遊客的重要城市文化事件。\n\n每年 Block Party 會封街舉行，集中在布魯克林 Bushwick 一帶（以 Troutman Street、St. Nicholas Avenue 一帶街區為核心），由知名街頭藝術家與新秀藝術家共同即席創作，讓整個社區成為開放式的戶外畫廊。活動現場設有舞台，由重量級嘻哈音樂人及 DJ 輪番演出，例如近年曾邀請 Rakim、Ice-T、Raekwon、Busta Rhymes 等經典傳奇，在街頭藝術之間打造充滿能量的音樂現場。\n\n作為免費、向所有年齡層開放的城市節慶，Bushwick Collective Block Party 不僅展現塗鴉、街頭藝術與嘻哈文化的創造力，也透過藝術與音樂連結不同背景的社群，成為紐約夏季啟動的重要文化節點。',
    long_desc_en: "Organized by The Bushwick Collective, the Bushwick Collective Block Party is an annual street art and music festival in Bushwick, Brooklyn that has grown from a neighborhood graffiti jam into a large-scale urban celebration bringing together international artists, hip-hop performers, and the local community. During the event, Scott Avenue and the surrounding streets are closed to traffic as more than forty artists from New York and around the world paint new murals, while a full lineup of hip-hop legends and DJs — including past appearances by Ice-T, Raekwon, Busta Rhymes, and many others — take over the main stage.\n\nFree and open to all ages, the Block Party now also features a VIP beer garden, satellite warehouse and rooftop parties, and collaborations with galleries and local businesses, turning Bushwick into an international hub for street art every early summer.",
    ensemble: {
      name: 'The Bushwick Collective',
      name_en: 'The Bushwick Collective',
      bio: 'The Bushwick Collective 是由紐約布魯克林在地策展人 Joe Ficalora 於 2012 年創立的街頭藝術計畫，基地位於 Bushwick 區 Troutman Street 與 St. Nicholas Avenue 一帶。為了以藝術回應社區歷史與自身家庭記憶，他開始與鄰里屋主協調釋出牆面，邀請來自紐約各地與世界各國的塗鴉與壁畫藝術家，共同把原本以工業倉儲為主的街區，轉化為持續更新的戶外公共藝術畫廊。\n\n十多年來，The Bushwick Collective 匯聚了 Buff Monster、Blek le Rat、Case Ma\'Claim、Pixel Pancho 等國際知名創作者，也讓 Bushwick 成為紐約最具代表性的街頭藝術地標之一。',
      bio_en: "The Bushwick Collective is a street art initiative founded in 2012 by Bushwick native Joe Ficalora, centered around Troutman Street and St. Nicholas Avenue in Brooklyn, New York. Motivated by a desire to honor his family's history and transform the industrial streets of his neighborhood, Ficalora began working with local building owners to offer their walls to graffiti and mural artists from New York and around the world, turning the area into a constantly evolving open-air gallery.\n\nOver the past decade, The Bushwick Collective has hosted acclaimed artists such as Buff Monster, Blek le Rat, Case Ma'Claim, and Pixel Pancho, establishing Bushwick as one of New York City's most recognizable street art destinations.",
      instagram: 'https://www.instagram.com/thebushwickcollective'
    },
    performers: [
      {
        instrument: '街頭藝術', instrument_en: 'Street Art',
        name: '黑雞先生 Mr. OGAY', name_en: 'Mr. OGAY',
        bio: '黑雞先生（本名周義勳）是台灣街頭藝術創作者，自詡為「充滿愛的憤怒青年」，自 2000 年接觸塗鴉至今，足跡遍及台灣各地，並曾受邀前往日本、中國與紐約等地進行創作。他的作品多以衣不蔽體的裸男形象為主角，將「醜陋」視為視覺語彙，透過誇張身體與犀利文字，對社會現況、體制與道德偽善做出直接而幽默的批判。',
        bio_en: 'Mr. Ogay (Chou I-Hsun) is a Taiwanese street artist who describes himself as an "angry youth full of love." Since discovering graffiti in 2000, he has painted extensively across Taiwan and has been invited to create works in Japan, China, New York, and beyond. Centered on semi-nude male figures, his art embraces "ugliness" as a visual language, using exaggerated bodies and sharp, humorous text to comment on current events, social systems, and moral hypocrisy.',
        instagram: 'https://www.instagram.com/mrogay'
      },
      {
        instrument: '塗鴉藝術', instrument_en: 'Graffiti',
        name: 'COLASA', name_en: 'COLASA',
        bio: 'Colasa（林軒毅）自小接受正規美術訓練，發展出以塗鴉為核心、融合東西方語彙的前衛視覺風格。他擅長以非傳統、帶有反叛精神的創作手法挑戰主流藝術架構，從抽象與具象之間遊走，持續實驗各種材質與媒介。其創作橫跨街頭藝術、時尚與行為藝術領域，近年受邀參與日本、韓國、香港、英國、新加坡、加拿大等地的展覽，並與 Audi、Audemars Piguet、Levi\'s、rag & bone、XBOX、華納電影等品牌合作。',
        bio_en: "Colasa (Lin Hsuan-Yi) is a Taiwanese artist formally trained in fine arts who has developed a distinctive, graffiti-driven visual language that fuses Eastern and Western influences. Known for his non-traditional and rebellious approach, he moves fluidly between abstraction and figuration, constantly experimenting with new materials and media. His practice spans street art, fashion, and performance, and he has been invited to exhibit and paint live in Japan, Korea, Hong Kong, China, the UK, Singapore, and Canada, while collaborating with brands such as Audi, Audemars Piguet, Levi's, rag & bone, XBOX, and Warner Bros.",
        instagram: 'https://www.instagram.com/colasa'
      },
      {
        instrument: '塗鴉 × 裝置', instrument_en: 'Graffiti & Installation',
        name: '傅星翰 VASTAR', name_en: 'VASTAR',
        bio: '傅星翰（VASTAR，1988 年生）是台灣塗鴉與立體裝置創作者。出身殯葬業禮儀師背景，2014 年起轉為全職創作，擅長運用噴漆罐、廢鐵、鋼筋、木材等回收媒材，結合寫實繪畫與雕塑語彙。以老美式漫畫風格著稱，曾受邀為周杰倫《功夫熊貓》MV 設計塗鴉場景、為《大嘻哈時代》打造舞台牆面，並於 2024 年成為首位獲選「TOKYO COMIC CON」官方主視覺的台灣藝術家。',
        bio_en: 'VASTAR (Fu Hsing-Han, born 1988) is a Taiwanese graffiti and 3D installation artist known for blending realistic painting with sculptural elements, using discarded spray cans, scrap metal, rebar, and wood. Drawing on vintage American comic aesthetics, he has been commissioned for Jay Chou\'s "Kung Fu Panda" theme song MV, stage design for "The Rappers" TV show, and a mural for Warner Bros.\' "Suicide Squad." In 2024, he became the first Taiwanese artist selected as official key visual artist for TOKYO COMIC CON.',
        instagram: 'https://www.instagram.com/vastar.art'
      },
      {
        instrument: '街頭插畫', instrument_en: 'Street Illustration',
        name: 'ALLO 愛羅', name_en: 'ALLO',
        bio: 'ALLO 愛羅畢業於國立臺灣師範大學特殊教育學系，曾任台北市國中特教班教師，現為 SPG 共享工作室創辦人。自學繪畫出身，長期致力於結合街頭藝術與插畫創作，擅長以俐落噴漆線條描繪女性肖像，透過深邃眼神與細膩表情，呈現溫柔卻堅定的精神力量。曾獲「墨路行者國際塗鴉大賽」冠軍與最佳人氣獎。',
        bio_en: 'ALLO is a Taiwanese street artist and illustrator with a background in special education, having taught at junior high schools in Taipei and founded SPG Shared Studio. A self-taught painter, he uses clean spray-paint lines to depict female portraits that radiate both gentleness and inner strength. He has received top honors at the "墨路行者 International Graffiti Competition" and created the main visual for "West Town Party 2nd" in collaboration with INFINITE.',
        instagram: 'https://www.instagram.com/allostrator'
      },
      {
        instrument: '壁畫藝術', instrument_en: 'Mural Art',
        name: 'Candy Kuo 郭于嫣', name_en: 'Candy Kuo',
        bio: 'Candy Kuo 郭于嫣出生於台北，成長於美國德州南部，現居奧斯汀，是一位台裔美籍視覺與壁畫藝術家，擅長融合東西方美學語彙。她以具象寫實手法描繪在地動植物與女性形象，關注自然、生態與女性身體之間的關係，並藉由公共藝術與社區壁畫，將城市牆面轉化為連結與認同的場域。自 2016 年起陸續在奧斯汀、邁阿密、紐約、長灘等城市創作壁畫並參與藝術節。',
        bio_en: 'Candy Kuo was born in Taipei and raised in South Texas, now based in Austin as a Taiwanese-American visual and mural artist whose work blends Eastern and Western aesthetics. Using a figurative and realist approach, she portrays local flora and fauna alongside powerful female figures, exploring the relationships between nature, femininity, and environment. Since 2016, she has created murals in Austin, Miami, New York, and Long Beach, collaborating with local and international brands.',
        instagram: 'https://www.instagram.com/itscandykuo'
      }
    ],
    category:'street', isPrimary:true, externalUrl:''
  },
  {
    num:'05', icon:'🌈',
    img:'images/展演活動_2026紐約同志遊行.png',
    date:'2026-06-28',
    time:'中午過後，持續約 4–6 小時',
    title:'2026 紐約同志遊行',
    title_en:'2026 New York City Pride March',
    subtitle:'Nymphia Wind × Tina Banana × Yolanda Mesula · 檳榔西施上紐約街頭',
    subtitle_en:'Nymphia Wind × Tina Banana × Yolanda Mesula · Betel Nut Beauty hits New York',
    location:'曼哈頓第五大道穿越格林威治村',
    location_full:'Manhattan – Fifth Avenue through Greenwich Village (route TBC)',
    desc:'2026紐約同志遊行，由《魯保羅變裝皇后秀》冠軍妮妃雅領軍，攜手臺灣皇后 Tina Banana、Yolanda Mesula 前進紐約，以「檳榔西施」為花車主題，融合臺灣街頭文化、霓虹視覺與變裝表演，轉化為鮮明而當代的遊行語言。作為臺灣獨特的文化符號，檳榔西施承載性別氣質、勞動身體與地方記憶。',
    desc_en:"For the 2026 New York City Pride March, Nymphia Wind, winner of RuPaul's Drag Race, will lead Taiwanese drag performers Tina Banana and Yolanda Mesula to New York with a float themed around the \"Betel Nut Beauty.\" Combining Taiwanese street culture, neon aesthetics, and drag performance, the project transforms this iconic figure into a bold and contemporary visual language for the parade.",
    long_desc: '紐約同志遊行每年都是全球最具規模與能見度的 Pride 活動之一。2026 年，由《魯保羅變裝皇后秀》冠軍妮妃雅擔任策展與領銜演出，攜手臺灣變裝皇后 Tina Banana 與 Yolanda Mesula，以「檳榔西施」為主題打造花車，將臺灣街頭文化與其獨特的身體美學帶進紐約街頭，轉化為一場鮮明而當代的文化表述。\n\n本次創作透過變裝藝術進行轉譯，將「檳榔西施」轉化為一種具有主體性、風格強度與當代表達的文化形象。藉由花車設計、霓虹裝置、電子音樂、服裝造型與身體展演，妮妃雅與兩位臺灣變裝皇后共同建構出一個來自臺灣街頭、並能與國際觀眾直接對話的視覺場景。在紐約同志遊行的場域中，這場花車創作展開一種以 queer 表演為核心的文化轉譯實踐。',
    long_desc_en: "The New York City Pride March is one of the largest and most visible Pride events in the world each year. In 2026, Nymphia Wind, winner of RuPaul's Drag Race, will serve as curator and lead performer, joined by Taiwanese drag performers Tina Banana and Yolanda Mesula. Together, they will create a float centered on the theme of the \"Betel Nut Beauty,\" bringing Taiwanese street culture and its distinctive embodied aesthetics into the streets of New York and transforming them into a vivid and contemporary cultural statement.\n\nThrough drag performance, this project reinterprets the Betel Nut Beauty as a cultural figure with agency, stylistic force, and contemporary expression. Through float design, neon installations, electronic music, costume, and performance, Nymphia Wind and the two Taiwanese drag performers together construct a visual scene rooted in Taiwanese street culture that speaks directly to international audiences. Within the context of the NYC Pride March, this float becomes a practice of cultural translation centered on queer performance.",
    speakersLabel: '策展人',
    speakersLabel_en: 'Curator',
    speakers: [
      {
        name: '妮妃雅 Nymphia Wind',
        name_en: 'Nymphia Wind',
        role: '策展人・領銜演出',
        role_en: 'Curator & Lead Performer',
        bio: '妮妃雅（Nymphia Wind）是來自台灣的國際變裝藝術家，榮獲美國《魯保羅變裝皇后秀》第16季冠軍。她以鮮明的香蕉美學、精緻工藝與跨文化舞台語彙聞名，透過變裝藝術將台灣文化轉化為具有國際辨識度的當代表述。近年受邀於台灣總統府、巴黎文化奧運、紐約百年劇院 Town Hall、荷蘭阿姆斯特丹運河遊行等重要場域演出，並獲哈佛大學外交政策倡議組織（HUFPI）首屆「年度改革者獎」。',
        bio_en: "Nymphia Wind is an internationally acclaimed drag artist from Taiwan and the winner of Season 16 of RuPaul's Drag Race. Known for her striking banana aesthetics, refined craftsmanship, and cross-cultural stage language, she transforms Taiwanese culture through drag into a contemporary expression with strong international recognition. She has been invited to perform at the Presidential Office of Taiwan, the Paris Cultural Olympics, Town Hall (New York), and the Amsterdam Canal Parade. She was honored with the inaugural Changemaker of the Year award by HUFPI.",
        facebook: 'https://www.facebook.com/66wind99/',
        instagram: 'https://www.instagram.com/66wind99/'
      }
    ],
    performers: [
      {
        instrument: '變裝表演',
        instrument_en: 'Drag Performance',
        name: 'Tina Banana',
        name_en: 'Tina Banana',
        bio: 'Tina Banana 是活躍於臺灣的變裝表演者，亦為妮妃雅創立的變裝家族 The House of Wind 核心成員。曾受邀於總統府演出，並參與巴黎文化奧運與世界壯年運動會閉幕典禮等國際場合。她的表演以強烈的視覺轉化為特色，透過服裝、造型與對嘴演出建立鮮明舞台語言。',
        bio_en: 'Tina Banana is a drag performer active in Taiwan and a core member of The House of Wind, the drag family founded by Nymphia Wind. She has performed at the Presidential Office of Taiwan and appeared in major international contexts such as the Paris Cultural Olympiad and the World Masters Games Closing Ceremony. Her work is distinguished by strong visual transformation, using costume, styling, and lip-sync performance to shape a vivid stage language.',
        instagram: 'https://www.instagram.com/tinabananananana/'
      },
      {
        instrument: '變裝表演',
        instrument_en: 'Drag Performance',
        name: 'Yolanda Mesula',
        name_en: 'Yolanda Mesula',
        bio: 'Yolanda Mesula 自2016年起活躍於臺灣變裝表演場域，擅長透過身體姿態、節奏感與造型轉換，形塑兼具張力與個人魅力的舞台形象。演出曾出現在 Netflix 紀錄影集《Midnight Asia》中。近年獲得泰國 Drag Arena 冠軍，並於次年受邀擔任評審。',
        bio_en: 'Yolanda Mesula has been active in Taiwan\'s drag performance scene since 2016. Her performance was featured in the Netflix documentary series Midnight Asia, offering international audiences a glimpse into Taiwan\'s nightlife culture. In recent years, she won Thailand\'s Drag Arena and returned the following year as an invited judge. Her work brings together the feel of Taiwan\'s streets, the atmosphere of the night, and contemporary queer aesthetics.',
        instagram: 'https://www.instagram.com/jiyao_aka_yolanda/'
      }
    ],
    category:'street', isPrimary:true, externalUrl:''
  }
];

/* ---------- Quiz Game Data ---------- */
const GAME_DATA = {
  'lin-hwai-min': {
    id:'lin-hwai-min', title:'臺美藝文大師講座', title_en:'Taiwan–US Arts Master Lecture',
    subtitle:'林懷民 Lin Hwai-min', subtitle_en:'Lin Hwai-min',
    emoji:'🎭', color:'#8B4513', colorLight:'#fdf3e7',
    venue:'Asia Society, Upper East Side',
    unlockMsg:'你已認識台灣最重要的舞蹈藝術家之一！',
    unlockMsg_en:'You\'ve met one of Taiwan\'s most important dance artists!',
    questions:[
      { q:'林懷民在 1973 年創立的舞團，以台灣哪個傳統意象命名？',
        q_en:'The dance company Lin Hwai-min founded in 1973 is named after which traditional image?',
        opts:['雲門','竹影','墨荷','山嵐'], ans:0,
        opts_en:['Cloud Gate','Bamboo Shadow','Ink Lotus','Mountain Mist'],
        fact:'「雲門」取自《呂氏春秋》，是中國最古老的舞蹈之一，象徵天地之氣。雲門舞集是台灣第一個現代舞職業舞團。',
        fact_en:'"Cloud Gate" comes from the ancient text Lüshi Chunqiu and is one of China\'s oldest dances, symbolizing the energy of heaven and earth. Cloud Gate Dance Theatre was Taiwan\'s first professional modern dance company.' },
      { q:'林懷民除了是舞蹈家，他還有另一個重要身份是？',
        q_en:'Besides being a choreographer, Lin Hwai-min is also known as a?',
        opts:['小說家','電影導演','音樂家','建築師'], ans:0,
        opts_en:['Novelist','Film Director','Musician','Architect'],
        fact:'林懷民 22 歲就出版小說《蟬》，融合文學與肢體的思維深刻影響了雲門作品的敘事性。',
        fact_en:'Lin Hwai-min published his novel "Cicada" at age 22. His literary sensibility deeply shaped the narrative quality of Cloud Gate\'s works.' },
      { q:'雲門舞集代表作《薪傳》，描述的是台灣哪段歷史？',
        q_en:'Cloud Gate\'s landmark piece Legacy depicts which chapter of Taiwanese history?',
        opts:['先民渡海來台','日治時期抗爭','二二八事件','台灣經濟奇蹟'], ans:0,
        opts_en:['Early settlers crossing the strait','Resistance during Japanese rule','The 228 Incident','Taiwan\'s economic miracle'],
        fact:'《薪傳》1978 年首演，描述漢人先民冒險橫越台灣海峽來台墾荒，在台美斷交當晚演出，感動無數台灣人。',
        fact_en:'Legacy premiered in 1978, depicting Han settlers crossing the Taiwan Strait. It was performed the night Taiwan–US diplomatic relations were severed, deeply moving audiences across the island.' },
      { q:'林懷民的舞作常融合哪些台灣在地元素？',
        q_en:'Which local Taiwanese elements does Lin Hwai-min frequently weave into his choreography?',
        opts:['書法、太極、傳統音樂','嘻哈、街舞','芭蕾、歌劇','說唱、相聲'], ans:0,
        opts_en:['Calligraphy, Tai Chi & folk music','Hip-hop & street dance','Ballet & opera','Rap & stand-up comedy'],
        fact:'雲門舞集深受東方美學影響，林懷民曾讓舞者練習書法、太極導引，將這些身體訓練融入現代舞語彙中。',
        fact_en:'Cloud Gate is deeply rooted in Eastern aesthetics. Lin had dancers practice calligraphy and Tai Chi, integrating these disciplines into a modern dance vocabulary.' },
      { q:'林懷民於 2019 年退休，他將雲門舞集交棒給哪位接班人？',
        q_en:'When Lin Hwai-min retired in 2019, who did he hand Cloud Gate over to?',
        opts:['鄭宗龍','布拉瑞揚','周書毅','黃翊'], ans:0,
        opts_en:['Cheng Tsung-lung','Bulareyaung','Chou Shu-yi','Huang Yi'],
        fact:'鄭宗龍來自台北萬華，作品融合台灣庶民生活與當代舞蹈美學，成為雲門第二代藝術總監。',
        fact_en:'Cheng Tsung-lung grew up in Taipei\'s Wanhua district. His work blends everyday Taiwanese life with contemporary dance aesthetics, making him Cloud Gate\'s second artistic director.' }
    ]
  },
  'nso-paiwan': {
    id:'nso-paiwan', title:'NSO × 泰武古謠', title_en:'NSO × Taimu Ancient Ballads',
    subtitle:'原住民音樂 Indigenous Music', subtitle_en:'Indigenous Music of Taiwan',
    emoji:'🎵', color:'#1a6b3c', colorLight:'#e8f5ee',
    venue:'Carnegie Hall, Midtown',
    unlockMsg:'你已走入台灣原住民族的音樂靈魂！',
    unlockMsg_en:'You\'ve entered the musical soul of Taiwan\'s indigenous peoples!',
    questions:[
      { q:'泰武古謠傳唱所在的「泰武鄉」位於台灣哪個縣市？',
        q_en:'Taimu Ancient Ballads originate from Taimu Township, which is located in which Taiwanese county?',
        opts:['屏東縣','台東縣','花蓮縣','南投縣'], ans:0,
        opts_en:['Pingtung County','Taitung County','Hualien County','Nantou County'],
        fact:'泰武鄉位於屏東縣，是排灣族重要的文化聚落。泰武國小的古謠合唱團曾登上國際舞台，將排灣族傳統吟唱帶給全世界。',
        fact_en:'Taimu Township is in Pingtung County, an important Paiwan cultural community. The Taimu Elementary School choir has performed internationally, bringing traditional Paiwan chanting to the world.' },
      { q:'台灣官方認定的原住民族共有幾族？',
        q_en:'How many officially recognized indigenous peoples are there in Taiwan?',
        opts:['16 族','9 族','12 族','20 族'], ans:0,
        opts_en:['16 peoples','9 peoples','12 peoples','20 peoples'],
        fact:'台灣目前官方認定 16 個原住民族，各族擁有不同語言、音樂、祭儀與服飾。原住民族人口約 57 萬，佔全台人口約 2.4%。',
        fact_en:'Taiwan officially recognizes 16 indigenous peoples, each with distinct languages, music, ceremonies, and dress. The indigenous population is around 570,000, roughly 2.4% of Taiwan\'s total.' },
      { q:'排灣族傳統音樂中，有一種重要的雙管樂器叫做？',
        q_en:'What is the important double-pipe traditional instrument in Paiwan music?',
        opts:['鼻笛','口琴','月琴','陶笛'], ans:0,
        opts_en:['Nose flute','Harmonica','Moon lute','Ocarina'],
        fact:'鼻笛（paringed）是排灣族男性以鼻子吹奏的傳統樂器，象徵愛情與思念，是極具代表性的原住民族樂器。',
        fact_en:'The nose flute (paringed) is played by Paiwan men through the nose, symbolizing love and longing. It is one of the most iconic traditional instruments among Taiwan\'s indigenous peoples.' },
      { q:'布農族哪首歌曾因旋律特殊而被送往太空？',
        q_en:'Which Bunun song was sent into space on a probe due to its unique melodic structure?',
        opts:['祈禱小米豐收歌','捕魚祭歌','年祭歡歌','打耳祭歌'], ans:0,
        opts_en:['Pasibutbut (Millet Harvest Prayer)','Fishing Festival Song','New Year Celebration Song','Ear-shooting Festival Song'],
        fact:'布農族「祈禱小米豐收歌」是全球罕見的天然複音合唱，被聯合國教科文組織關注，並於 1970 年代被送上太空探測器。',
        fact_en:'The Bunun Pasibutbut is a rare natural polyphonic chant recognized by UNESCO. In the 1970s it was placed aboard a space probe to represent humanity\'s musical heritage.' },
      { q:'NSO 國家交響樂團成立於哪一年？',
        q_en:'In which year was Taiwan\'s National Symphony Orchestra (NSO) founded?',
        opts:['1986 年','1970 年','2000 年','1995 年'], ans:0,
        opts_en:['1986','1970','2000','1995'],
        fact:'NSO 國家交響樂團成立於 1986 年，是台灣最重要的職業交響樂團，長期致力於跨文化合作與原創委託。',
        fact_en:'Founded in 1986, the NSO is Taiwan\'s most important professional symphony orchestra, dedicated to cross-cultural collaboration and original commissioned works.' }
    ]
  },
  'bushwick': {
    id:'bushwick', title:'布希維克街頭藝術節', title_en:'Bushwick Street Art Festival',
    subtitle:'台灣視覺藝術 Taiwan Visual Art', subtitle_en:'Taiwanese Visual Art',
    emoji:'🎨', color:'#e8472a', colorLight:'#fdeee9',
    venue:'Bushwick Collective, Brooklyn',
    unlockMsg:'你已發現台灣視覺藝術的當代能量！',
    unlockMsg_en:'You\'ve discovered the contemporary energy of Taiwanese visual art!',
    questions:[
      { q:'布希維克（Bushwick）位於紐約哪個行政區？',
        q_en:'Bushwick is located in which New York City borough?',
        opts:['布魯克林','曼哈頓','皇后區','布朗克斯'], ans:0,
        opts_en:['Brooklyn','Manhattan','Queens','The Bronx'],
        fact:'Bushwick 位於布魯克林東北部，過去是工業區，近年成為全球最重要的街頭藝術聚落之一，每年吸引世界各地藝術家在此創作壁畫。',
        fact_en:'Bushwick is in northeast Brooklyn. Once an industrial district, it is now one of the world\'s most important street art communities, drawing artists from around the globe to paint murals each year.' },
      { q:'台灣廟宇文化中，哪種視覺元素最常出現在當代台灣藝術中？',
        q_en:'Which visual elements from Taiwan\'s temple culture most frequently appear in contemporary Taiwanese art?',
        opts:['龍、虎、神明圖騰','梅花與竹子','101大樓剪影','台灣黑熊'], ans:0,
        opts_en:['Dragon, tiger & deity iconography','Plum blossoms & bamboo','Taipei 101 silhouette','Formosan black bear'],
        fact:'台灣廟宇是當代設計師最重要的靈感來源之一。龍柱、交趾陶、剪黏工藝等廟宇美學，被大量轉化為現代插畫、街頭藝術與品牌設計。',
        fact_en:'Taiwan\'s temples are a key inspiration for contemporary designers. Dragon pillars, jiaozhi ceramics, and traditional craftwork have been widely transformed into modern illustration, street art, and brand design.' },
      { q:'台灣哪個地方以「彩虹眷村」壁畫聞名，差點遭拆除卻因民眾連署保留？',
        q_en:'Which Taiwanese city is home to the Rainbow Village murals, nearly demolished but saved by a public petition?',
        opts:['台中','台北','高雄','嘉義'], ans:0,
        opts_en:['Taichung','Taipei','Kaohsiung','Chiayi'],
        fact:'台中彩虹眷村由老兵黃永阜一人獨力彩繪，原本面臨拆除，後因民眾連署而保留，是台灣最具代表性的庶民藝術故事。',
        fact_en:'Taichung\'s Rainbow Village was painted single-handedly by veteran Huang Yung-fu. Originally slated for demolition, it was preserved after a public petition—one of Taiwan\'s most beloved folk art stories.' },
      { q:'台灣近年最受國際關注的當代藝術博覽會是？',
        q_en:'Which contemporary art fair in Taiwan has attracted the most international attention in recent years?',
        opts:['Taipei Dangdai（台北當代）','故宮特展','總統府藝廊','ART TAIPEI'], ans:0,
        opts_en:['Taipei Dangdai','National Palace Museum Special Exhibition','Presidential Office Gallery','ART TAIPEI'],
        fact:'Taipei Dangdai 自 2019 年起每年舉辦，匯聚亞洲與全球頂尖畫廊，是台灣打入國際當代藝術市場的重要窗口。',
        fact_en:'Taipei Dangdai, held annually since 2019, brings together leading galleries from Asia and around the world, and is Taiwan\'s key gateway into the international contemporary art market.' },
      { q:'「眷村文化」孕育了大量台灣藝術家，眷村最初是為安置哪些人而建立？',
        q_en:'Juancun (military dependents\' villages) produced many Taiwanese artists. Who were they originally built to house?',
        opts:['1949年隨國民政府來台的軍人及家屬','日治時期留台日本人','原住民族遷移安置','越戰難民'], ans:0,
        opts_en:['Soldiers & families who came with the KMT government in 1949','Japanese residents remaining after WWII','Relocated indigenous peoples','Vietnam War refugees'],
        fact:'眷村孕育了侯孝賢、朱天文等大批文藝人才。眷村美學融合中國各省習俗與台灣在地文化，形成獨特的混血風格。',
        fact_en:'Juancun produced a wealth of artistic talent including Hou Hsiao-hsien and Chu T\'ien-wen. Juancun aesthetics blend customs from various Chinese provinces with Taiwanese local culture, creating a unique hybrid style.' }
    ]
  },
  'film': {
    id:'film', title:'臺灣主題影展', title_en:'Taiwan Film Festival',
    subtitle:'台灣電影 Taiwan Cinema', subtitle_en:'Taiwan Cinema',
    emoji:'🎬', color:'#1a3a6b', colorLight:'#e8edf5',
    venue:'Metrograph, Lower East Side',
    unlockMsg:'你已進入台灣電影的黃金世界！',
    unlockMsg_en:'You\'ve entered the golden world of Taiwanese cinema!',
    questions:[
      { q:'台灣導演李安以哪部電影首次獲得奧斯卡最佳導演獎？',
        q_en:'With which film did Taiwanese director Ang Lee win his first Academy Award for Best Director?',
        opts:['斷背山','臥虎藏龍','少年Pi的奇幻漂流','色，戒'], ans:0,
        opts_en:['Brokeback Mountain','Crouching Tiger, Hidden Dragon','Life of Pi','Lust, Caution'],
        fact:'李安以《斷背山》（2005）獲得奧斯卡最佳導演獎，是首位獲此殊榮的亞裔導演，被視為全球最具影響力的華裔導演。',
        fact_en:'Ang Lee won the Oscar for Best Director with Brokeback Mountain (2005), becoming the first Asian director to receive this honor. He is widely regarded as the most influential Chinese-language filmmaker in the world.' },
      { q:'台灣「新電影運動」約發生在哪個年代？',
        q_en:'The Taiwan New Cinema movement took place in approximately which decade?',
        opts:['1980 年代','1960 年代','1970 年代','1990 年代'], ans:0,
        opts_en:['1980s','1960s','1970s','1990s'],
        fact:'1980 年代，侯孝賢、楊德昌等導演發起台灣新電影運動，以寫實風格記錄台灣社會，讓台灣電影首度在坎城、柏林、威尼斯等影展發光。',
        fact_en:'In the 1980s, directors Hou Hsiao-hsien and Edward Yang launched the Taiwan New Cinema movement, using realist storytelling to document Taiwanese society and win acclaim at Cannes, Berlin, and Venice.' },
      { q:'侯孝賢《悲情城市》獲得威尼斯金獅獎，描述的是台灣哪個歷史事件？',
        q_en:'Hou Hsiao-hsien\'s City of Sadness won the Venice Golden Lion. Which historical event does the film depict?',
        opts:['二二八事件','台灣光復','戒嚴解除','台美斷交'], ans:0,
        opts_en:['The 228 Incident','Retrocession of Taiwan','Lifting of Martial Law','Severance of Taiwan–US ties'],
        fact:'《悲情城市》（1989）以九份為背景，描述二二八事件後台灣人的創傷，是台灣第一部正面觸及此事件的電影。',
        fact_en:'City of Sadness (1989), set in Jiufen, portrays the trauma following the 228 Incident. It was the first Taiwanese film to directly confront this event and won the Golden Lion at Venice.' },
      { q:'宮崎駿《神隱少女》的靈感場景，據說來自台灣哪個地方？',
        q_en:'Which Taiwanese location is said to have inspired the setting of Hayao Miyazaki\'s Spirited Away?',
        opts:['九份老街','阿里山','淡水','台南安平'], ans:0,
        opts_en:['Jiufen Old Street','Alishan','Tamsui','Anping, Tainan'],
        fact:'九份的金礦小鎮風貌、山城燈籠與茶樓意象，常被認為是《神隱少女》油屋場景的靈感來源之一，讓九份成為全球觀光客必訪之地。',
        fact_en:'Jiufen\'s mountain town atmosphere, glowing lanterns, and teahouses are widely believed to have inspired the bathhouse scenes in Spirited Away, making it a must-visit destination for global tourists.' },
      { q:'台灣被稱為「台灣奧斯卡」的電影最高榮譽是？',
        q_en:'Which film award is known as the "Taiwanese Oscars"?',
        opts:['金馬獎','金鐘獎','金曲獎','金穗獎'], ans:0,
        opts_en:['Golden Horse Awards','Golden Bell Awards','Golden Melody Awards','Golden Harvest Awards'],
        fact:'金馬獎創立於 1962 年，是華語電影圈歷史最悠久、最具公信力的電影獎項，與金鐘、金曲並稱台灣三金。',
        fact_en:'The Golden Horse Awards, founded in 1962, are the oldest and most prestigious film awards in the Chinese-language world, known alongside the Golden Bell and Golden Melody as Taiwan\'s "Three Golds."' }
    ]
  },
  'pride': {
    id:'pride', title:'紐約同志大遊行', title_en:'NYC Pride March',
    subtitle:'台灣 LGBTQ+ 文化', subtitle_en:'Taiwan LGBTQ+ Culture',
    emoji:'🏳️‍🌈', color:'#9b30d9', colorLight:'#f3e8fd',
    venue:'5th Avenue, Manhattan',
    unlockMsg:'你已了解台灣在平權路上的驕傲！',
    unlockMsg_en:'You\'ve learned about Taiwan\'s proud journey toward equality!',
    questions:[
      { q:'台灣在哪一年成為亞洲第一個同性婚姻合法化的國家？',
        q_en:'In which year did Taiwan become the first country in Asia to legalize same-sex marriage?',
        opts:['2019 年','2017 年','2021 年','2015 年'], ans:0,
        opts_en:['2019','2017','2021','2015'],
        fact:'2019 年 5 月 24 日，台灣正式成為亞洲首個同性婚姻合法化的國家，全球排名第 27 個，引發全亞洲廣泛關注。',
        fact_en:'On May 24, 2019, Taiwan officially became the first country in Asia—and the 27th worldwide—to legalize same-sex marriage, drawing widespread attention across the continent.' },
      { q:'台灣同志遊行每年在哪個城市舉行，是亞洲規模最大的？',
        q_en:'In which city is Taiwan\'s annual Pride Parade held, the largest in Asia?',
        opts:['台北','台中','高雄','台南'], ans:0,
        opts_en:['Taipei','Taichung','Kaohsiung','Tainan'],
        fact:'台北同志遊行自 2003 年起每年舉辦，近年參與人數突破 20 萬人，是亞洲規模最大的同志驕傲遊行。',
        fact_en:'The Taipei Pride Parade has been held annually since 2003. In recent years, attendance has surpassed 200,000 people, making it the largest Pride event in Asia.' },
      { q:'台灣同婚合法化的關鍵判決來自哪個機構？',
        q_en:'Which body issued the pivotal ruling that led to the legalization of same-sex marriage in Taiwan?',
        opts:['司法院大法官','立法院','行政院','總統府'], ans:0,
        opts_en:['Council of Grand Justices','Legislative Yuan','Executive Yuan','Presidential Office'],
        fact:'2017 年司法院大法官做出釋字第 748 號解釋，認定民法不允許同婚違憲，要求立法機關兩年內完成修法，開啟合法化歷程。',
        fact_en:'In 2017, the Council of Grand Justices issued Interpretation No. 748, ruling that the Civil Code\'s prohibition of same-sex marriage was unconstitutional and requiring the legislature to amend the law within two years.' },
      { q:'台灣最具代表性的 LGBTQ+ 友善商圈位於台北哪裡？',
        q_en:'Where in Taipei is Taiwan\'s most iconic LGBTQ+-friendly neighborhood?',
        opts:['西門町','信義區','天母','北投'], ans:0,
        opts_en:['Ximending','Xinyi District','Tianmu','Beitou'],
        fact:'西門町是台灣最具代表性的 LGBTQ+ 友善商圈，被稱為「台灣的 Chelsea」，彩虹旗飄揚的咖啡廳與友善商店密集。',
        fact_en:'Ximending is Taiwan\'s most iconic LGBTQ+-friendly district, often called "Taiwan\'s Chelsea," with rainbow flags flying from cafés and welcoming shops throughout.' },
      { q:'哪位台灣導演以電影三部曲記錄台灣 LGBTQ+ 故事享譽國際？',
        q_en:'Which Taiwanese director gained international acclaim for a film trilogy documenting LGBTQ+ stories in Taiwan?',
        opts:['周美玲','李安','侯孝賢','魏德聖'], ans:0,
        opts_en:['Zero Chou','Ang Lee','Hou Hsiao-hsien','Wei Te-sheng'],
        fact:'周美玲導演的「同志三部曲」以細膩筆觸描繪台灣 LGBTQ+ 生命經驗，在國際影展廣受好評。',
        fact_en:'Director Zero Chou\'s "Queer Trilogy" portrays LGBTQ+ life in Taiwan with sensitivity and depth, winning broad acclaim at international film festivals.' }
    ]
  },
  'horse': {
    id:'horse', title:'翃舞製作', title_en:'H·Art·Ch Dance Company',
    subtitle:'台灣當代舞蹈 Contemporary Dance', subtitle_en:'Taiwanese Contemporary Dance',
    emoji:'💃', color:'#c47a00', colorLight:'#fdf4e0',
    venue:'Skirball Cultural Center, Upper West Side',
    unlockMsg:'你已感受台灣當代舞蹈的力與美！',
    unlockMsg_en:'You\'ve felt the power and beauty of Taiwanese contemporary dance!',
    questions:[
      { q:'台灣當代舞蹈最常從哪些台灣本土元素汲取靈感？',
        q_en:'Which local Taiwanese elements most frequently inspire contemporary Taiwanese dance?',
        opts:['廟會儀式與原住民族肢體','古典芭蕾技巧','日本武道','韓國流行舞蹈'], ans:0,
        opts_en:['Temple rituals & indigenous movement','Classical ballet technique','Japanese martial arts','Korean pop dance'],
        fact:'台灣當代舞蹈創作者常向廟會陣頭、牽亡魂儀式、原住民族歌舞尋找靈感，以當代技法重新詮釋，形成台灣獨特的舞蹈語彙。',
        fact_en:'Taiwanese contemporary dance choreographers draw inspiration from temple processions, spirit-guiding ceremonies, and indigenous songs and dances, reinterpreting them through contemporary techniques to form a uniquely Taiwanese movement language.' },
      { q:'台灣哪位舞蹈家以「與機器人共舞」聞名全球？',
        q_en:'Which Taiwanese dancer became world-famous for "dancing with a robot"?',
        opts:['黃翊','布拉瑞揚','鄭宗龍','林懷民'], ans:0,
        opts_en:['Huang Yi','Bulareyaung','Cheng Tsung-lung','Lin Hwai-min'],
        fact:'黃翊的代表作《黃翊與庫卡》讓舞者與工業機器人 KUKA 共舞，探討人與科技的關係，在全球 15+ 國家巡演。',
        fact_en:'Huang Yi\'s signature work HUANG YI & KUKA features a dancer performing alongside industrial robot KUKA, exploring the relationship between humans and technology. It has toured in over 15 countries.' },
      { q:'以原住民族身份融合當代舞蹈的布拉瑞揚，屬於哪個族群？',
        q_en:'Bulareyaung, who integrates his indigenous heritage into contemporary dance, belongs to which ethnic group?',
        opts:['排灣族','阿美族','卑南族','泰雅族'], ans:0,
        opts_en:['Paiwan','Amis','Puyuma','Atayal'],
        fact:'布拉瑞揚·帕格勒法為排灣族人，曾為雲門舞集舞者，2015 年回故鄉台東成立舞團，作品融合排灣族文化與當代舞蹈。',
        fact_en:'Bulareyaung Pagarlava is Paiwan. A former Cloud Gate dancer, he returned to his hometown in Taitung in 2015 to found his own company, blending Paiwan culture with contemporary dance.' },
      { q:'台灣最重要的表演藝術機構「兩廳院」的正式名稱是？',
        q_en:'What is the official name of Taiwan\'s most important performing arts institution, known as "Liangting Yuan"?',
        opts:['國立中正文化中心','國立台灣藝術大學','台北市文化局','文化部'], ans:0,
        opts_en:['National Chiang Kai-shek Cultural Center','National Taiwan University of Arts','Taipei City Cultural Affairs Bureau','Ministry of Culture'],
        fact:'兩廳院（國立中正文化中心）旗下的國家音樂廳與國家戲劇院，是台灣表演藝術的最高殿堂。',
        fact_en:'The National Chiang Kai-shek Cultural Center—home to the National Concert Hall and National Theater—is the pinnacle of performing arts in Taiwan.' },
      { q:'「翃」這個字的意思最接近？',
        q_en:'The character 「翃」 most closely means?',
        opts:['鳥振翅飛翔','大地寬廣','水波流動','光芒四射'], ans:0,
        opts_en:['A bird spreading its wings in flight','Vast and wide-open land','Water flowing in ripples','Light radiating in all directions'],
        fact:'「翃」意指鳥飛翔的樣子，象徵舞者以身體在空間中飛翔探索的意志。翃舞製作成立於 2011 年，以跨域創作見長。',
        fact_en:'「翃」 depicts a bird in full flight, symbolizing a dancer\'s will to soar and explore space with their body. H·Art·Ch was founded in 2011 and is known for interdisciplinary creation.' }
    ]
  },
  'summerstage': {
    id:'summerstage', title:'SummerStage: Taiwanese Waves', title_en:'SummerStage: Taiwanese Waves',
    subtitle:'台灣之夜 Taiwan Night', subtitle_en:'A Night of Taiwan',
    emoji:'🌙', color:'#0d6b8c', colorLight:'#e0f2f8',
    venue:'Central Park SummerStage, Rumsey Playfield',
    unlockMsg:'你已體驗一夜台灣的完整魅力！',
    unlockMsg_en:'You\'ve experienced the full magic of a Taiwanese night!',
    questions:[
      { q:'台灣最具代表性的飲料「珍珠奶茶」發源於哪個城市？',
        q_en:'Which city is the birthplace of bubble tea (boba), Taiwan\'s most iconic drink?',
        opts:['台中','台北','台南','高雄'], ans:0,
        opts_en:['Taichung','Taipei','Tainan','Kaohsiung'],
        fact:'珍珠奶茶（Bubble Tea）1980 年代起源於台中，如今全球市場規模已超過 30 億美元，是台灣對世界飲食文化最大的貢獻之一。',
        fact_en:'Bubble tea originated in Taichung in the 1980s. Today it is a global industry worth over $3 billion, representing Taiwan\'s biggest contribution to world food culture.' },
      { q:'Central Park SummerStage 提供什麼樣的演出？',
        q_en:'What kind of performances does Central Park SummerStage offer?',
        opts:['免費戶外音樂表演','付費室內音樂廳','電影首映','藝術拍賣'], ans:0,
        opts_en:['Free outdoor music performances','Ticketed indoor concert hall','Film premieres','Art auctions'],
        fact:'Central Park SummerStage 自 1986 年起每年夏季舉辦免費戶外演出，是紐約最重要的多元文化音樂平台。',
        fact_en:'Central Park SummerStage has hosted free outdoor performances every summer since 1986, making it New York\'s most important multicultural music platform.' },
      { q:'台灣「辦桌文化」是指什麼？',
        q_en:'What does the Taiwanese tradition of "ban-do" (辦桌) refer to?',
        opts:['戶外大型宴席文化','便當盒飯文化','夜市攤販文化','早餐店文化'], ans:0,
        opts_en:['Outdoor communal banquet culture','Bento box lunch culture','Night market stall culture','Breakfast shop culture'],
        fact:'「辦桌」是台灣傳統的戶外宴席文化，在喜慶、廟會等場合，由總鋪師在路邊搭棚大宴賓客，是台灣最具凝聚力的庶民飲食儀式。',
        fact_en:'"Ban-do" is Taiwan\'s traditional outdoor banquet culture. For celebrations and temple festivals, a master chef sets up a large street banquet—one of Taiwan\'s most community-bonding culinary rituals.' },
      { q:'以下哪位音樂人被稱為「華語流行音樂天王」，來自台灣？',
        q_en:'Which Taiwanese musician is known as the "King of Mandopop"?',
        opts:['周杰倫（Jay Chou）','BTS 防彈少年團','張學友','劉德華'], ans:0,
        opts_en:['Jay Chou (周杰倫)','BTS','Jacky Cheung (張學友)','Andy Lau (劉德華)'],
        fact:'周杰倫自 2000 年代起稱霸全球華語市場，以融合中西音樂元素的創作風格著稱，至今仍是全球最具影響力的華語藝人之一。',
        fact_en:'Jay Chou has dominated the global Mandopop market since the 2000s, celebrated for blending Eastern and Western musical styles. He remains one of the most influential Chinese-language artists in the world.' },
      { q:'台灣夜市文化中，「雞排」是哪種料理方式的代表？',
        q_en:'In Taiwan\'s night market culture, what is "ji pai" (chicken steak) famous for?',
        opts:['炸雞胸肉排，比臉大','烤雞腿','滷雞翅','蒸雞肉'], ans:0,
        opts_en:['A fried chicken breast bigger than your face','Grilled chicken leg','Braised chicken wings','Steamed chicken'],
        fact:'台灣大雞排以巨大尺寸（比臉還大）、酥脆外皮聞名，是夜市最具代表性的食物之一，也是外國旅客必嚐的小吃體驗。',
        fact_en:'Taiwan\'s giant fried chicken steak is famous for its enormous size—bigger than your face—and its crispy coating. It is one of the most iconic night market foods and a must-try for foreign visitors.' }
    ]
  }
};
