'use strict';

/* ---------- Events Data ---------- */
/* category: 'sound' | 'image' | 'street'  isPrimary: true = 主要活動 / false = 其他活動 */
const EVENTS = [

  /* ── 身體與聲音 · 主要活動 ── */
  {
    num:'02', icon:'🎼',
    date:'2026-05-19',
    title:'NSO《來自臺灣》美國巡演',
    title_en:'From Formosa: Taiwan Philharmonic Chamber Ensemble 2026 US Tour',
    subtitle:'交響樂 × 排灣族古謠 · Feel the Roots.',
    subtitle_en:'Symphony Orchestra × Paiwan Ancient Ballads · Feel the Roots.',
    location:'Merkin Concert Hall, Kaufman Music Center, New York',
    desc:'2026 年「美國臺灣傳統週」，國家交響樂團肩負文化外交使命赴美演出，由首席小提琴家鄧皓敦領銜，攜手排灣族古謠演唱團體「TBT 泰武古謠傳唱」同台，讓山上的聲音與音樂廳的弦樂交會在同一個晚上。演出涵蓋蕭泰然《原住民組曲》及陳可嘉受委託的世界首演新作。',
    desc_en:"Celebrating Taiwanese American Heritage Week, the Taiwan Philharmonic embarks on a cultural diplomacy tour to the United States. Led by Concertmaster Hao-Tun Teng, the ensemble is joined by the Taiwu Ballads Troupe (TBT) — bringing the voices of the mountain into the same evening as the concert hall's strings. The program includes Tyzen Hsiao's Aboriginal Suite and the world premiere of a new work by Ke-Chia Chen.",
    category:'sound', isPrimary:true, externalUrl:'',
  },
  {
    num:'06', icon:'💃',
    date:'2026-07-17', endDate:'2026-07-18',
    title:'翃舞製作《羽人》BIRDY',
    title_en:'HORSE Dance Theatre: BIRDY',
    subtitle:'當代舞蹈 · Feel the Move.',
    subtitle_en:'Contemporary Dance Performance · Feel the Move.',
    location:'Skirball Cultural Center, New York',
    desc:'《羽人》以強烈而細膩的身體語言，描繪人在束縛之中仍渴望自由。編舞家賴翃中大膽解構傳統戲曲元素：象徵權力的「翎子」化為意識的延伸，失去槍頭的「藤桿」則架起浮動的牢籠，作品揉合太極與當代舞蹈語彙。2023 年於法國外亞維儂藝術節 20 場演出完售。',
    desc_en:'BIRDY explores the tension between freedom and constraint through a refined physical language. Choreographer LAI Hung-chung deconstructs traditional Peking opera — pheasant feathers become extensions of consciousness; rattan poles form fluid, cage-like structures. Blending Tai Chi with contemporary dance, the work resonated at the 2023 Festival Off Avignon with 20 sold-out performances.',
    category:'sound', isPrimary:true, externalUrl:'',
  },
  {
    num:'07', icon:'🎵',
    date:'2026-08-16',
    title:'Taiwanese Waves @ SummerStage',
    title_en:'Taiwanese Waves @ SummerStage',
    subtitle:'9m88 / YELLOW / ØZI / Mong Tong · Feel the Wave.',
    subtitle_en:'9m88 · YELLOW · ØZI · Mong Tong · Feel the Wave.',
    location:'Rumsey Playfield, Central Park, New York',
    desc:'Taiwanese Waves 自 2016 年起每年在紐約 SummerStage 舉辦，是近 40 年歷史中第一個以亞洲音樂為核心策展理念取得官方邀請的節目。2026 年第七屆演出陣容：9m88、YELLOW 黃宣、ØZI、Mong Tong 夢東，由 Chinatown Records 華埠錄音擔任音樂策展協力。現場設臺灣美食攤位，免費入場。',
    desc_en:"Taiwanese Waves has taken place annually at SummerStage since 2016 — the first program in its nearly 40-year history officially invited based on a curatorial vision centered on Asian music. The 2026 seventh edition features 9m88, YELLOW, ØZI, and Mong Tong, with curation support from Chinatown Records. Taiwanese food vendors from 886 and Wen Wen on-site. Free admission.",
    category:'sound', isPrimary:true, externalUrl:'',
  },

  /* ── 身體與聲音 · 其他活動 ── */
  {
    num:'08', icon:'🥁',
    date:'2026-08-12', endDate:'2026-08-14',
    title:'砲臺舞蹈節',
    title_en:'Fort Dance Festival',
    subtitle:'麥藍堤亞舞團',
    subtitle_en:'Malandain Ballet Biarritz',
    location:'哈德遜河岸公園, New York, NY',
    desc:'麥藍堤亞舞團帶來融合台灣原住民族身體記憶與當代舞蹈語彙的精彩演出，在哈德遜河岸公園戶外場地呈現台灣當代舞蹈的力與美。',
    desc_en:'A spectacular outdoor performance blending Taiwanese indigenous body memory with contemporary dance vocabulary, presented at the Hudson River Park waterfront stage.',
    category:'sound', isPrimary:false, externalUrl:'',
  },
  {
    num:'09', icon:'🎸',
    date:'2026-08-01', endDate:'2026-09-30',
    title:'徐崇育爵士樂團',
    title_en:'Hsu Chung-yu Jazz Ensemble',
    subtitle:'Clave de Taiwan 美國巡演',
    subtitle_en:'Clave de Taiwan US Tour',
    location:'紐約 × 邁阿密',
    desc:'台灣爵士吉他手徐崇育率領 Clave de Taiwan 樂團，以融合台灣民謠與拉丁爵士的獨特音樂語言，展開紐約至邁阿密的美國巡迴演出。',
    desc_en:'Taiwanese jazz guitarist Hsu Chung-yu leads Clave de Taiwan on a US tour from New York to Miami, blending Taiwanese folk melodies with Latin jazz in a unique musical voice.',
    category:'sound', isPrimary:false, externalUrl:'',
  },
  {
    num:'10', icon:'🎪',
    date:'2026-08-12', endDate:'2026-08-16',
    title:'國際偶戲藝穗節',
    title_en:'International Puppet Arts Fringe Festival',
    subtitle:'飛人集社《初生》',
    subtitle_en:'Fei-Performers《Birth》',
    location:'克萊門特中心, New York, NY',
    desc:'飛人集社以《初生》登上紐約國際偶戲藝穗節，以精緻偶戲技藝呈現台灣當代表演藝術，探索生命誕生與消逝的詩意敘事。',
    desc_en:'Fei-Performers brings 《Birth》to the New York International Puppet Arts Fringe, presenting a poetic narrative of life and loss through exquisite Taiwanese puppetry and contemporary performance.',
    category:'sound', isPrimary:false, externalUrl:'',
  },

  /* ── 影像與敘事 · 主要活動 ── */
  {
    num:'01', icon:'🎭',
    date:'2026-05-01',
    title:'臺美藝文大師系列講座',
    title_en:'Across Borders, Across Bodies: Lin Hwai-min in Conversation',
    subtitle:'林懷民 × Jodee Nimerichter · Feel the Wisdom.',
    subtitle_en:'Lin Hwai-min × Jodee Nimerichter · Feel the Wisdom.',
    location:'Asia Society, New York',
    desc:'這場對話邀請雲門舞集創辦人林懷民，與美國舞蹈節（ADF）執行長 Jodee Nimerichter 共同出席，由亞洲協會總監 Rachel Cooper 主持，回顧臺灣與美國之間數十年的藝術交流歷程。透過個人故事與幕後視角，揭示跨國夥伴關係如何塑造了雲門從臺灣走向世界舞台的旅程。',
    desc_en:'Cloud Gate founder Lin Hwai-min and ADF Executive Director Jodee Nimerichter join together in conversation, moderated by Asia Society\'s Rachel Cooper. Together they reflect on decades of artistic exchange between Taiwan and the United States, and how cross-border partnerships shaped Cloud Gate\'s journey from Taiwan to the world stage.',
    category:'image', isPrimary:true, externalUrl:'',
  },
  {
    num:'04', icon:'🎬',
    date:'2026-09-01', endDate:'2026-09-30',
    title:'世界之間：跨越疆界的臺灣電影',
    title_en:'Between Worlds: Taiwanese Cinema Across Borders',
    subtitle:'電影影展 · Feel the Frame.',
    subtitle_en:'Film Festival at Metrograph · Feel the Frame.',
    location:'Metrograph, 7 Ludlow St, New York',
    desc:'Metrograph 電影院自 2018 年起與駐紐約臺北文化中心深度合作，歷屆台灣影展場場爆滿。2026 年以「邊界、遷徙、歸屬」為主軸，策劃放映 10 部長片及 1 場短片選集，分三大策展方向：新浪潮起點、離散與遷徙、跨界合作，並邀請影人出席開幕。',
    desc_en:"Metrograph has partnered with the Taipei Cultural Center in New York since 2018, with every Taiwanese film program selling out. In 2026, Between Worlds presents 10 features and a short film program across three strands — New Wave Foundations, Diaspora Stories, and Cross-Border Collaborations — organized around the themes of borders, migration, and belonging.",
    category:'image', isPrimary:true, externalUrl:'',
  },

  /* ── 影像與敘事 · 其他活動 ── */
  {
    num:'11', icon:'🎞️',
    date:'2026-06-01', endDate:'2026-07-31',
    title:'紐約亞洲影展',
    title_en:'New York Asian Film Festival',
    subtitle:'第25屆・4部臺灣片入選',
    subtitle_en:'25th Edition · 4 Taiwanese Films Selected',
    location:'林肯電影中心, New York, NY',
    desc:'第 25 屆紐約亞洲影展共有 4 部臺灣電影入選，於林肯電影中心與紐約觀眾相遇，展現臺灣電影的多元視野與創作能量。',
    desc_en:'The 25th New York Asian Film Festival features 4 selected Taiwanese films screening at Lincoln Center, showcasing the diversity and creative energy of contemporary Taiwanese cinema.',
    category:'image', isPrimary:false, externalUrl:'',
  },
  {
    num:'12', icon:'🖥️',
    date:'2026-04-03', endDate:'2027-04-03',
    title:'鄭淑麗個展',
    title_en:'Shu Lea Cheang Solo Exhibition',
    subtitle:'互動電影裝置',
    subtitle_en:'Interactive Film Installation',
    location:'Leslie-Lohman Museum, New York, NY',
    desc:'台灣錄像藝術先驅鄭淑麗在 Leslie-Lohman 美術館展出互動電影裝置新作，以其標誌性的身體政治與性別議題，挑戰觀者的感官認知邊界。',
    desc_en:'Taiwanese video art pioneer Shu Lea Cheang presents a new interactive film installation at Leslie-Lohman Museum, challenging perceptions through her signature exploration of body politics and gender.',
    category:'image', isPrimary:false, externalUrl:'',
  },

  /* ── 街頭與生活 · 主要活動 ── */
  {
    num:'03', icon:'🎨',
    date:'2026-05-18', endDate:'2026-05-30',
    title:'布希維克街頭藝術節 臺灣藝術家參展',
    title_en:'The Bushwick Collective Block Party — Taiwan',
    subtitle:'五位臺灣壁畫藝術家 · Feel the Wall.',
    subtitle_en:'Five Taiwanese Mural Artists · Feel the Wall.',
    location:'Bushwick, Brooklyn, New York',
    desc:'駐紐約臺北文化中心邀請五位臺灣壁畫藝術家（黑雞先生、Colasa、VASTAR、ALLO、Candy Kuo）參與第 15 屆布希維克街頭藝術節，各自進行一幅大型壁畫現地創作。5 月 30 日正式開幕，壓軸歌手 Bone Thugs-N-Harmony 登台，免費參加。',
    desc_en:"The Taipei Cultural Center in New York brings five Taiwanese mural artists — Mr. Ogay, Colasa, VASTAR, ALLO, and Candy Kuo — to the 15th Bushwick Collective Block Party. Each creates one large-scale mural on-site in Bushwick. The Block Party on May 30 features ~50 new works and a headline performance by Bone Thugs-N-Harmony. Free admission.",
    category:'street', isPrimary:true, externalUrl:'',
  },
  {
    num:'05', icon:'🌈',
    date:'2026-06-28',
    title:'2026 紐約同志遊行',
    title_en:'2026 New York City Pride March',
    subtitle:'Nymphia Wind × 臺灣變裝皇后 · Feel the Pride.',
    subtitle_en:'Nymphia Wind × Taiwanese Drag Queens · Feel the Pride.',
    location:'5th Avenue, Manhattan, New York',
    desc:'《魯保羅變裝皇后秀》冠軍妮妃雅（Nymphia Wind）擔任策展與領銜演出，攜手臺灣變裝皇后 Tina Banana 與 Yolanda Mesula，以「檳榔西施」為主題打造花車。透過霓虹裝置、電子音樂與身體展演，讓臺灣美學在全球最具指標性的同志遊行現場發光。',
    desc_en:"RuPaul's Drag Race winner Nymphia Wind curates and leads the performance, joined by Taiwanese drag queens Tina Banana and Yolanda Mesula. Their float, themed around the Betel Nut Beauty, reinterprets a distinctly Taiwanese cultural figure through neon installations, electronic music, and performance at the world's most iconic Pride event.",
    category:'street', isPrimary:true, externalUrl:'',
  },
];

/* ---------- Quiz Game Data ---------- */
const GAME_DATA = {
  'lin-hwai-min': {
    id:'lin-hwai-min', title:'臺美藝文大師講座', title_en:'Taiwan–US Arts Master Lecture',
    subtitle:'林懷民 Lin Hwai-min', subtitle_en:'Lin Hwai-min',
    emoji:'🎭', color:'#8B4513', colorLight:'#fdf3e7',
    venue:'Asia Society, Upper East Side',
    unlockMsg:'你已認識台灣最重要的舞蹈藝術家之一！',
    unlockMsg_en:'You\'ve met one of Taiwan\'s most important dance artists!',
    questions:[
      { q:'林懷民在 1973 年創立的舞團，以台灣哪個傳統意象命名？',
        q_en:'The dance company Lin Hwai-min founded in 1973 is named after which traditional image?',
        opts:['雲門','竹影','墨荷','山嵐'], ans:0,
        opts_en:['Cloud Gate','Bamboo Shadow','Ink Lotus','Mountain Mist'],
        fact:'「雲門」取自《呂氏春秋》，是中國最古老的舞蹈之一，象徵天地之氣。雲門舞集是台灣第一個現代舞職業舞團。',
        fact_en:'"Cloud Gate" comes from the ancient text Lüshi Chunqiu and is one of China\'s oldest dances, symbolizing the energy of heaven and earth. Cloud Gate Dance Theatre was Taiwan\'s first professional modern dance company.' },
      { q:'林懷民除了是舞蹈家，他還有另一個重要身份是？',
        q_en:'Besides being a choreographer, Lin Hwai-min is also known as a?',
        opts:['小說家','電影導演','音樂家','建築師'], ans:0,
        opts_en:['Novelist','Film Director','Musician','Architect'],
        fact:'林懷民 22 歲就出版小說《蟬》，融合文學與肢體的思維深刻影響了雲門作品的敘事性。',
        fact_en:'Lin Hwai-min published his novel "Cicada" at age 22. His literary sensibility deeply shaped the narrative quality of Cloud Gate\'s works.' },
      { q:'雲門舞集代表作《薪傳》，描述的是台灣哪段歷史？',
        q_en:'Cloud Gate\'s landmark piece Legacy depicts which chapter of Taiwanese history?',
        opts:['先民渡海來台','日治時期抗爭','二二八事件','台灣經濟奇蹟'], ans:0,
        opts_en:['Early settlers crossing the strait','Resistance during Japanese rule','The 228 Incident','Taiwan\'s economic miracle'],
        fact:'《薪傳》1978 年首演，描述漢人先民冒險橫越台灣海峽來台墾荒，在台美斷交當晚演出，感動無數台灣人。',
        fact_en:'Legacy premiered in 1978, depicting Han settlers crossing the Taiwan Strait. It was performed the night Taiwan–US diplomatic relations were severed, deeply moving audiences across the island.' },
      { q:'林懷民的舞作常融合哪些台灣在地元素？',
        q_en:'Which local Taiwanese elements does Lin Hwai-min frequently weave into his choreography?',
        opts:['書法、太極、傳統音樂','嘻哈、街舞','芭蕾、歌劇','說唱、相聲'], ans:0,
        opts_en:['Calligraphy, Tai Chi & folk music','Hip-hop & street dance','Ballet & opera','Rap & stand-up comedy'],
        fact:'雲門舞集深受東方美學影響，林懷民曾讓舞者練習書法、太極導引，將這些身體訓練融入現代舞語彙中。',
        fact_en:'Cloud Gate is deeply rooted in Eastern aesthetics. Lin had dancers practice calligraphy and Tai Chi, integrating these disciplines into a modern dance vocabulary.' },
      { q:'林懷民於 2019 年退休，他將雲門舞集交棒給哪位接班人？',
        q_en:'When Lin Hwai-min retired in 2019, who did he hand Cloud Gate over to?',
        opts:['鄭宗龍','布拉瑞揚','周書毅','黃翊'], ans:0,
        opts_en:['Cheng Tsung-lung','Bulareyaung','Chou Shu-yi','Huang Yi'],
        fact:'鄭宗龍來自台北萬華，作品融合台灣庶民生活與當代舞蹈美學，成為雲門第二代藝術總監。',
        fact_en:'Cheng Tsung-lung grew up in Taipei\'s Wanhua district. His work blends everyday Taiwanese life with contemporary dance aesthetics, making him Cloud Gate\'s second artistic director.' }
    ]
  },
  'nso-paiwan': {
    id:'nso-paiwan', title:'NSO × 泰武古謠', title_en:'NSO × Taimu Ancient Ballads',
    subtitle:'原住民音樂 Indigenous Music', subtitle_en:'Indigenous Music of Taiwan',
    emoji:'🎵', color:'#1a6b3c', colorLight:'#e8f5ee',
    venue:'Carnegie Hall, Midtown',
    unlockMsg:'你已走入台灣原住民族的音樂靈魂！',
    unlockMsg_en:'You\'ve entered the musical soul of Taiwan\'s indigenous peoples!',
    questions:[
      { q:'泰武古謠傳唱所在的「泰武鄉」位於台灣哪個縣市？',
        q_en:'Taimu Ancient Ballads originate from Taimu Township, which is located in which Taiwanese county?',
        opts:['屏東縣','台東縣','花蓮縣','南投縣'], ans:0,
        opts_en:['Pingtung County','Taitung County','Hualien County','Nantou County'],
        fact:'泰武鄉位於屏東縣，是排灣族重要的文化聚落。泰武國小的古謠合唱團曾登上國際舞台，將排灣族傳統吟唱帶給全世界。',
        fact_en:'Taimu Township is in Pingtung County, an important Paiwan cultural community. The Taimu Elementary School choir has performed internationally, bringing traditional Paiwan chanting to the world.' },
      { q:'台灣官方認定的原住民族共有幾族？',
        q_en:'How many officially recognized indigenous peoples are there in Taiwan?',
        opts:['16 族','9 族','12 族','20 族'], ans:0,
        opts_en:['16 peoples','9 peoples','12 peoples','20 peoples'],
        fact:'台灣目前官方認定 16 個原住民族，各族擁有不同語言、音樂、祭儀與服飾。原住民族人口約 57 萬，佔全台人口約 2.4%。',
        fact_en:'Taiwan officially recognizes 16 indigenous peoples, each with distinct languages, music, ceremonies, and dress. The indigenous population is around 570,000, roughly 2.4% of Taiwan\'s total.' },
      { q:'排灣族傳統音樂中，有一種重要的雙管樂器叫做？',
        q_en:'What is the important double-pipe traditional instrument in Paiwan music?',
        opts:['鼻笛','口琴','月琴','陶笛'], ans:0,
        opts_en:['Nose flute','Harmonica','Moon lute','Ocarina'],
        fact:'鼻笛（paringed）是排灣族男性以鼻子吹奏的傳統樂器，象徵愛情與思念，是極具代表性的原住民族樂器。',
        fact_en:'The nose flute (paringed) is played by Paiwan men through the nose, symbolizing love and longing. It is one of the most iconic traditional instruments among Taiwan\'s indigenous peoples.' },
      { q:'布農族哪首歌曾因旋律特殊而被送往太空？',
        q_en:'Which Bunun song was sent into space on a probe due to its unique melodic structure?',
        opts:['祈禱小米豐收歌','捕魚祭歌','年祭歡歌','打耳祭歌'], ans:0,
        opts_en:['Pasibutbut (Millet Harvest Prayer)','Fishing Festival Song','New Year Celebration Song','Ear-shooting Festival Song'],
        fact:'布農族「祈禱小米豐收歌」是全球罕見的天然複音合唱，被聯合國教科文組織關注，並於 1970 年代被送上太空探測器。',
        fact_en:'The Bunun Pasibutbut is a rare natural polyphonic chant recognized by UNESCO. In the 1970s it was placed aboard a space probe to represent humanity\'s musical heritage.' },
      { q:'NSO 國家交響樂團成立於哪一年？',
        q_en:'In which year was Taiwan\'s National Symphony Orchestra (NSO) founded?',
        opts:['1986 年','1970 年','2000 年','1995 年'], ans:0,
        opts_en:['1986','1970','2000','1995'],
        fact:'NSO 國家交響樂團成立於 1986 年，是台灣最重要的職業交響樂團，長期致力於跨文化合作與原創委託。',
        fact_en:'Founded in 1986, the NSO is Taiwan\'s most important professional symphony orchestra, dedicated to cross-cultural collaboration and original commissioned works.' }
    ]
  },
  'bushwick': {
    id:'bushwick', title:'布希維克街頭藝術節', title_en:'Bushwick Street Art Festival',
    subtitle:'台灣視覺藝術 Taiwan Visual Art', subtitle_en:'Taiwanese Visual Art',
    emoji:'🎨', color:'#e8472a', colorLight:'#fdeee9',
    venue:'Bushwick Collective, Brooklyn',
    unlockMsg:'你已發現台灣視覺藝術的當代能量！',
    unlockMsg_en:'You\'ve discovered the contemporary energy of Taiwanese visual art!',
    questions:[
      { q:'布希維克（Bushwick）位於紐約哪個行政區？',
        q_en:'Bushwick is located in which New York City borough?',
        opts:['布魯克林','曼哈頓','皇后區','布朗克斯'], ans:0,
        opts_en:['Brooklyn','Manhattan','Queens','The Bronx'],
        fact:'Bushwick 位於布魯克林東北部，過去是工業區，近年成為全球最重要的街頭藝術聚落之一，每年吸引世界各地藝術家在此創作壁畫。',
        fact_en:'Bushwick is in northeast Brooklyn. Once an industrial district, it is now one of the world\'s most important street art communities, drawing artists from around the globe to paint murals each year.' },
      { q:'台灣廟宇文化中，哪種視覺元素最常出現在當代台灣藝術中？',
        q_en:'Which visual elements from Taiwan\'s temple culture most frequently appear in contemporary Taiwanese art?',
        opts:['龍、虎、神明圖騰','梅花與竹子','101大樓剪影','台灣黑熊'], ans:0,
        opts_en:['Dragon, tiger & deity iconography','Plum blossoms & bamboo','Taipei 101 silhouette','Formosan black bear'],
        fact:'台灣廟宇是當代設計師最重要的靈感來源之一。龍柱、交趾陶、剪黏工藝等廟宇美學，被大量轉化為現代插畫、街頭藝術與品牌設計。',
        fact_en:'Taiwan\'s temples are a key inspiration for contemporary designers. Dragon pillars, jiaozhi ceramics, and traditional craftwork have been widely transformed into modern illustration, street art, and brand design.' },
      { q:'台灣哪個地方以「彩虹眷村」壁畫聞名，差點遭拆除卻因民眾連署保留？',
        q_en:'Which Taiwanese city is home to the Rainbow Village murals, nearly demolished but saved by a public petition?',
        opts:['台中','台北','高雄','嘉義'], ans:0,
        opts_en:['Taichung','Taipei','Kaohsiung','Chiayi'],
        fact:'台中彩虹眷村由老兵黃永阜一人獨力彩繪，原本面臨拆除，後因民眾連署而保留，是台灣最具代表性的庶民藝術故事。',
        fact_en:'Taichung\'s Rainbow Village was painted single-handedly by veteran Huang Yung-fu. Originally slated for demolition, it was preserved after a public petition—one of Taiwan\'s most beloved folk art stories.' },
      { q:'台灣近年最受國際關注的當代藝術博覽會是？',
        q_en:'Which contemporary art fair in Taiwan has attracted the most international attention in recent years?',
        opts:['Taipei Dangdai（台北當代）','故宮特展','總統府藝廊','ART TAIPEI'], ans:0,
        opts_en:['Taipei Dangdai','National Palace Museum Special Exhibition','Presidential Office Gallery','ART TAIPEI'],
        fact:'Taipei Dangdai 自 2019 年起每年舉辦，匯聚亞洲與全球頂尖畫廊，是台灣打入國際當代藝術市場的重要窗口。',
        fact_en:'Taipei Dangdai, held annually since 2019, brings together leading galleries from Asia and around the world, and is Taiwan\'s key gateway into the international contemporary art market.' },
      { q:'「眷村文化」孕育了大量台灣藝術家，眷村最初是為安置哪些人而建立？',
        q_en:'Juancun (military dependents\' villages) produced many Taiwanese artists. Who were they originally built to house?',
        opts:['1949年隨國民政府來台的軍人及家屬','日治時期留台日本人','原住民族遷移安置','越戰難民'], ans:0,
        opts_en:['Soldiers & families who came with the KMT government in 1949','Japanese residents remaining after WWII','Relocated indigenous peoples','Vietnam War refugees'],
        fact:'眷村孕育了侯孝賢、朱天文等大批文藝人才。眷村美學融合中國各省習俗與台灣在地文化，形成獨特的混血風格。',
        fact_en:'Juancun produced a wealth of artistic talent including Hou Hsiao-hsien and Chu T\'ien-wen. Juancun aesthetics blend customs from various Chinese provinces with Taiwanese local culture, creating a unique hybrid style.' }
    ]
  },
  'film': {
    id:'film', title:'臺灣主題影展', title_en:'Taiwan Film Festival',
    subtitle:'台灣電影 Taiwan Cinema', subtitle_en:'Taiwan Cinema',
    emoji:'🎬', color:'#1a3a6b', colorLight:'#e8edf5',
    venue:'Metrograph, Lower East Side',
    unlockMsg:'你已進入台灣電影的黃金世界！',
    unlockMsg_en:'You\'ve entered the golden world of Taiwanese cinema!',
    questions:[
      { q:'台灣導演李安以哪部電影首次獲得奧斯卡最佳導演獎？',
        q_en:'With which film did Taiwanese director Ang Lee win his first Academy Award for Best Director?',
        opts:['斷背山','臥虎藏龍','少年Pi的奇幻漂流','色，戒'], ans:0,
        opts_en:['Brokeback Mountain','Crouching Tiger, Hidden Dragon','Life of Pi','Lust, Caution'],
        fact:'李安以《斷背山》（2005）獲得奧斯卡最佳導演獎，是首位獲此殊榮的亞裔導演，被視為全球最具影響力的華裔導演。',
        fact_en:'Ang Lee won the Oscar for Best Director with Brokeback Mountain (2005), becoming the first Asian director to receive this honor. He is widely regarded as the most influential Chinese-language filmmaker in the world.' },
      { q:'台灣「新電影運動」約發生在哪個年代？',
        q_en:'The Taiwan New Cinema movement took place in approximately which decade?',
        opts:['1980 年代','1960 年代','1970 年代','1990 年代'], ans:0,
        opts_en:['1980s','1960s','1970s','1990s'],
        fact:'1980 年代，侯孝賢、楊德昌等導演發起台灣新電影運動，以寫實風格記錄台灣社會，讓台灣電影首度在坎城、柏林、威尼斯等影展發光。',
        fact_en:'In the 1980s, directors Hou Hsiao-hsien and Edward Yang launched the Taiwan New Cinema movement, using realist storytelling to document Taiwanese society and win acclaim at Cannes, Berlin, and Venice.' },
      { q:'侯孝賢《悲情城市》獲得威尼斯金獅獎，描述的是台灣哪個歷史事件？',
        q_en:'Hou Hsiao-hsien\'s City of Sadness won the Venice Golden Lion. Which historical event does the film depict?',
        opts:['二二八事件','台灣光復','戒嚴解除','台美斷交'], ans:0,
        opts_en:['The 228 Incident','Retrocession of Taiwan','Lifting of Martial Law','Severance of Taiwan–US ties'],
        fact:'《悲情城市》（1989）以九份為背景，描述二二八事件後台灣人的創傷，是台灣第一部正面觸及此事件的電影。',
        fact_en:'City of Sadness (1989), set in Jiufen, portrays the trauma following the 228 Incident. It was the first Taiwanese film to directly confront this event and won the Golden Lion at Venice.' },
      { q:'宮崎駿《神隱少女》的靈感場景，據說來自台灣哪個地方？',
        q_en:'Which Taiwanese location is said to have inspired the setting of Hayao Miyazaki\'s Spirited Away?',
        opts:['九份老街','阿里山','淡水','台南安平'], ans:0,
        opts_en:['Jiufen Old Street','Alishan','Tamsui','Anping, Tainan'],
        fact:'九份的金礦小鎮風貌、山城燈籠與茶樓意象，常被認為是《神隱少女》油屋場景的靈感來源之一，讓九份成為全球觀光客必訪之地。',
        fact_en:'Jiufen\'s mountain town atmosphere, glowing lanterns, and teahouses are widely believed to have inspired the bathhouse scenes in Spirited Away, making it a must-visit destination for global tourists.' },
      { q:'台灣被稱為「台灣奧斯卡」的電影最高榮譽是？',
        q_en:'Which film award is known as the "Taiwanese Oscars"?',
        opts:['金馬獎','金鐘獎','金曲獎','金穗獎'], ans:0,
        opts_en:['Golden Horse Awards','Golden Bell Awards','Golden Melody Awards','Golden Harvest Awards'],
        fact:'金馬獎創立於 1962 年，是華語電影圈歷史最悠久、最具公信力的電影獎項，與金鐘、金曲並稱台灣三金。',
        fact_en:'The Golden Horse Awards, founded in 1962, are the oldest and most prestigious film awards in the Chinese-language world, known alongside the Golden Bell and Golden Melody as Taiwan\'s "Three Golds."' }
    ]
  },
  'pride': {
    id:'pride', title:'紐約同志大遊行', title_en:'NYC Pride March',
    subtitle:'台灣 LGBTQ+ 文化', subtitle_en:'Taiwan LGBTQ+ Culture',
    emoji:'🏳️‍🌈', color:'#9b30d9', colorLight:'#f3e8fd',
    venue:'5th Avenue, Manhattan',
    unlockMsg:'你已了解台灣在平權路上的驕傲！',
    unlockMsg_en:'You\'ve learned about Taiwan\'s proud journey toward equality!',
    questions:[
      { q:'台灣在哪一年成為亞洲第一個同性婚姻合法化的國家？',
        q_en:'In which year did Taiwan become the first country in Asia to legalize same-sex marriage?',
        opts:['2019 年','2017 年','2021 年','2015 年'], ans:0,
        opts_en:['2019','2017','2021','2015'],
        fact:'2019 年 5 月 24 日，台灣正式成為亞洲首個同性婚姻合法化的國家，全球排名第 27 個，引發全亞洲廣泛關注。',
        fact_en:'On May 24, 2019, Taiwan officially became the first country in Asia—and the 27th worldwide—to legalize same-sex marriage, drawing widespread attention across the continent.' },
      { q:'台灣同志遊行每年在哪個城市舉行，是亞洲規模最大的？',
        q_en:'In which city is Taiwan\'s annual Pride Parade held, the largest in Asia?',
        opts:['台北','台中','高雄','台南'], ans:0,
        opts_en:['Taipei','Taichung','Kaohsiung','Tainan'],
        fact:'台北同志遊行自 2003 年起每年舉辦，近年參與人數突破 20 萬人，是亞洲規模最大的同志驕傲遊行。',
        fact_en:'The Taipei Pride Parade has been held annually since 2003. In recent years, attendance has surpassed 200,000 people, making it the largest Pride event in Asia.' },
      { q:'台灣同婚合法化的關鍵判決來自哪個機構？',
        q_en:'Which body issued the pivotal ruling that led to the legalization of same-sex marriage in Taiwan?',
        opts:['司法院大法官','立法院','行政院','總統府'], ans:0,
        opts_en:['Council of Grand Justices','Legislative Yuan','Executive Yuan','Presidential Office'],
        fact:'2017 年司法院大法官做出釋字第 748 號解釋，認定民法不允許同婚違憲，要求立法機關兩年內完成修法，開啟合法化歷程。',
        fact_en:'In 2017, the Council of Grand Justices issued Interpretation No. 748, ruling that the Civil Code\'s prohibition of same-sex marriage was unconstitutional and requiring the legislature to amend the law within two years.' },
      { q:'台灣最具代表性的 LGBTQ+ 友善商圈位於台北哪裡？',
        q_en:'Where in Taipei is Taiwan\'s most iconic LGBTQ+-friendly neighborhood?',
        opts:['西門町','信義區','天母','北投'], ans:0,
        opts_en:['Ximending','Xinyi District','Tianmu','Beitou'],
        fact:'西門町是台灣最具代表性的 LGBTQ+ 友善商圈，被稱為「台灣的 Chelsea」，彩虹旗飄揚的咖啡廳與友善商店密集。',
        fact_en:'Ximending is Taiwan\'s most iconic LGBTQ+-friendly district, often called "Taiwan\'s Chelsea," with rainbow flags flying from cafés and welcoming shops throughout.' },
      { q:'哪位台灣導演以電影三部曲記錄台灣 LGBTQ+ 故事享譽國際？',
        q_en:'Which Taiwanese director gained international acclaim for a film trilogy documenting LGBTQ+ stories in Taiwan?',
        opts:['周美玲','李安','侯孝賢','魏德聖'], ans:0,
        opts_en:['Zero Chou','Ang Lee','Hou Hsiao-hsien','Wei Te-sheng'],
        fact:'周美玲導演的「同志三部曲」以細膩筆觸描繪台灣 LGBTQ+ 生命經驗，在國際影展廣受好評。',
        fact_en:'Director Zero Chou\'s "Queer Trilogy" portrays LGBTQ+ life in Taiwan with sensitivity and depth, winning broad acclaim at international film festivals.' }
    ]
  },
  'horse': {
    id:'horse', title:'翃舞製作', title_en:'H·Art·Ch Dance Company',
    subtitle:'台灣當代舞蹈 Contemporary Dance', subtitle_en:'Taiwanese Contemporary Dance',
    emoji:'💃', color:'#c47a00', colorLight:'#fdf4e0',
    venue:'Skirball Cultural Center, Upper West Side',
    unlockMsg:'你已感受台灣當代舞蹈的力與美！',
    unlockMsg_en:'You\'ve felt the power and beauty of Taiwanese contemporary dance!',
    questions:[
      { q:'台灣當代舞蹈最常從哪些台灣本土元素汲取靈感？',
        q_en:'Which local Taiwanese elements most frequently inspire contemporary Taiwanese dance?',
        opts:['廟會儀式與原住民族肢體','古典芭蕾技巧','日本武道','韓國流行舞蹈'], ans:0,
        opts_en:['Temple rituals & indigenous movement','Classical ballet technique','Japanese martial arts','Korean pop dance'],
        fact:'台灣當代舞蹈創作者常向廟會陣頭、牽亡魂儀式、原住民族歌舞尋找靈感，以當代技法重新詮釋，形成台灣獨特的舞蹈語彙。',
        fact_en:'Taiwanese contemporary dance choreographers draw inspiration from temple processions, spirit-guiding ceremonies, and indigenous songs and dances, reinterpreting them through contemporary techniques to form a uniquely Taiwanese movement language.' },
      { q:'台灣哪位舞蹈家以「與機器人共舞」聞名全球？',
        q_en:'Which Taiwanese dancer became world-famous for "dancing with a robot"?',
        opts:['黃翊','布拉瑞揚','鄭宗龍','林懷民'], ans:0,
        opts_en:['Huang Yi','Bulareyaung','Cheng Tsung-lung','Lin Hwai-min'],
        fact:'黃翊的代表作《黃翊與庫卡》讓舞者與工業機器人 KUKA 共舞，探討人與科技的關係，在全球 15+ 國家巡演。',
        fact_en:'Huang Yi\'s signature work HUANG YI & KUKA features a dancer performing alongside industrial robot KUKA, exploring the relationship between humans and technology. It has toured in over 15 countries.' },
      { q:'以原住民族身份融合當代舞蹈的布拉瑞揚，屬於哪個族群？',
        q_en:'Bulareyaung, who integrates his indigenous heritage into contemporary dance, belongs to which ethnic group?',
        opts:['排灣族','阿美族','卑南族','泰雅族'], ans:0,
        opts_en:['Paiwan','Amis','Puyuma','Atayal'],
        fact:'布拉瑞揚·帕格勒法為排灣族人，曾為雲門舞集舞者，2015 年回故鄉台東成立舞團，作品融合排灣族文化與當代舞蹈。',
        fact_en:'Bulareyaung Pagarlava is Paiwan. A former Cloud Gate dancer, he returned to his hometown in Taitung in 2015 to found his own company, blending Paiwan culture with contemporary dance.' },
      { q:'台灣最重要的表演藝術機構「兩廳院」的正式名稱是？',
        q_en:'What is the official name of Taiwan\'s most important performing arts institution, known as "Liangting Yuan"?',
        opts:['國立中正文化中心','國立台灣藝術大學','台北市文化局','文化部'], ans:0,
        opts_en:['National Chiang Kai-shek Cultural Center','National Taiwan University of Arts','Taipei City Cultural Affairs Bureau','Ministry of Culture'],
        fact:'兩廳院（國立中正文化中心）旗下的國家音樂廳與國家戲劇院，是台灣表演藝術的最高殿堂。',
        fact_en:'The National Chiang Kai-shek Cultural Center—home to the National Concert Hall and National Theater—is the pinnacle of performing arts in Taiwan.' },
      { q:'「翃」這個字的意思最接近？',
        q_en:'The character 「翃」 most closely means?',
        opts:['鳥振翅飛翔','大地寬廣','水波流動','光芒四射'], ans:0,
        opts_en:['A bird spreading its wings in flight','Vast and wide-open land','Water flowing in ripples','Light radiating in all directions'],
        fact:'「翃」意指鳥飛翔的樣子，象徵舞者以身體在空間中飛翔探索的意志。翃舞製作成立於 2011 年，以跨域創作見長。',
        fact_en:'「翃」 depicts a bird in full flight, symbolizing a dancer\'s will to soar and explore space with their body. H·Art·Ch was founded in 2011 and is known for interdisciplinary creation.' }
    ]
  },
  'summerstage': {
    id:'summerstage', title:'SummerStage: Taiwanese Waves', title_en:'SummerStage: Taiwanese Waves',
    subtitle:'台灣之夜 Taiwan Night', subtitle_en:'A Night of Taiwan',
    emoji:'🌙', color:'#0d6b8c', colorLight:'#e0f2f8',
    venue:'Central Park SummerStage, Rumsey Playfield',
    unlockMsg:'你已體驗一夜台灣的完整魅力！',
    unlockMsg_en:'You\'ve experienced the full magic of a Taiwanese night!',
    questions:[
      { q:'台灣最具代表性的飲料「珍珠奶茶」發源於哪個城市？',
        q_en:'Which city is the birthplace of bubble tea (boba), Taiwan\'s most iconic drink?',
        opts:['台中','台北','台南','高雄'], ans:0,
        opts_en:['Taichung','Taipei','Tainan','Kaohsiung'],
        fact:'珍珠奶茶（Bubble Tea）1980 年代起源於台中，如今全球市場規模已超過 30 億美元，是台灣對世界飲食文化最大的貢獻之一。',
        fact_en:'Bubble tea originated in Taichung in the 1980s. Today it is a global industry worth over $3 billion, representing Taiwan\'s biggest contribution to world food culture.' },
      { q:'Central Park SummerStage 提供什麼樣的演出？',
        q_en:'What kind of performances does Central Park SummerStage offer?',
        opts:['免費戶外音樂表演','付費室內音樂廳','電影首映','藝術拍賣'], ans:0,
        opts_en:['Free outdoor music performances','Ticketed indoor concert hall','Film premieres','Art auctions'],
        fact:'Central Park SummerStage 自 1986 年起每年夏季舉辦免費戶外演出，是紐約最重要的多元文化音樂平台。',
        fact_en:'Central Park SummerStage has hosted free outdoor performances every summer since 1986, making it New York\'s most important multicultural music platform.' },
      { q:'台灣「辦桌文化」是指什麼？',
        q_en:'What does the Taiwanese tradition of "ban-do" (辦桌) refer to?',
        opts:['戶外大型宴席文化','便當盒飯文化','夜市攤販文化','早餐店文化'], ans:0,
        opts_en:['Outdoor communal banquet culture','Bento box lunch culture','Night market stall culture','Breakfast shop culture'],
        fact:'「辦桌」是台灣傳統的戶外宴席文化，在喜慶、廟會等場合，由總鋪師在路邊搭棚大宴賓客，是台灣最具凝聚力的庶民飲食儀式。',
        fact_en:'"Ban-do" is Taiwan\'s traditional outdoor banquet culture. For celebrations and temple festivals, a master chef sets up a large street banquet—one of Taiwan\'s most community-bonding culinary rituals.' },
      { q:'以下哪位音樂人被稱為「華語流行音樂天王」，來自台灣？',
        q_en:'Which Taiwanese musician is known as the "King of Mandopop"?',
        opts:['周杰倫（Jay Chou）','BTS 防彈少年團','張學友','劉德華'], ans:0,
        opts_en:['Jay Chou (周杰倫)','BTS','Jacky Cheung (張學友)','Andy Lau (劉德華)'],
        fact:'周杰倫自 2000 年代起稱霸全球華語市場，以融合中西音樂元素的創作風格著稱，至今仍是全球最具影響力的華語藝人之一。',
        fact_en:'Jay Chou has dominated the global Mandopop market since the 2000s, celebrated for blending Eastern and Western musical styles. He remains one of the most influential Chinese-language artists in the world.' },
      { q:'台灣夜市文化中，「雞排」是哪種料理方式的代表？',
        q_en:'In Taiwan\'s night market culture, what is "ji pai" (chicken steak) famous for?',
        opts:['炸雞胸肉排，比臉大','烤雞腿','滷雞翅','蒸雞肉'], ans:0,
        opts_en:['A fried chicken breast bigger than your face','Grilled chicken leg','Braised chicken wings','Steamed chicken'],
        fact:'台灣大雞排以巨大尺寸（比臉還大）、酥脆外皮聞名，是夜市最具代表性的食物之一，也是外國旅客必嚐的小吃體驗。',
        fact_en:'Taiwan\'s giant fried chicken steak is famous for its enormous size—bigger than your face—and its crispy coating. It is one of the most iconic night market foods and a must-try for foreign visitors.' }
    ]
  }
};
