'use strict';

/* ---------- Language Strings (ZH / EN) ---------- */
const LANG = {
  zh: {
    /* Navbar */
    'nav-concept':'黑潮理念',
    'nav-news':'最新消息','nav-events':'展演活動','nav-discover':'文化探索',
    'nav-calendar':'行事曆','nav-contact':'聯絡我們',
    /* Banner */
    'banner-sub':'台灣文化部 × 紐約文化局合作計畫<br>七大藝文展演，2026 紐約登場',
    'btn-explore':'探索活動','btn-news':'最新消息',
    /* Articles */
    'sec-news-title':'最新消息',
    'sec-news-sub':'掌握 Taiwan Pop 計畫最新動態，了解台灣與紐約的文化對話',
    'art-1-cat':'官方公告',
    'art-1-title':'Taiwan Pop 計畫正式啟動！台灣文化將在紐約發聲',
    'art-1-desc':'台灣文化部攜手紐約文化局，共同推出 Taiwan Pop 文化交流計畫，七大藝文展演於 2026 年在紐約各地精彩登場。',
    'art-2-cat':'活動預告',
    'art-2-title':'雲門舞集創辦人林懷民將赴紐約展開大師講座',
    'art-2-desc':'臺美藝文大師系列講座首場邀請林懷民現身紐約，暢談台灣當代藝術創作、身體美學與跨文化對話。',
    'art-3-cat':'活動預告',
    'art-3-title':'中央公園 SummerStage「Taiwanese Waves」盛夏登場',
    'art-3-desc':'Taiwan Pop 壓軸活動確認進駐紐約著名戶外演出場地 SummerStage，帶來融合台灣當代音樂與視覺的跨界演出。',
    'art-4-cat':'專題報導',
    'art-4-title':'什麼是 Taiwan Pop？一個讓台灣文化被看見的計畫',
    'art-4-desc':'從當代舞蹈、原住民古謠、街頭藝術到電影影展，Taiwan Pop 不只是音樂，而是多元台灣文化的全面展演。',
    'btn-more-news':'查看更多消息',
    /* Concept */
    'concept-title':'臺灣<em>尚趴</em>',
    'concept-slogan':'Feel the Pop · 曼哈頓的臺灣日常',
    'concept-manifesto':'台灣文化不是博物館裡的展品，而是此刻正在發生的生活日常。2026 年，Taiwan Pop 以塗鴉為語言，以藝術為媒介，帶著七大展演橫跨曼哈頓——從大師講座到中央公園夏日舞台，讓紐約在這個夏天，看見最真實的台灣。',
    'concept-p1-title':'紐文中心<br>文化地標',
    'concept-p1-desc':'紐文中心作為黑潮計畫的實體品牌中心，透過塗鴉次文化元素融入公務大樓外觀，成為曼哈頓最具辨識度的台灣文化打卡地標。每一位走進這裡的訪客，都是台灣文化的第一手見證者。',
    'concept-p2-title':'線性串連<br>整個夏天',
    'concept-p2-desc':'從 5 月的林懷民大師講座，到 8 月中央公園的 Taiwanese Waves，七個活動成為每一個行銷波段的節點，以連續出現的主視覺建立視覺覆蓋，讓整個紐約的夏天都有台灣的聲音。',
    'concept-p3-title':'Taiwan Pop<br>視覺覆蓋',
    'concept-p3-desc':'一個以紐約塗鴉文化為靈魂的主視覺，持續出現在街頭廣告、在地商家、活動現場。每一杯貼著主視覺的手搖飲、每一個茄芷袋，都是行走在曼哈頓的台灣文化宣言。',
    /* Events */
    'sec-events-title':'展演活動',
    'sec-events-sub':'2026 年，十二場跨領域藝文展演，以三大主題在紐約呈現最真實的台灣',
    'cat-sound-label':'身體與聲音',
    'cat-sound-sub':'現場表演・音樂・舞蹈',
    'cat-image-label':'影像與敘事',
    'cat-image-sub':'電影・視覺藝術・文學',
    'cat-street-label':'街頭與生活',
    'cat-street-sub':'藝術節・遊行・城市現場',
    'event-cta':'了解更多・立即報名 →',
    /* Discover */
    'sec-discover-title':'探索台灣 × 紐約',
    'sec-discover-sub':'滑動地圖，找到每場活動的地點，點擊開始你的台灣文化探索之旅',
    'map-hint':'← 滑動探索地圖 →',
    'map-prefix':'已探索','map-suffix':'個台灣文化主題',
    /* Calendar */
    'sec-cal-title':'活動行事曆',
    'sec-cal-sub':'掌握所有活動日期，提前規劃您的參與計畫',
    'cal-upcoming-h':'近期活動','cal-legend':'活動日期','cal-no-events':'暫無近期活動',
    /* Footer */
    'footer-desc':'Taiwan Pop 是台灣文化部與紐約文化局合作的年度文化交流計畫，透過七大藝文展演讓台灣被世界看見。',
    'footer-links-h':'快速連結','footer-contact-h':'聯絡資訊',
    'footer-news':'最新消息','footer-events':'展演活動','footer-discover':'文化探索',
    'footer-cal':'行事曆','footer-hours':'週一至週五 09:00–18:00 (TST)',
    /* Map Pins */
    'pin-1':'林懷民講座','pin-2':'NSO × 泰武古謠','pin-3':'布希維克街頭藝術節',
    'pin-4':'臺灣主題影展','pin-5':'紐約同志大遊行','pin-6':'翃舞製作','pin-7':'Taiwanese Waves',
    /* Modal */
    'modal-cta':'了解更多詳情 →',
    /* Quiz UI */
    'quiz-back':'← 返回地圖',
    'quiz-next-q':'下一題 →','quiz-see-result':'查看結果 →',
    'quiz-retry':'再試一次','quiz-back-map':'回到地圖 ↗',
    'quiz-res-perfect':'完美！你對台灣文化的了解讓我們驕傲！',
    'quiz-res-good':'答得不錯！你已經對台灣有相當的認識了。',
    'quiz-res-keep':'繼續加油！台灣的故事等著你慢慢探索。',
    /* Celebration */
    'cel-title':'台灣文化全制霸！',
    'cel-sub':'你以全滿分征服了所有七大主題！<br>對台灣文化的熱情與了解，令我們驕傲。',
    'cel-badge':'✨ 七大文化探索者 ✨',
    'cel-invite':'準備好親臨紐約，感受這些文化盛事了嗎？',
    'cel-to-events':'前往活動頁面 →','cel-close':'繼續探索',
    /* Concept Page */
    'cp-hero-title':'黑潮理念',
    'cp-hero-sub':'一個讓台灣文化在紐約發聲的計畫，從理念到行動的完整脈絡',
    'cp-origin-tag':'01 · 活動緣起',
    'cp-origin-title':'為什麼是紐約？<br>為什麼是現在？',
    'cp-origin-p1':'台灣的文化能量，從來不缺席——缺的是被看見的機會。2026 年，適逢紐文中心成立35週年，台灣文化部與紐約文化局以「黑潮」為名，策動一場橫跨整個夏天的文化行動。',
    'cp-origin-p2':'黑潮，是太平洋上那道來自台灣的深層洋流，跨越邊界、穿越海洋，帶著熱帶的溫度抵達北美。這個計畫，正是那道洋流的文化版本。',
    'cp-origin-p3':'Taiwan Pop 不是一場表演，而是一整個夏天的台灣存在。從街頭到舞台，從電影到古謠，讓紐約看見最立體的台灣。',
    'cp-id-tag':'02 · 品牌識別',
    'cp-id-title':'Semi-Wildstyle<br>主視覺美學',
    'cp-id-sub':'以紐約塗鴉文化為語言，書寫台灣的當代宣言',
    'cp-id-c1-title':'Magenta 洋紅',
    'cp-id-c1-desc':'#F52281 — 台灣的熱度，是這個計畫的主調。霓虹般的洋紅，讓台灣在曼哈頓的夜晚無法被忽視。',
    'cp-id-c2-title':'Neon Green 螢光綠',
    'cp-id-c2-desc':'#00FF00 — 街頭噴漆的生命力，是塗鴉文化與台灣活力的共同語言。',
    'cp-id-c3-title':'Pure White 純白',
    'cp-id-c3-desc':'#FFFFFF — 反差底色，讓文字在純黑底上發光，如同深夜街頭的塗鴉。',
    'cp-id-note':'Semi-Wildstyle 是介於可辨讀與抽象之間的塗鴉字體風格。Taiwan Pop 以此作為主視覺文字基底，在視覺上同時傳遞「紐約街頭」與「台灣個性」的雙重身份。這套識別系統將持續出現在紐文中心外觀、活動現場、聯名周邊與街頭媒體上。',
    'cp-35-tag':'03 · 紐文35背景',
    'cp-35-title':'紐文中心<br>35 週年',
    'cp-35-p1':'台灣駐紐約台北文化中心（紐文中心）自 1991 年成立以來，已是台灣文化對外交流的最重要窗口之一。2026 年適逢35週年，是這個計畫最重要的時間節點。',
    'cp-35-p2':'Taiwan Pop 以35週年為契機，啟動前所未有的城市規模文化行動。紐文中心不再只是一棟辦公大樓，而是整個夏天的台灣文化地標——外牆成為畫布，大廳成為展場，成為每位旅美台灣人的精神座標。',
    'cp-35-stat1':'週年','cp-35-stat2':'創立年份','cp-35-stat3':'藝文展演',
    'cp-partners-tag':'04 · 聯名商家',
    'cp-partners-title':'Taiwan Pop 在地夥伴',
    'cp-partners-sub':'走進這些地方，感受台灣文化在紐約的日常存在',
    'cp-cat-bubble':'手搖飲','cp-cat-restaurant':'台灣料理','cp-cat-bookstore':'書店・文創','cp-cat-art':'藝術空間',
    'cp-partners-note':'* 以上為示意清單，正式聯名商家名單將於活動前公布',
    'cp-awe-tag':'05 · 品牌角色',
    'cp-awe-title':'認識 a-We',
    'cp-awe-sub':'Taiwan Pop 的形象大使，無限成長的文化稀有寶',
    'cp-awe-zh-name':'無限成長稀有寶',
    'cp-awe-attr-h':'能力屬性',
    'cp-awe-attr1-name':'連續加成','cp-awe-attr1-desc':'每次踩上新格子，能力值就累積增長，越走越強。',
    'cp-awe-attr2-name':'領域展開','cp-awe-attr2-desc':'涉足文化領域，解鎖新技能，台灣知識越廣，領域越大。',
    'cp-awe-attr3-name':'伸縮自如','cp-awe-attr3-desc':'能屈能伸，適應任何文化場域，從音樂廳到街頭都自在。',
    'cp-awe-attr4-name':'集氣蓄力','cp-awe-attr4-desc':'每次答對問題蓄積文化能量，等待最佳時機全力爆發。',
    'cp-awe-form-front':'正面','cp-awe-form-back':'背面','cp-awe-form-left':'左側','cp-awe-form-right':'右側',
    'cp-awe-mission-h':'四大任務',
    'cp-awe-mission1':'探索台灣藝文展演，成為紐約的文化嚮導',
    'cp-awe-mission2':'記錄黑潮視角，用底片留住城市的台灣時刻',
    'cp-awe-mission3':'聯結旅美台灣人，讓彼此的故事交織成網',
    'cp-awe-mission4':'征服文化大富翁，以知識換取台灣文化稱號',
    'cp-awe-equip-h':'專屬裝備',
    'cp-awe-equip-name':'無限儲存空間魔法袋',
    'cp-awe-equip-desc':'可裝下任何形式的台灣文化記憶——音樂、影像、食物香氣、街頭印記，全部收納，永不遺失。',
    'cp-film-tag':'06 · 底片機計畫',
    'cp-film-title':'黑潮視角<br>底片機紀實',
    'cp-film-p1':'在快拍與濾鏡統治的時代，Taiwan Pop 選擇底片。',
    'cp-film-p2':'我們邀請藝術工作者、旅美台灣人，以底片相機記錄 2026 年夏天的紐約——那些在城市角落發生的台灣時刻：一杯手搖飲被舉起、一段古謠在廣場流動、一抹塗鴉的洋紅出現在磚牆上。',
    'cp-film-p3':'這些影像將累積成紐文中心35週年的城市圖像檔案，成為這個夏天最真實的台灣記錄。底片的顆粒感，是刻意的選擇——我們想要留下的，是那種無法完美複製的溫度。',
    'cp-film-join':'洽詢參與方式 →',
    'cp-film-badge':'底片 · 紐約 · 2026',
    'cp-press-tag':'07 · 媒體洽詢',
    'cp-press-title':'媒體與合作洽詢',
    'cp-press-sub':'歡迎媒體採訪、合作邀約與商業洽談，請透過以下方式聯絡我們',
    'cp-press-media-h':'媒體聯絡','cp-press-media-note':'新聞稿索取、採訪申請、圖片授權',
    'cp-press-partner-h':'合作洽詢','cp-press-partner-note':'聯名商家、活動贊助、品牌合作',
    'cp-press-film-h':'底片機計畫報名','cp-press-film-note':'攝影參與、作品投稿、底片借用申請',
    'cp-press-hours-h':'服務時間',
    'cp-press-hours':'週一至週五<br>09:00 – 18:00 (TST)',
    'cp-press-hours-note':'通常於 2 個工作日內回覆',
    /* Calendar internals */
    months:['1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月'],
    shortMonths:['JAN','FEB','MAR','APR','MAY','JUN','JUL','AUG','SEP','OCT','NOV','DEC'],
    weekdays:['日','一','二','三','四','五','六'],
    calTitle:(y,mn)=>`${y} 年 ${mn}`,
  },
  en: {
    /* Navbar */
    'nav-concept':'Black Current',
    'nav-news':'News','nav-events':'Events','nav-discover':'Discover',
    'nav-calendar':'Calendar','nav-contact':'Contact',
    /* Banner */
    'banner-sub':'Taiwan Ministry of Culture × NYC Dept. of Cultural Affairs<br>Seven Cultural Events, New York 2026',
    'btn-explore':'Explore Events','btn-news':'Latest News',
    /* Articles */
    'sec-news-title':'Latest News',
    'sec-news-sub':'Stay up to date with Taiwan Pop and the cultural dialogue between Taiwan and New York',
    'art-1-cat':'Announcement',
    'art-1-title':'Taiwan Pop Officially Launched — Taiwan Culture Coming to New York',
    'art-1-desc':"Taiwan's Ministry of Culture and NYC's Dept. of Cultural Affairs jointly launch the Taiwan Pop cultural exchange, bringing seven spectacular arts events across New York in 2026.",
    'art-2-cat':'Preview',
    'art-2-title':'Cloud Gate Founder Lin Hwai-min to Give Masterclass in New York',
    'art-2-desc':"The first Taiwan-US Arts Master Series invites Lin Hwai-min to New York to share his five-decade creative journey and Taiwan's contemporary arts with the world.",
    'art-3-cat':'Preview',
    'art-3-title':'"Taiwanese Waves" at Central Park SummerStage This Summer',
    'art-3-desc':"Taiwan Pop's grand finale is confirmed at New York's iconic outdoor venue SummerStage, featuring a cross-disciplinary show blending Taiwan's contemporary music and visual arts.",
    'art-4-cat':'Feature',
    'art-4-title':"What Is Taiwan Pop? A Campaign to Put Taiwan's Culture on the World Stage",
    'art-4-desc':"From contemporary dance and indigenous chants to street art and film — Taiwan Pop is more than music. It's a full showcase of Taiwan's diverse cultural identity.",
    'btn-more-news':'More News',
    /* Concept */
    'concept-title':'Taiwan <em>Pops</em>',
    'concept-slogan':'Feel the Pop · Taiwanese Daily Life in Manhattan',
    'concept-manifesto':"Taiwan's culture isn't confined to museums — it's alive, unfolding in the streets right now. In 2026, Taiwan Pop speaks through graffiti, moves through art, and arrives in Manhattan with seven events stretching from masterclass to outdoor stage — letting New York feel the most authentic Taiwan.",
    'concept-p1-title':'Cultural Hub<br>in Manhattan',
    'concept-p1-desc':"The Taiwanese Cultural Center serves as the physical brand hub of the Black Current Project. Through graffiti-infused architecture, it becomes Manhattan's most recognizable Taiwan cultural landmark — a space where every visitor witnesses Taiwan's culture firsthand.",
    'concept-p2-title':'Seven Events<br>All Summer Long',
    'concept-p2-desc':"From Lin Hwai-min's masterclass in May to Taiwanese Waves at Central Park in August, seven events anchor each campaign wave — building sustained visual coverage that ensures Taiwan's voice is heard throughout New York's entire summer.",
    'concept-p3-title':'Taiwan Pop<br>Visual Identity',
    'concept-p3-desc':"A single visual identity rooted in New York's graffiti culture appears across billboards, local shops, and event venues. Every branded bubble tea cup, every tote bag on the subway, is a Taiwan cultural statement walking through Manhattan.",
    /* Events */
    'sec-events-title':'Performances',
    'sec-events-sub':'Twelve cross-disciplinary arts events in 2026, presenting the most authentic Taiwan in New York across three themes',
    'cat-sound-label':'Body & Sound',
    'cat-sound-sub':'Live Performance · Music · Dance',
    'cat-image-label':'Image & Narrative',
    'cat-image-sub':'Film · Visual Arts · Literature',
    'cat-street-label':'Street & Life',
    'cat-street-sub':'Festival · Parade · Urban Scene',
    'event-cta':'Learn More · Register →',
    /* Discover */
    'sec-discover-title':'Discover Taiwan × New York',
    'sec-discover-sub':"Scroll the map to find each event's location. Click to begin your Taiwan cultural exploration",
    'map-hint':'← Scroll to Explore →',
    'map-prefix':'Explored','map-suffix':'Cultural Themes',
    /* Calendar */
    'sec-cal-title':'Event Calendar',
    'sec-cal-sub':'Mark your calendar and plan your visit in advance',
    'cal-upcoming-h':'Upcoming Events','cal-legend':'Event Date','cal-no-events':'No upcoming events',
    /* Footer */
    'footer-desc':'Taiwan Pop is an annual cultural exchange program by the Taiwan Ministry of Culture and NYC Dept. of Cultural Affairs, showcasing Taiwan to the world through seven arts events.',
    'footer-links-h':'Quick Links','footer-contact-h':'Contact',
    'footer-news':'News','footer-events':'Events','footer-discover':'Discover',
    'footer-cal':'Calendar','footer-hours':'Mon–Fri 09:00–18:00 (TST)',
    /* Map Pins */
    'pin-1':'Lin Hwai-min Lecture','pin-2':'NSO × Taiwu Ballads','pin-3':'Bushwick Street Art Festival',
    'pin-4':'Taiwan Film Festival','pin-5':'NYC Pride March','pin-6':'H·Art·Ch Dance','pin-7':'Taiwanese Waves',
    /* Modal */
    'modal-cta':'Learn More →',
    /* Quiz UI */
    'quiz-back':'← Back to Map',
    'quiz-next-q':'Next →','quiz-see-result':'See Results →',
    'quiz-retry':'Try Again','quiz-back-map':'Back to Map ↗',
    'quiz-res-perfect':'Perfect! Your knowledge of Taiwanese culture fills us with pride!',
    'quiz-res-good':'Well done! You already have a solid understanding of Taiwan.',
    'quiz-res-keep':"Keep going! The story of Taiwan is waiting to be explored.",
    /* Celebration */
    'cel-title':'Taiwan Cultural Grand Master!',
    'cel-sub':"You've aced all seven themes with a perfect score!<br>Your passion and knowledge of Taiwanese culture fills us with pride.",
    'cel-badge':'✨ Seven Cultural Explorer ✨',
    'cel-invite':'Ready to experience these cultural events in New York?',
    'cel-to-events':'Go to Events →','cel-close':'Keep Exploring',
    /* Concept Page */
    'cp-hero-title':'Black Current',
    'cp-hero-sub':'The full story behind Taiwan Pop — from vision to action',
    'cp-origin-tag':'01 · Origin',
    'cp-origin-title':'Why New York?<br>Why Now?',
    'cp-origin-p1':"Taiwan's cultural energy has never been absent — it just needs to be seen. In 2026, marking the 35th anniversary of the Taiwanese Cultural Center in New York, Taiwan's Ministry of Culture and NYC's Dept. of Cultural Affairs launch a city-wide cultural movement under the name \"Black Current\".",
    'cp-origin-p2':'The Black Current is the deep Pacific Ocean current that flows from Taiwan across the ocean to North America, carrying tropical warmth across borders. This campaign is its cultural equivalent.',
    'cp-origin-p3':"Taiwan Pop is not a single performance — it's a whole summer of Taiwan's presence. From street to stage, from film to indigenous chants, letting New York see Taiwan in full dimension.",
    'cp-id-tag':'02 · Visual Identity',
    'cp-id-title':'Semi-Wildstyle<br>Visual Aesthetic',
    'cp-id-sub':'Speaking through New York graffiti culture, writing Taiwan\'s contemporary declaration',
    'cp-id-c1-title':'Magenta',
    'cp-id-c1-desc':"#F52281 — Taiwan's heat is this campaign's keynote. Neon magenta ensures Taiwan cannot be ignored in Manhattan's nights.",
    'cp-id-c2-title':'Neon Green',
    'cp-id-c2-desc':"#00FF00 — The vitality of street spray paint, the shared language of graffiti culture and Taiwan's energy.",
    'cp-id-c3-title':'Pure White',
    'cp-id-c3-desc':'#FFFFFF — High-contrast base, letting text glow against pure black, like graffiti on a midnight wall.',
    'cp-id-note':"Semi-Wildstyle sits between legible and abstract graffiti lettering. Taiwan Pop uses it as the visual text foundation, conveying both 'New York streets' and 'Taiwanese identity' simultaneously. This identity system appears on the Cultural Center facade, event venues, branded merchandise, and outdoor media.",
    'cp-35-tag':'03 · NYTCC 35th',
    'cp-35-title':'Taiwanese Cultural<br>Center, 35 Years',
    'cp-35-p1':'The Taiwanese Cultural Center in New York (NYTCC) has been one of the most important windows for Taiwanese cultural exchange since its founding in 1991. The 35th anniversary in 2026 is the pivotal moment for this campaign.',
    'cp-35-p2':"Taiwan Pop seizes the 35th anniversary to launch an unprecedented city-scale cultural movement. The Cultural Center becomes more than an office building — it's the Taiwan cultural landmark of the entire summer. Its facade becomes a canvas, its lobby a gallery, becoming the spiritual anchor for Taiwanese living in the US.",
    'cp-35-stat1':'Years','cp-35-stat2':'Founded','cp-35-stat3':'Arts Events',
    'cp-partners-tag':'04 · Partners',
    'cp-partners-title':'Taiwan Pop Local Partners',
    'cp-partners-sub':"Step inside these venues and feel Taiwan's daily presence in New York",
    'cp-cat-bubble':'Bubble Tea','cp-cat-restaurant':'Taiwanese Cuisine','cp-cat-bookstore':'Books & Culture','cp-cat-art':'Art Space',
    'cp-partners-note':'* This is a preliminary list. The official partner venues will be announced before the events.',
    'cp-awe-tag':'05 · Brand Character',
    'cp-awe-title':'Meet a-We',
    'cp-awe-sub':'The face of Taiwan Pop — an infinitely growing cultural rare creature',
    'cp-awe-zh-name':'Infinite Growth Rare Creature',
    'cp-awe-attr-h':'Abilities',
    'cp-awe-attr1-name':'Continuous Bonus','cp-awe-attr1-desc':'Every new square leveled up accumulates power — the further you go, the stronger you become.',
    'cp-awe-attr2-name':'Domain Expansion','cp-awe-attr2-desc':'Enter new cultural territories, unlock new skills. The wider your Taiwan knowledge, the larger your domain.',
    'cp-awe-attr3-name':'Elastic Adapt','cp-awe-attr3-desc':'Flexible in any cultural setting — equally at home in concert halls and on street corners.',
    'cp-awe-attr4-name':'Charge & Release','cp-awe-attr4-desc':'Accumulate cultural energy with every correct answer, waiting for the perfect moment to unleash full power.',
    'cp-awe-form-front':'Front','cp-awe-form-back':'Back','cp-awe-form-left':'Left','cp-awe-form-right':'Right',
    'cp-awe-mission-h':'Four Missions',
    'cp-awe-mission1':'Explore Taiwan arts events and become a cultural guide in New York',
    'cp-awe-mission2':'Capture the Black Current perspective — document New York\'s Taiwanese moments on film',
    'cp-awe-mission3':'Connect Taiwanese living in the US, weaving individual stories into a shared network',
    'cp-awe-mission4':'Conquer the Taiwan Culture Board Game and earn your Taiwanese cultural title',
    'cp-awe-equip-h':'Equipment',
    'cp-awe-equip-name':'Infinite Storage Magic Bag',
    'cp-awe-equip-desc':'Can hold any form of Taiwanese cultural memory — music, images, food aromas, street marks — all stored, never lost.',
    'cp-film-tag':'06 · Film Camera Project',
    'cp-film-title':'Black Current View<br>Film Documentary',
    'cp-film-p1':'In an era ruled by instant shots and filters, Taiwan Pop chooses film.',
    'cp-film-p2':"We invite artists and Taiwanese living in the US to document the summer of 2026 in New York with film cameras — capturing Taiwanese moments in city corners: a bubble tea lifted, an ancient chant drifting across a plaza, a stroke of magenta graffiti on a brick wall.",
    'cp-film-p3':'These images will accumulate into a city image archive for the 35th anniversary of NYTCC, becoming the most authentic record of this summer. The grain of film is a deliberate choice — we want to preserve a warmth that cannot be perfectly replicated.',
    'cp-film-join':'Inquire About Participation →',
    'cp-film-badge':'FILM · NYC · 2026',
    'cp-press-tag':'07 · Media & Press',
    'cp-press-title':'Media & Partnership Inquiries',
    'cp-press-sub':'We welcome media interviews, collaboration invitations, and business partnerships',
    'cp-press-media-h':'Media Contact','cp-press-media-note':'Press releases, interview requests, image licensing',
    'cp-press-partner-h':'Partnership','cp-press-partner-note':'Brand partners, event sponsorship, co-branding',
    'cp-press-film-h':'Film Project Sign-up','cp-press-film-note':'Photography participation, submission, film camera rental',
    'cp-press-hours-h':'Office Hours',
    'cp-press-hours':'Mon – Fri<br>09:00 – 18:00 (TST)',
    'cp-press-hours-note':'We typically respond within 2 business days',
    /* Calendar internals */
    months:['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'],
    shortMonths:['JAN','FEB','MAR','APR','MAY','JUN','JUL','AUG','SEP','OCT','NOV','DEC'],
    weekdays:['Sun','Mon','Tue','Wed','Thu','Fri','Sat'],
    calTitle:(y,mn)=>`${mn} ${y}`,
  }
};
