'use strict';

/* ---------- Language Strings (ZH / EN) ---------- */
const LANG = {
  zh: {
    /* Navbar */
    'nav-concept':'黑潮理念',
    'nav-news':'最新消息','nav-events':'展演活動','nav-awe':'a-we 紐約跑酷','nav-discover':'文化探索',
    'nav-calendar':'行事曆','nav-contact':'聯絡我們',
    /* a-we NYC Run */
    'game-awe-title':'a-we <span>紐約</span>跑酷',
    'game-awe-sub':'跑過紐約，跳越展演場館，探索 Taiwan Pop 文化活動',
    'sec-awe-title':'a-we 紐約跑酷',
    'sec-awe-sub':'跟著 a-We 跑過紐約，跳越展演場館，解鎖台灣文化活動資訊，登上排行榜！',
    'home-awe-cta':'來去跑酷！',
    /* Banner */
    'banner-sub':'台灣文化部 × Taipei Cultural Center in NY合作計畫<br>七大藝文展演，2026 紐約登場',
    'btn-explore':'探索活動','btn-news':'最新消息',
    /* Articles */
    'sec-news-title':'掌握動態',
    'sec-news-sub':'掌握 Taiwan Pop 計畫最新動態，了解台灣與紐約的文化對話',
    'art-1-cat':'官方公告',
    'art-1-title':'Taiwan Pop 計畫正式啟動！台灣文化將在紐約發聲',
    'art-1-desc':'台灣文化部攜手Taipei Cultural Center in NY，共同推出 Taiwan Pop 文化交流計畫，七大藝文展演於 2026 年在紐約各地精彩登場。',
    'art-2-cat':'活動預告',
    'art-2-title':'雲門舞集創辦人林懷民將赴紐約展開大師講座',
    'art-2-desc':'臺美藝文大師系列講座首場邀請林懷民現身紐約，暢談台灣當代藝術創作、身體美學與跨文化對話。',
    'art-3-cat':'活動預告',
    'art-3-title':'中央公園 SummerStage「Taiwanese Waves」盛夏登場',
    'art-3-desc':'Taiwan Pop 壓軸活動確認進駐紐約著名戶外演出場地 SummerStage，帶來融合台灣當代音樂與視覺的跨界演出。',
    'art-4-cat':'專題報導',
    'art-4-title':'什麼是 Taiwan Pop？一個讓台灣文化被看見的計畫',
    'art-4-desc':'從當代舞蹈、原住民古謠、街頭藝術到電影影展，Taiwan Pop 不只是音樂，而是多元台灣文化的全面展演。',
    'btn-more-news':'查看全部',
    /* Concept */
    'concept-title':'臺灣<em>尚趴</em>',
    'concept-slogan':'臺灣尚趴 · 曼哈頓的臺灣日常',
    'concept-manifesto':'黑潮，從臺灣東岸出發、持續向北流動的暖流。它有自己的溫度、方向與速度。穿越日本海域，橫渡太平洋，帶著熱帶的記憶進入寒冷的水域，在不知不覺中改變那裡的溫度。2026 年的夏天，這些長年累積的能量，將重新轉化——在音樂廳的舞台上、電影院的銀幕前、布魯克林的牆面、哈德遜河岸的草地、遊行的人群之中，以及你手中那杯手搖飲的杯身，臺灣文化將常態地出現在曼哈頓的生活場域裡。',
    'concept-p1-title':'身體與聲音｜Feel the Beat.',
    'concept-p1-subtitle':'臺灣文化，有屬於自己的脈搏與節奏',
    'concept-p1-desc':'從泰武山上傳承千年的排灣古謠，到當代舞台上精準到毫秒的舞蹈；從爵士樂手在跨文化合奏中的即興延展，到中央公園夏日舞台上向整座城市釋放的聲音能量。不同形式之間，各自保有節奏，同時在深處產生共鳴與共振。<br><br><strong>這個節奏存在於身體、聲音，以及現場的空氣之中。</strong><br><br>這個夏天，國家交響樂團與泰武古謠傳唱者在紐約交織出島嶼的聲音根系；翃舞製作透過身體語言，觸及語言難以抵達的感受；Taiwanese Waves 集結於中央公園夏日舞台，使臺灣的聲音成為城市記憶的一部分。砲臺舞蹈節在哈德遜河岸展開，偶戲藝穗節於克萊門特中心開演，徐崇育爵士樂團橫跨紐約與邁阿密巡演。<br><br>節奏在城市不同角落同時落地。<br>唯有置身其中，才能真正感受。',
    'concept-p2-title':'影像與敘事｜Feel the Story.',
    'concept-p2-subtitle':'臺灣是一個持續生成故事的地方。',
    'concept-p2-desc':'這座島嶼的地理多重交疊，歷史並行展開，認同在流動中成形。長時間的交錯與轉換，培養出一種觀看世界的方式。多元的視角和語言，敘事保持開放。創作者往往在時代的縫隙之中，從邊界觀看，再將視野轉譯成可以被感知的形式。<br><br>這種轉譯能力，使臺灣影像與藝術在國際場域中持續留下痕跡，也讓個體經驗能跨越距離，被他人理解與接住。<br><br>這個夏天，林懷民於紐約的講座，將帶來身體創作與時代交織的視角。臺灣主題影展以整整一個月的時間，展開電影所構築的多重現實。紐約亞洲影展臺灣明星計畫，讓陳玉勳、廖克發等導演的新作站上美東重要的電影平台。鄭淑麗於 Leslie-Lohman 美術館的委製個展，以互動影像裝置探問觀看本身的政治與詩性，在城市中留下當代藝術的刻度。<br><br>每一個故事都是入口。<br>走進去，將遇見另一種觀看世界的方式。',
    'concept-p3-title':'街頭與生活｜Feel the Vibe.',
    'concept-p3-subtitle':'臺灣文化在不同環境中，始終保有蓬勃的生命力。',
    'concept-p3-desc':'在歷史長軸中，臺灣文化形態具備高度的適應力。它能在不同語境中落地，在異質的文化場域中持續延伸，並以當下的語言與環境對話，同時維持自身的核心氣質。這種狀態來自清晰的自我認知，也帶來一種自然的從容。<br><br><strong>多元並存，使文化更加飽滿。</strong><br><br>這個夏天，臺灣文化將帶著＿＿＿＿＿＿＿＿，進入曼哈頓各種生活現場。在布希維克街頭藝術節，臺灣創作與紐約塗鴉並置於街區牆面上，直接的對話；六月的同志大遊行中，臺灣的多元價值與城市的能量交會，彼此放大；台灣將出現在城市日常的各個角落，以不同形式滲入曼哈頓的生活中。<br><br>臺灣蓬勃的文化生命力，總能在各個角落找到自己的位置。',
    /* Concept hero — structured content */
    'concept-kuro':'黑潮理念',
    'concept-pop':'臺灣尚趴',
    'concept-nyc':'曼哈頓的臺灣日常',
    'concept-sub1':'黑潮，從臺灣東岸出發、持續向北流動的暖流',
    'concept-sub1-body':'它有自己的溫度、方向與速度。穿越日本海域，橫渡太平洋，帶著熱帶的記憶進入寒冷的水域，在不知不覺中改變那裡的溫度。',
    'concept-sub2':'臺灣文化在世界之中的移動，也有類似的軌跡',
    'concept-sub2-body':'紐約文化中心在紐約已走過三十五年。這段時間裡，無數音樂會、展覽、電影與講座，在曼哈頓的核心持續發聲。這些內容沒有急於定義臺灣的位置，而是在累積一種被看見、被感受的經驗。聲音、影像、身體與故事，自然地進入這座城市的感知之中。',
    'concept-sub3':'2026年的夏天，這些長年累積的能量，將重新轉化',
    'concept-sub3-body':'將文化滲入城市的日常紋理中，在音樂廳的舞台上、電影院的銀幕前、布魯克林的牆面、哈德遜河岸的草地、遊行的人群之中，以及你手中那杯手搖飲的杯身。臺灣文化將常態地出現在曼哈頓的生活場域裡。',
    'concept-closing':'流動本身，自帶方向與力量。',
    'concept-themes-label':'三大展演策略 · Three Themes',
    'concept-expand-hint':'點擊展開',
    /* Events */
    'sec-events-title':'展演活動',
    'sec-events-sub':'2026 年，十二場跨領域藝文展演，以三大主題在紐約呈現最真實的台灣',
    'cat-sound-label':'身體與聲音',
    'cat-sound-sub':'現場表演・音樂・舞蹈',
    'cat-image-label':'影像與敘事',
    'cat-image-sub':'電影・視覺藝術・文學',
    'cat-street-label':'街頭與生活',
    'cat-street-sub':'藝術節・遊行・城市現場',
    'event-cta':'了解更多・立即報名 →',
    /* Discover */
    'sec-discover-title':'探索台灣 × 紐約',
    'sec-discover-sub':'滑動地圖，找到每場活動的地點，點擊開始你的台灣文化探索之旅',
    'map-hint':'← 滑動探索地圖 →',
    'map-prefix':'已探索','map-suffix':'個台灣文化主題',
    /* Calendar */
    'sec-cal-title':'活動行事曆',
    'sec-cal-sub':'掌握所有活動日期，提前規劃您的參與計畫',
    'cal-upcoming-h':'近期活動','cal-legend':'活動日期（點擊查看詳情）','cal-no-events':'暫無近期活動','cal-view-detail':'查看詳情 →',
    /* Footer */
    'footer-desc':'Taiwan Pop 是台灣文化部與Taipei Cultural Center in NY合作的年度文化交流計畫，透過七大藝文展演讓台灣被世界看見。',
    'footer-links-h':'快速連結','footer-contact-h':'聯絡資訊',
    'footer-news':'最新消息','footer-events':'展演活動','footer-discover':'文化探索',
    'footer-cal':'行事曆','footer-hours':'週一至週五 09:00–18:00 (TST)',
    /* Map Pins */
    'pin-1':'林懷民講座','pin-2':'NSO × 泰武古謠','pin-3':'布希維克街頭藝術節',
    'pin-4':'臺灣主題影展','pin-5':'紐約同志大遊行','pin-6':'翃舞製作','pin-7':'Taiwanese Waves',
    /* Modal */
    'modal-cta':'了解更多詳情 →',
    /* Quiz UI */
    'quiz-back':'← 返回地圖',
    'quiz-next-q':'下一題 →','quiz-see-result':'查看結果 →',
    'quiz-retry':'再試一次','quiz-back-map':'回到地圖 ↗',
    'quiz-res-perfect':'完美！你對台灣文化的了解讓我們驕傲！',
    'quiz-res-good':'答得不錯！你已經對台灣有相當的認識了。',
    'quiz-res-keep':'繼續加油！台灣的故事等著你慢慢探索。',
    /* Celebration */
    'cel-title':'台灣文化全制霸！',
    'cel-sub':'你以全滿分征服了所有七大主題！<br>對台灣文化的熱情與了解，令我們驕傲。',
    'cel-badge':'✨ 七大文化探索者 ✨',
    'cel-invite':'準備好親臨紐約，感受這些文化盛事了嗎？',
    'cel-to-events':'前往活動頁面 →','cel-close':'繼續探索',
    /* Concept Page */
    'cp-hero-title':'黑潮理念',
    'cp-hero-sub':'黑潮計畫 — Feel the Pop · 臺灣尚趴<br>2026 年夏天，台灣文化融入曼哈頓的生活日常',
    'cp-origin-tag':'01 · 活動緣起',
    'cp-origin-title':'黑潮，從臺灣東岸出發',
    'cp-origin-p1':'Taiwan Pop 是台灣文化部與駐紐約臺北文化中心（TCCNY）共同推動的年度文化交流計畫。以 TCCNY 在紐約深耕三十五年為起點，2026 年選擇以最當代的藝文形式，重新定義台灣在這座城市的文化位置。',
    'cp-origin-p2':'七大展演橫跨音樂、舞蹈、影像、街頭藝術，Taiwan Pop 不以文化觀光的視角出發，而是以創作者的姿態切入紐約的文化生態——讓台灣的聲音、故事與能量，真正成為這座城市的一部分。',
    'cp-origin-p3':'2026 年的夏天，這些長年累積的能量，將重新轉化——將文化滲入城市的日常紋理中，在音樂廳的舞台上、電影院的銀幕前、布魯克林的牆面、哈德遜河岸的草地、遊行的人群之中，以及你手中那杯手搖飲的杯身。臺灣文化將常態地出現在曼哈頓的生活場域裡。',
    'cp-id-tag':'02 · 品牌識別',
    'cp-id-title':'Semi-Wildstyle<br>主視覺美學',
    'cp-id-sub':'以紐約塗鴉文化為語言，書寫台灣的當代宣言',
    'cp-id-c1-title':'Magenta 洋紅',
    'cp-id-c1-desc':'#F52281 — 台灣的熱度，是這個計畫的主調。霓虹般的洋紅，讓台灣在曼哈頓的夜晚無法被忽視。',
    'cp-id-c2-title':'Neon Green 螢光綠',
    'cp-id-c2-desc':'#00FF00 — 街頭噴漆的生命力，是塗鴉文化與台灣活力的共同語言。',
    'cp-id-c3-title':'Pure White 純白',
    'cp-id-c3-desc':'#FFFFFF — 反差底色，讓文字在純黑底上發光，如同深夜街頭的塗鴉。',
    'cp-id-note':'Semi-Wildstyle 是介於可辨讀與抽象之間的塗鴉字體風格。Taiwan Pop 以此作為主視覺文字基底，在視覺上同時傳遞「紐約街頭」與「台灣個性」的雙重身份。這套識別系統將持續出現在紐文中心外觀、活動現場、聯名周邊與街頭媒體上。',
    'cp-35-tag':'03 · 紐文35背景',
    'cp-35-title':'紐文中心<br>三十五年',
    'cp-35-p1':'駐紐約臺北文化中心（Taipei Cultural Center in New York，TCCNY）由中華民國文化部設立，自 1990 年起在紐約持續推動台灣文化的國際交流，至今已走過三十五年。',
    'cp-35-p2':'透過音樂會、展覽、電影、講座等多元節目形式，TCCNY 在曼哈頓核心持續發聲，讓台灣的聲音、影像與故事自然融入這座城市的文化生活。Taiwan Pop 正是在這個三十五年的基礎上，以最當代的姿態，向紐約展示台灣。',
    'cp-35-stat1':'週年','cp-35-stat2':'創立年份','cp-35-stat3':'藝文展演',
    'cp-partners-tag':'04 · 聯名商家',
    'cp-partners-title':'聯名夥伴',
    'cp-partners-sub':'走進這些地方，感受台灣文化在紐約的日常存在',
    'cp-cat-bubble':'手搖飲','cp-cat-restaurant':'台灣料理','cp-cat-bookstore':'書店・文創','cp-cat-art':'藝術空間',
    'cp-partners-note':'* 以上為示意清單，正式聯名商家名單將於活動前公布',
    'cp-awe-tag':'05 · 品牌角色',
    'cp-awe-title':'認識 a-We',
    'cp-awe-sub':'Taiwan Pop 的形象大使，無限成長的文化稀有寶',
    'cp-awe-zh-name':'無限成長稀有寶',
    'cp-awe-attr-h':'能力屬性',
    'cp-awe-attr1-name':'連續加成','cp-awe-attr1-desc':'每次踩上新格子，能力值就累積增長，越走越強。',
    'cp-awe-attr2-name':'領域展開','cp-awe-attr2-desc':'涉足文化領域，解鎖新技能，台灣知識越廣，領域越大。',
    'cp-awe-attr3-name':'伸縮自如','cp-awe-attr3-desc':'能屈能伸，適應任何文化場域，從音樂廳到街頭都自在。',
    'cp-awe-attr4-name':'集氣蓄力','cp-awe-attr4-desc':'每次答對問題蓄積文化能量，等待最佳時機全力爆發。',
    'cp-awe-form-front':'正面','cp-awe-form-back':'背面','cp-awe-form-left':'左側','cp-awe-form-right':'右側',
    'cp-awe-mission-h':'四大任務',
    'cp-awe-mission1':'探索台灣藝文展演，成為紐約的文化嚮導',
    'cp-awe-mission2':'記錄黑潮視角，用底片留住城市的台灣時刻',
    'cp-awe-mission3':'聯結旅美台灣人，讓彼此的故事交織成網',
    'cp-awe-mission4':'征服文化大富翁，以知識換取台灣文化稱號',
    'cp-awe-equip-h':'專屬裝備',
    'cp-awe-equip-name':'無限儲存空間魔法袋',
    'cp-awe-equip-desc':'可裝下任何形式的台灣文化記憶——音樂、影像、食物香氣、街頭印記，全部收納，永不遺失。',
    'cp-film-tag':'06 · 底片機計畫',
    'cp-film-title':'黑潮視角<br>底片機紀實',
    'cp-film-p1':'在快拍與濾鏡統治的時代，Taiwan Pop 選擇底片。',
    'cp-film-p2':'我們邀請藝術工作者、旅美台灣人，以底片相機記錄 2026 年夏天的紐約——那些在城市角落發生的台灣時刻：一杯手搖飲被舉起、一段古謠在廣場流動、一抹塗鴉的洋紅出現在磚牆上。',
    'cp-film-p3':'這些影像將累積成紐文中心35週年的城市圖像檔案，成為這個夏天最真實的台灣記錄。底片的顆粒感，是刻意的選擇——我們想要留下的，是那種無法完美複製的溫度。',
    'cp-film-join':'洽詢參與方式 →',
    'cp-film-badge':'底片 · 紐約 · 2026',
    'cp-press-tag':'07 · 媒體洽詢',
    'cp-press-title':'媒體與合作洽詢',
    'cp-press-sub':'歡迎媒體採訪、合作邀約與商業洽談，請透過以下方式聯絡我們',
    'cp-press-media-h':'媒體聯絡','cp-press-media-note':'新聞稿索取、採訪申請、圖片授權',
    'cp-press-partner-h':'合作洽詢','cp-press-partner-note':'聯名商家、活動贊助、品牌合作',
    'cp-press-film-h':'底片機計畫報名','cp-press-film-note':'攝影參與、作品投稿、底片借用申請',
    'cp-press-hours-h':'服務時間',
    'cp-press-hours':'週一至週五<br>09:00 – 18:00 (TST)',
    'cp-press-hours-note':'通常於 2 個工作日內回覆',
    /* Concept page — inline content (manifesto / origin / strategy / themes / nytcc) */
    'cp-manifesto-big':'Feel the Pop<br>臺灣尚趴',
    'cp-manifesto-p1':'「黑潮」是環繞台灣的強勁洋流，從菲律賓海域出發，沿台灣東岸北上，流向日本與北太平洋。我們以此為名，象徵台灣文化的強勁能量，帶著自信與創造力，流向世界。',
    'cp-manifesto-p2':'2026 年夏天，Taiwan Pop 計畫讓台灣登上紐約的舞台——不是以異國情調展示，而是以平等、當代的姿態，融入城市脈動，讓紐約人感受台灣的 Pop。',
    'cp-origin-big':'台灣文化部<br>× 紐文 35',
    'cp-strategy-title':'三大策展策略',
    'cp-strat-1-body':'Taiwan Pop 不是一個在博物館或劇院內的封閉展演，而是走進紐約人的公園、街頭與生活。從 SummerStage 到布希維克街頭，台灣的節奏就在城市的每個角落。',
    'cp-strat-2-body':'NSO 與泰武古謠的跨界合作，翃舞以原住民文化為靈感的當代舞蹈——Taiwan Pop 不斷在傳統與當代之間找到最有力的對話。',
    'cp-strat-3-body':'台灣文化在紐約的呈現，是以平等夥伴而非異國展示的姿態。與紐約在地機構的深度合作，確保每個展演都真正融入紐約的文化脈絡。',
    'cp-themes-title':'身體・影像・街頭',
    'cp-theme-sound-desc':'臺灣節奏在紐約起舞。現場表演、音樂與舞蹈，讓身體成為跨文化溝通的語言。',
    'cp-theme-image-desc':'臺灣故事在銀幕上說。透過電影、視覺藝術與文學，傳遞台灣的當代視角。',
    'cp-theme-street-desc':'臺灣氣味融入曼哈頓。從街頭藝術到同志大遊行，台灣的活力在城市中發聲。',
    'cp-35-title':'Taipei Cultural Center in NY<br>35 週年',
    /* Concept — strategy card titles */
    'cp-strat-1-title':'融入生活日常',
    'cp-strat-2-title':'當代與傳統對話',
    'cp-strat-3-title':'平等的文化交流',
    /* Concept — theme event list items */
    'cp-ev-sound-1':'林懷民 × 美國舞蹈節 對談',
    'cp-ev-sound-2':'NSO《來自臺灣》',
    'cp-ev-sound-3':'翃舞製作《羽人》',
    'cp-ev-sound-4':'臺灣之夜 @ SummerStage',
    'cp-ev-sound-5':'嚴俊傑鋼琴講座暨示範演出',
    'cp-ev-image-1':'世界之間：臺灣電影',
    'cp-ev-image-2':'紐約亞洲影展・鄭淑麗個展',
    'cp-ev-street-1':'布希維克街頭藝術計畫',
    'cp-ev-street-2':'紐約同志大遊行',
    /* Index showcase stats */
    'stat-1-desc':'橫跨聲音、影像、街頭三大主題，七個精彩展演在紐約登場',
    'stat-2-desc':'身體與聲音・影像與敘事・街頭與生活',
    'stat-3-desc':'Feel the Pop · 臺灣尚趴 — 2026 夏天，曼哈頓感受台灣創造力',
    'tc-link':'看活動 <span class="arr">→</span>',
    'bc-ev-city':'2026 夏天・曼哈頓',
    /* News page */
    'news-page-title':'掌握<br>動態',
    'news-page-sub':'Taiwan Pop 計畫最新動態，了解台灣與紐約的文化對話',
    'news-cat-all':'全部',
    'news-cat-announce':'官方公告',
    'news-cat-preview':'活動預告',
    'news-cat-feature':'專題報導',
    'news-cat-media':'媒體報導',
    'news-load-more':'載入更多',
    'news-loading':'載入中',
    'news-empty':'暫無文章',
    /* Calendar internals */
    months:['1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月'],
    shortMonths:['JAN','FEB','MAR','APR','MAY','JUN','JUL','AUG','SEP','OCT','NOV','DEC'],
    weekdays:['日','一','二','三','四','五','六'],
    calTitle:(y,mn)=>`${y} 年 ${mn}`,
  },
  en: {
    /* Navbar */
    'nav-concept':'Black Current',
    'nav-news':'News','nav-events':'Events','nav-awe':'a-we NYC Run','nav-discover':'Discover',
    'nav-calendar':'Calendar','nav-contact':'Contact',
    /* a-we NYC Run */
    'game-awe-title':'a-we <span>NYC</span> Run',
    'game-awe-sub':'Run through NYC, jump over venues, discover Taiwan Pop events',
    'sec-awe-title':'a-we NYC Run',
    'sec-awe-sub':'Run through New York with a-We, leap over event venues, unlock cultural event info, and claim your spot on the leaderboard!',
    'home-awe-cta':'Let\'s Run!',
    /* Banner */
    'banner-sub':'Taiwan Ministry of Culture × Taipei Cultural Center in NY<br>Seven Cultural Events, New York 2026',
    'btn-explore':'Explore Events','btn-news':'Latest News',
    /* Articles */
    'sec-news-title':'Latest News',
    'sec-news-sub':'Stay up to date with Taiwan Pop and the cultural dialogue between Taiwan and New York',
    'art-1-cat':'Announcement',
    'art-1-title':'Taiwan Pop Officially Launched — Taiwan Culture Coming to New York',
    'art-1-desc':"Taiwan's Ministry of Culture and Taipei Cultural Center in NY jointly launch the Taiwan Pop cultural exchange, bringing seven spectacular arts events across New York in 2026.",
    'art-2-cat':'Preview',
    'art-2-title':'Cloud Gate Founder Lin Hwai-min to Give Masterclass in New York',
    'art-2-desc':"The first Taiwan-US Arts Master Series invites Lin Hwai-min to New York to share his five-decade creative journey and Taiwan's contemporary arts with the world.",
    'art-3-cat':'Preview',
    'art-3-title':'"Taiwanese Waves" at Central Park SummerStage This Summer',
    'art-3-desc':"Taiwan Pop's grand finale is confirmed at New York's iconic outdoor venue SummerStage, featuring a cross-disciplinary show blending Taiwan's contemporary music and visual arts.",
    'art-4-cat':'Feature',
    'art-4-title':"What Is Taiwan Pop? A Campaign to Put Taiwan's Culture on the World Stage",
    'art-4-desc':"From contemporary dance and indigenous chants to street art and film — Taiwan Pop is more than music. It's a full showcase of Taiwan's diverse cultural identity.",
    'btn-more-news':'View All',
    /* Concept */
    'concept-title':'Taiwan <em>Pops</em>',
    'concept-slogan':'Taiwan Pops · Taiwanese Daily Life in Manhattan',
    'concept-manifesto':"The Black Current flows north from Taiwan's eastern coast — carrying its own temperature, direction, and momentum. Crossing the waters of Japan, traversing the Pacific, it brings tropical memory into cold waters and quietly changes the temperature of wherever it arrives. In the summer of 2026, this long-accumulated energy transforms — on concert hall stages, cinema screens, Brooklyn walls, Hudson River lawns, and in the crowds of the Pride March. Taiwan's culture will be a constant presence in the fabric of daily life in Manhattan.",
    'concept-p1-title':'Body & Sound｜Feel the Beat.',
    'concept-p1-subtitle':'Taiwanese culture has its own pulse and rhythm.',
    'concept-p1-desc':"From thousand-year-old Paiwan chants carried down from Mount Taiwu, to dance choreographed with millisecond precision on the contemporary stage; from a jazz musician's improvisation in cross-cultural dialogue, to the wave of sound released toward the whole city at Central Park SummerStage. Between different forms, each keeps its own rhythm, while resonating deep within.<br><br><strong>This rhythm exists in the body, in sound, and in the air of the performance itself.</strong><br><br>This summer, the NSO and Taiwu chant singers weave the island's musical roots in New York; HORSE Dance Theatre communicates through physical language, reaching where words cannot; Taiwanese Waves gathers at Central Park SummerStage, making Taiwan's sound part of the city's memory. The Fortress Dance Festival unfolds along the Hudson, the International Puppet Festival opens at the Clement Center, and the Joshua Xu Jazz Band tours New York and Miami.<br><br>Rhythm landing simultaneously in different corners of the city.<br>You have to be there to truly feel it.",
    'concept-p2-title':'Image & Narrative｜Feel the Story.',
    'concept-p2-subtitle':'Taiwan is a place that continuously generates stories.',
    'concept-p2-desc':"This island's geography overlaps in multiple layers, its histories unfold in parallel, and its identity takes shape in motion. Long periods of exchange and transformation have cultivated a way of seeing the world. With diverse perspectives and languages, narrative stays open. Creators work in the gaps between eras, looking from the margins, translating their vision into forms that can be felt.<br><br>This power of translation allows Taiwanese cinema and art to leave continuous traces internationally, and lets individual experience cross distances — to be understood and caught by others.<br><br>This summer, Lin Hwai-min's lecture in New York brings perspectives on body and creation across time. The Taiwan Film Festival unfolds a full month of cinema's multiple realities. The NYAFF Taiwan Star Project brings new works by Chen Yu-hsun, Midi Z and others to major East Coast screens. Shu Lea Cheang's commissioned exhibition at Leslie-Lohman Museum interrogates the politics and poetics of looking — leaving a mark of contemporary art in the city.<br><br>Every story is an entry point.<br>Walk inside, and you will find another way of seeing the world.",
    'concept-p3-title':'Street & Life｜Feel the Vibe.',
    'concept-p3-subtitle':"Taiwan's culture retains its vitality in every environment.",
    'concept-p3-desc':"Throughout its long history, Taiwanese culture has developed a high degree of adaptability. It takes root in different contexts, extends itself in foreign cultural terrain, speaks in the language of the present while maintaining its essential character. This quality comes from a clear sense of self, and brings with it a natural ease.<br><br><strong>Diversity makes culture richer.</strong><br><br>This summer, Taiwanese culture will bring ________ into the everyday spaces of Manhattan. At the Bushwick Block Party, Taiwanese art stands side by side with New York graffiti on neighborhood walls — a direct dialogue. In June's Pride March, Taiwan's values of plurality meet the city's energy and amplify each other. Taiwan will appear in every corner of daily city life, seeping into Manhattan in many forms.<br><br>Taiwan's vibrant cultural life force will always find its place in every corner.",
    /* Concept hero — structured content */
    'concept-kuro':'The Kuroshio Philosophy',
    'concept-pop':'Taiwan Pop',
    'concept-nyc':"Manhattan's Taiwan Daily Life",
    'concept-sub1':"Kuroshio — a warm current flowing north from Taiwan's east coast",
    'concept-sub1-body':"It carries its own temperature, direction, and speed. Crossing the waters of Japan, traversing the Pacific, it brings tropical memories into cold waters, quietly changing the temperature of wherever it flows.",
    'concept-sub2':'Taiwanese culture moving through the world follows a similar trajectory',
    'concept-sub2-body':"The Taiwan Center New York has been part of this city for thirty-five years. In that time, countless concerts, exhibitions, films, and lectures have resonated at the heart of Manhattan. These works never rushed to define Taiwan's place — instead, they accumulated a kind of presence: to be seen, to be felt. Sound, image, body, and story, entering the city's consciousness naturally.",
    'concept-sub3':'In the summer of 2026, these long-accumulated energies will transform',
    'concept-sub3-body':"Culture seeping into the city's daily texture — on concert hall stages, cinema screens, Brooklyn walls, Hudson riverbank grass, in the crowds of the parade, and on the cup in your hand. Taiwan's culture will appear as a constant in the everyday life of Manhattan.",
    'concept-closing':'A current carries its own direction and force.',
    'concept-themes-label':'Three Themes · 三大展演策略',
    'concept-expand-hint':'Click to expand',
    /* Events */
    'sec-events-title':'Performances',
    'sec-events-sub':'Twelve cross-disciplinary arts events in 2026, presenting the most authentic Taiwan in New York across three themes',
    'cat-sound-label':'Body & Sound',
    'cat-sound-sub':'Live Performance · Music · Dance',
    'cat-image-label':'Image & Narrative',
    'cat-image-sub':'Film · Visual Arts · Literature',
    'cat-street-label':'Street & Life',
    'cat-street-sub':'Festival · Parade · Urban Scene',
    'event-cta':'Learn More · Register →',
    /* Discover */
    'sec-discover-title':'Discover Taiwan × New York',
    'sec-discover-sub':"Scroll the map to find each event's location. Click to begin your Taiwan cultural exploration",
    'map-hint':'← Scroll to Explore →',
    'map-prefix':'Explored','map-suffix':'Cultural Themes',
    /* Calendar */
    'sec-cal-title':'Event Calendar',
    'sec-cal-sub':'Mark your calendar and plan your visit in advance',
    'cal-upcoming-h':'Upcoming Events','cal-legend':'Event Date (click to view)','cal-no-events':'No upcoming events','cal-view-detail':'View Details →',
    /* Footer */
    'footer-desc':'Taiwan Pop is an annual cultural exchange program by the Taiwan Ministry of Culture and Taipei Cultural Center in NY, showcasing Taiwan to the world through seven arts events.',
    'footer-links-h':'Quick Links','footer-contact-h':'Contact',
    'footer-news':'News','footer-events':'Events','footer-discover':'Discover',
    'footer-cal':'Calendar','footer-hours':'Mon–Fri 09:00–18:00 (TST)',
    /* Map Pins */
    'pin-1':'Lin Hwai-min Lecture','pin-2':'NSO × Taiwu Ballads','pin-3':'Bushwick Street Art Festival',
    'pin-4':'Taiwan Film Festival','pin-5':'NYC Pride March','pin-6':'H·Art·Ch Dance','pin-7':'Taiwanese Waves',
    /* Modal */
    'modal-cta':'Learn More →',
    /* Quiz UI */
    'quiz-back':'← Back to Map',
    'quiz-next-q':'Next →','quiz-see-result':'See Results →',
    'quiz-retry':'Try Again','quiz-back-map':'Back to Map ↗',
    'quiz-res-perfect':'Perfect! Your knowledge of Taiwanese culture fills us with pride!',
    'quiz-res-good':'Well done! You already have a solid understanding of Taiwan.',
    'quiz-res-keep':"Keep going! The story of Taiwan is waiting to be explored.",
    /* Celebration */
    'cel-title':'Taiwan Cultural Grand Master!',
    'cel-sub':"You've aced all seven themes with a perfect score!<br>Your passion and knowledge of Taiwanese culture fills us with pride.",
    'cel-badge':'✨ Seven Cultural Explorer ✨',
    'cel-invite':'Ready to experience these cultural events in New York?',
    'cel-to-events':'Go to Events →','cel-close':'Keep Exploring',
    /* Concept Page */
    'cp-hero-title':'Black Current',
    'cp-hero-sub':'The Kuroshio Initiative — Feel the Pop · Taiwan Pops<br>Summer 2026, Taiwan culture becomes part of Manhattan\'s everyday life',
    'cp-origin-tag':'01 · Origin',
    'cp-origin-title':'The Black Current,<br>Flowing North from Taiwan',
    'cp-origin-p1':"Taiwan Pop is an annual cultural exchange initiative co-led by Taiwan's Ministry of Culture and Taipei Cultural Center in New York (TCCNY). Built on TCCNY's 35 years of cultivating cultural presence in New York, 2026 marks a new chapter — redefining Taiwan's cultural identity in this city through the most contemporary arts forms.",
    'cp-origin-p2':"Seven events spanning music, dance, film, and street art — Taiwan Pop doesn't approach this from the angle of cultural tourism. Instead, it enters New York's cultural ecosystem as a creator — letting Taiwan's sounds, stories, and energy truly become part of this city.",
    'cp-origin-p3':"In the summer of 2026, this long-accumulated energy transforms — permeating the fabric of daily city life. On concert hall stages, cinema screens, Brooklyn walls, Hudson River lawns, in the crowds of the Pride March, and on the cup in your hand. Taiwan's culture will be a constant presence in the everyday spaces of Manhattan.",
    'cp-id-tag':'02 · Visual Identity',
    'cp-id-title':'Semi-Wildstyle<br>Visual Aesthetic',
    'cp-id-sub':'Speaking through New York graffiti culture, writing Taiwan\'s contemporary declaration',
    'cp-id-c1-title':'Magenta',
    'cp-id-c1-desc':"#F52281 — Taiwan's heat is this campaign's keynote. Neon magenta ensures Taiwan cannot be ignored in Manhattan's nights.",
    'cp-id-c2-title':'Neon Green',
    'cp-id-c2-desc':"#00FF00 — The vitality of street spray paint, the shared language of graffiti culture and Taiwan's energy.",
    'cp-id-c3-title':'Pure White',
    'cp-id-c3-desc':'#FFFFFF — High-contrast base, letting text glow against pure black, like graffiti on a midnight wall.',
    'cp-id-note':"Semi-Wildstyle sits between legible and abstract graffiti lettering. Taiwan Pop uses it as the visual text foundation, conveying both 'New York streets' and 'Taiwanese identity' simultaneously. This identity system appears on the Cultural Center facade, event venues, branded merchandise, and outdoor media.",
    'cp-35-tag':'03 · NYTCC 35th',
    'cp-35-title':'Taiwanese Cultural<br>Center, 35 Years',
    'cp-35-p1':"The Taipei Cultural Center in New York (TCCNY), established by Taiwan's Ministry of Culture, has been promoting Taiwan's international cultural exchange in New York since 1990 — now spanning thirty-five years.",
    'cp-35-p2':"Through concerts, exhibitions, films, and lectures, TCCNY has continued to resonate at the heart of Manhattan, letting Taiwan's sounds, images, and stories naturally integrate into this city's cultural life. Taiwan Pop builds on these thirty-five years to present Taiwan to New York in the most contemporary way.",
    'cp-35-stat1':'Years','cp-35-stat2':'Founded','cp-35-stat3':'Arts Events',
    'cp-partners-tag':'04 · Partners',
    'cp-partners-title':'Our Partners',
    'cp-partners-sub':"Step inside these venues and feel Taiwan's daily presence in New York",
    'cp-cat-bubble':'Bubble Tea','cp-cat-restaurant':'Taiwanese Cuisine','cp-cat-bookstore':'Books & Culture','cp-cat-art':'Art Space',
    'cp-partners-note':'* This is a preliminary list. The official partner venues will be announced before the events.',
    'cp-awe-tag':'05 · Brand Character',
    'cp-awe-title':'Meet a-We',
    'cp-awe-sub':'The face of Taiwan Pop — an infinitely growing cultural rare creature',
    'cp-awe-zh-name':'Infinite Growth Rare Creature',
    'cp-awe-attr-h':'Abilities',
    'cp-awe-attr1-name':'Continuous Bonus','cp-awe-attr1-desc':'Every new square leveled up accumulates power — the further you go, the stronger you become.',
    'cp-awe-attr2-name':'Domain Expansion','cp-awe-attr2-desc':'Enter new cultural territories, unlock new skills. The wider your Taiwan knowledge, the larger your domain.',
    'cp-awe-attr3-name':'Elastic Adapt','cp-awe-attr3-desc':'Flexible in any cultural setting — equally at home in concert halls and on street corners.',
    'cp-awe-attr4-name':'Charge & Release','cp-awe-attr4-desc':'Accumulate cultural energy with every correct answer, waiting for the perfect moment to unleash full power.',
    'cp-awe-form-front':'Front','cp-awe-form-back':'Back','cp-awe-form-left':'Left','cp-awe-form-right':'Right',
    'cp-awe-mission-h':'Four Missions',
    'cp-awe-mission1':'Explore Taiwan arts events and become a cultural guide in New York',
    'cp-awe-mission2':'Capture the Black Current perspective — document New York\'s Taiwanese moments on film',
    'cp-awe-mission3':'Connect Taiwanese living in the US, weaving individual stories into a shared network',
    'cp-awe-mission4':'Conquer the Taiwan Culture Board Game and earn your Taiwanese cultural title',
    'cp-awe-equip-h':'Equipment',
    'cp-awe-equip-name':'Infinite Storage Magic Bag',
    'cp-awe-equip-desc':'Can hold any form of Taiwanese cultural memory — music, images, food aromas, street marks — all stored, never lost.',
    'cp-film-tag':'06 · Film Camera Project',
    'cp-film-title':'Black Current View<br>Film Documentary',
    'cp-film-p1':'In an era ruled by instant shots and filters, Taiwan Pop chooses film.',
    'cp-film-p2':"We invite artists and Taiwanese living in the US to document the summer of 2026 in New York with film cameras — capturing Taiwanese moments in city corners: a bubble tea lifted, an ancient chant drifting across a plaza, a stroke of magenta graffiti on a brick wall.",
    'cp-film-p3':'These images will accumulate into a city image archive for the 35th anniversary of NYTCC, becoming the most authentic record of this summer. The grain of film is a deliberate choice — we want to preserve a warmth that cannot be perfectly replicated.',
    'cp-film-join':'Inquire About Participation →',
    'cp-film-badge':'FILM · NYC · 2026',
    'cp-press-tag':'07 · Media & Press',
    'cp-press-title':'Media & Partnership Inquiries',
    'cp-press-sub':'We welcome media interviews, collaboration invitations, and business partnerships',
    'cp-press-media-h':'Media Contact','cp-press-media-note':'Press releases, interview requests, image licensing',
    'cp-press-partner-h':'Partnership','cp-press-partner-note':'Brand partners, event sponsorship, co-branding',
    'cp-press-film-h':'Film Project Sign-up','cp-press-film-note':'Photography participation, submission, film camera rental',
    'cp-press-hours-h':'Office Hours',
    'cp-press-hours':'Mon – Fri<br>09:00 – 18:00 (TST)',
    'cp-press-hours-note':'We typically respond within 2 business days',
    /* Concept page — inline content */
    'cp-manifesto-big':'Feel the Pop<br>Taiwan Pops',
    'cp-manifesto-p1':'"Black Current" is the powerful ocean current surrounding Taiwan — flowing north from Philippine waters along Taiwan\'s eastern coast toward Japan and the North Pacific. We take this name to symbolize Taiwan\'s cultural energy flowing toward the world with confidence and creativity.',
    'cp-manifesto-p2':'In the summer of 2026, Taiwan Pop brings Taiwan onto the New York stage — not as exotic spectacle, but as an equal, contemporary presence woven into the city\'s pulse, letting New Yorkers feel Taiwan\'s Pop.',
    'cp-origin-big':'Ministry of Culture<br>× TCCNY 35',
    'cp-strategy-title':'Three Curatorial Strategies',
    'cp-strat-1-body':'Taiwan Pop isn\'t confined to museums or theaters — it moves into New Yorkers\' parks, streets, and daily lives. From SummerStage to Bushwick streets, Taiwan\'s rhythm lives in every corner of the city.',
    'cp-strat-2-body':'The cross-cultural collaboration of NSO and Taiwu ancient chants, HORSE Dance\'s contemporary movement inspired by indigenous culture — Taiwan Pop finds the most powerful dialogue between tradition and the contemporary.',
    'cp-strat-3-body':'Taiwan\'s cultural presence in New York comes as an equal partner, not an exotic display. Deep collaboration with local New York institutions ensures every event genuinely integrates into the city\'s cultural context.',
    'cp-themes-title':'Body · Image · Street',
    'cp-theme-sound-desc':'Taiwanese rhythm dances in New York. Live performance, music, and dance — letting the body become the language of cross-cultural communication.',
    'cp-theme-image-desc':'Taiwanese stories told on screen. Through film, visual art, and literature, conveying Taiwan\'s contemporary perspective.',
    'cp-theme-street-desc':'Taiwanese spirit woven into Manhattan. From street art to the Pride March, Taiwan\'s vitality speaks in the city.',
    'cp-35-title':'Taipei Cultural Center in NY<br>35th Anniversary',
    /* Concept — strategy card titles */
    'cp-strat-1-title':'Embedded in Daily Life',
    'cp-strat-2-title':'Contemporary Meets Traditional',
    'cp-strat-3-title':'Equal Cultural Exchange',
    /* Concept — theme event list items */
    'cp-ev-sound-1':'Lin Hwai-min × ADF in Conversation',
    'cp-ev-sound-2':'From Formosa: NSO US Tour',
    'cp-ev-sound-3':'HUNG DANCE — BIRDY',
    'cp-ev-sound-4':'Taiwanese Waves @ SummerStage',
    'cp-ev-sound-5':'Chun-Chieh Yen: Piano Lecture & Demonstration',
    'cp-ev-image-1':'Between Worlds: Taiwanese Cinema',
    'cp-ev-image-2':'NYAFF · Shu Lea Cheang Exhibition',
    'cp-ev-street-1':'Bushwick Collective Block Party',
    'cp-ev-street-2':'NYC Pride March',
    /* Index showcase stats */
    'stat-1-desc':'Seven flagship events across sound, image, and street — bringing Taiwan to New York',
    'stat-2-desc':'Body & Sound · Image & Narrative · Street & Life',
    'stat-3-desc':'Feel the Pop — Summer 2026, Manhattan feels Taiwan\'s creative energy',
    'tc-link':'View Events <span class="arr">→</span>',
    'bc-ev-city':'Summer 2026 · Manhattan',
    /* News page */
    'news-page-title':'Latest<br>News',
    'news-page-sub':'Stay up to date with Taiwan Pop and the cultural dialogue between Taiwan and New York',
    'news-cat-all':'All',
    'news-cat-announce':'Announcement',
    'news-cat-preview':'Preview',
    'news-cat-feature':'Feature',
    'news-cat-media':'Media',
    'news-load-more':'Load More',
    'news-loading':'Loading',
    'news-empty':'No articles found',
    /* Calendar internals */
    months:['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'],
    shortMonths:['JAN','FEB','MAR','APR','MAY','JUN','JUL','AUG','SEP','OCT','NOV','DEC'],
    weekdays:['Sun','Mon','Tue','Wed','Thu','Fri','Sat'],
    calTitle:(y,mn)=>`${mn} ${y}`,
  }
};
